// Enum /Script/ContextualAnimation.EContextualAnimIKTargetProvider
enum class EContextualAnimIKTargetProvider : uint8_t
{
  Autogenerated = 0,
  Bone = 1,
  EContextualAnimIKTargetProvider_MAX = 2
};