// Enum /Script/FortniteGame.EFortGlobalAction
enum class EFortGlobalAction : uint8_t
{
  TrapConfirm = 0,
  TrapPicker = 1,
  BuildConfirm = 2,
  PerformBuildingEditInteraction = 3,
  PerformBuildingImprovementInteraction = 4,
  SwitchQuickBar = 5,
  Use = 6,
  Reload = 7,
  InventoryOrChatHold = 8,
  GamepadChangeMaterialOrHarvestHold = 9,
  GamepadNextWeaponOrHarvestHold = 10,
  GamepadNextWeaponOrAltInteractOrHarvestHold = 11,
  ChangeMaterial = 12,
  Fire = 13,
  RotatePrimitiveClockwise = 14,
  Gadget1 = 15,
  Gadget2 = 16,
  Ability1 = 17,
  Ability2 = 18,
  Ability3 = 19,
  ToggleFullScreenMap = 20,
  ToggleInventory = 21,
  Jump = 22,
  Crouch = 23,
  ShoppingCartCoast = 24,
  GolfCartEBrake = 25,
  GolfCartForward = 26,
  GolfCartReverse = 27,
  GolfCartHonk = 28,
  GamepadToggleHarvestOrHoldCreativePhone = 29,
  GamepadToggleCreativePhoneWeapon = 30,
  Count = 31,
  EFortGlobalAction_MAX = 32
};