// Enum /Script/FortniteGame.EReplaySmokeTestStep
enum class EReplaySmokeTestStep : uint8_t
{
  Setup = 0,
  TogglePause = 1,
  StepForward = 2,
  StepBackward = 3,
  StepToEnd = 4,
  StepToBeginning = 5,
  SpeedUpPlayback = 6,
  SlowDownPlayback = 7,
  ToggleHideTimeline = 8,
  IterateCameraModes = 9,
  TogglePlayerOutlines = 10,
  ToggleNamePlates = 11,
  ToggleReplayRegion = 12,
  ZoomIn = 13,
  ZoomOut = 14,
  ToggleAutoFollowThirdPerson = 15,
  IncreaseExposure = 16,
  DecreaseExposure = 17,
  SetAutoExposure = 18,
  IncreaseAperture = 19,
  DecreaseAperture = 20,
  IncreaseFocalLength = 21,
  DecreaseFocalLength = 22,
  IncreaseFocusDistance = 23,
  DecreaseFocusDistance = 24,
  SetAutoFocus = 25,
  ToggleDamageEffects = 26,
  ToggleHideUI = 27,
  ToggleMap = 28,
  Reset = 29,
  MAX = 30
};