// BlueprintGeneratedClass /Game/Athena/Items/Consumables/AthenaConsumablesSharedFunctionLibrary.AthenaConsumablesSharedFunctionLibrary_C
// Size: 0x28
class UAthenaConsumablesSharedFunctionLibrary_C : public UBlueprintFunctionLibrary
{

	/* Functions */

	// Function /Game/Athena/Items/Consumables/AthenaConsumablesSharedFunctionLibrary.AthenaConsumablesSharedFunctionLibrary_C.SnapLocationToGrid (Has no native function)
	static void SnapLocationToGrid(struct FVector& Location, double& GridYOffset, double& GridZOffset, class UObject*& WorldContext, struct FVector& SnappedLocation, double& GridSizeZ, double& GridSizeXY, double& CallFuncBreakVectorX, double& CallFuncBreakVectorY, double& CallFuncBreakVectorZ, double& CallFuncSubtractDoubleDoubleReturnValue, double& CallFuncGridSnapFloatReturnValue, double& CallFuncGridSnapFloatReturnValue1, double& CallFuncGridSnapFloatReturnValue2, double& CallFuncSubtractDoubleDoubleReturnValue1, struct FVector& CallFuncMakeVectorReturnValue); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Athena/Items/Consumables/AthenaConsumablesSharedFunctionLibrary.AthenaConsumablesSharedFunctionLibrary_C.IsOverlappingDeployableBlockVolume (Has no native function)
	void IsOverlappingDeployableBlockVolume(class UObject*& WorldContextObject, float& BlockingAreaCheckRadius, struct FVector& Location, class UObject*& WorldContext, bool& bOverlapping, struct FScalableFloat& bBlockThrowableDeployVolumesEnabled, struct FName& BlockedTag, int& TempintArrayIndexVariable, bool& CallFuncIsValidReturnValue, int& TempintLoopCounterVariable, int& CallFuncAddIntIntReturnValue, struct TArray<class AActor*>& TempobjectVariable, bool& CallFuncGetValueAsBoolReturnValue, struct TArray<struct TEnumAsByte<EObjectTypeQuery>>& K2NodeMakeArrayArray, struct TArray<struct FHitResult>& CallFuncSphereTraceMultiForObjectsOutHits, bool& CallFuncSphereTraceMultiForObjectsReturnValue, int& CallFuncArrayLengthReturnValue, struct FHitResult& CallFuncArrayGetItem, bool& CallFuncLessIntIntReturnValue, bool& CallFuncBreakHitResultbBlockingHit, bool& CallFuncBreakHitResultbInitialOverlap, float& CallFuncBreakHitResultTime, float& CallFuncBreakHitResultDistance, struct FVector& CallFuncBreakHitResultLocation, struct FVector& CallFuncBreakHitResultImpactPoint, struct FVector& CallFuncBreakHitResultNormal, struct FVector& CallFuncBreakHitResultImpactNormal, class UPhysicalMaterial*& CallFuncBreakHitResultPhysMat, class AActor*& CallFuncBreakHitResultHitActor, class UPrimitiveComponent*& CallFuncBreakHitResultHitComponent, struct FName& CallFuncBreakHitResultHitBoneName, struct FName& CallFuncBreakHitResultBoneName, int& CallFuncBreakHitResultHitItem, int& CallFuncBreakHitResultElementIndex, int& CallFuncBreakHitResultFaceIndex, struct FVector& CallFuncBreakHitResultTraceStart, struct FVector& CallFuncBreakHitResultTraceEnd, bool& CallFuncIsValidReturnValue1, bool& CallFuncComponentHasTagReturnValue); // (Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent | Const)
};

