// BlueprintGeneratedClass /Game/Athena/AthenaFunctionLibrary.AthenaFunctionLibrary_C
// Size: 0x28
class UAthenaFunctionLibrary_C : public UBlueprintFunctionLibrary
{

	/* Functions */

	// Function /Game/Athena/AthenaFunctionLibrary.AthenaFunctionLibrary_C.SpawnLootFromArray (Has no native function)
	static void SpawnLootFromArray(struct TArray<struct FFortItemEntry>& Array, struct FVector& Position, struct FVector& Direction, int& OverrideMaxStackCount, bool& bToss, bool& bRandomRotation, bool& bBlockedFromAutoPickup, int& PickupInstigatorHandle, enum EFortPickupSourceTypeFlag& SourceType, enum EFortPickupSpawnSource& Source, class AFortPlayerController*& OptionalOwnerPC, bool& bPickupOnlyRelevantToOwner, class UObject*& WorldContext, struct TArray<class AFortPickup*>& ItemPickupsSpawned, struct TArray<class AFortPickup*>& PickupsSpawned, struct FName& LootTierData, int& CallFuncArrayLengthReturnValue, int& TempintLoopCounterVariable, bool& CallFuncLessIntIntReturnValue, int& CallFuncAddIntIntReturnValue, int& TempintArrayIndexVariable, struct FFortItemEntry& CallFuncArrayGetItem, class UFortWorldItemDefinition*& K2NodeDynamicCastAsFortWorldItemDefinition, bool& K2NodeDynamicCastbSuccess, class AFortPickup*& CallFuncK2SpawnPickupInWorldReturnValue, int& CallFuncArrayAddUniqueReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Athena/AthenaFunctionLibrary.AthenaFunctionLibrary_C.SetPOITextWithContextTag (Has no native function)
	static void SetPOITextWithContextTag(struct FGameplayTag& POITag, struct FGameplayTagContainer& ContextTags, class UObject*& WorldContext, int& CallFuncGetNumGameplayTagsInContainerReturnValue, bool& CallFuncIsServerReturnValue, bool& CallFuncGreaterEqualIntIntReturnValue, class AFortGameStateAthena*& CallFuncGetGameStateAthenaReturnValue, struct FGameplayTagContainer& CallFuncMakeGameplayTagContainerFromTagReturnValue, class UGSC_MiniMapDataOverride_C*& CallFuncGetComponentByClassReturnValue, int& CallFuncGetNumGameplayTagsInContainerReturnValue1, bool& CallFuncGreaterEqualIntIntReturnValue1, bool& CallFuncIsValidReturnValue, bool& CallFuncBooleanANDReturnValue); // (Static | Public | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Athena/AthenaFunctionLibrary.AthenaFunctionLibrary_C.GetPlayerGroundedZ (Has no native function)
	static void GetPlayerGroundedZ(class AFortPlayerPawn*& PlayerPawn, class UObject*& WorldContext, double& GroundZ, struct FVector& CallFuncK2GetActorLocationReturnValue, double& CallFuncBreakVectorX, double& CallFuncBreakVectorY, double& CallFuncBreakVectorZ, double& CallFuncSubtractDoubleDoubleReturnValue, double& CallFuncSubtractDoubleDoubleBImplicitCast); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Athena/AthenaFunctionLibrary.AthenaFunctionLibrary_C.ShouldAllowDeathEffects (Has no native function)
	static bool ShouldAllowDeathEffects(struct FGameplayTagContainer& DamageOrDeathTags, class UObject*& WorldContext); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Athena/AthenaFunctionLibrary.AthenaFunctionLibrary_C.GetActorMeshExtents (Has no native function)
	static void GetActorMeshExtents(class AActor*& Actor, class UObject*& WorldContext, struct FVector& BoundingBoxExtents, struct FVector& CurrentMin, struct FVector& CurrentMax, struct FVector& CallFuncGetActorBoundsOrigin, struct FVector& CallFuncGetActorBoundsBoxExtent, struct TArray<class UStaticMeshComponent*>& CallFuncK2GetComponentsByClassReturnValue, int& CallFuncArrayLengthReturnValue, int& CallFuncArrayLengthReturnValue1, bool& CallFuncGreaterIntIntReturnValue, int& TempintArrayIndexVariable, class UStaticMeshComponent*& CallFuncArrayGetItem, bool& CallFuncIsVisibleReturnValue, bool& CallFuncNotPreBoolReturnValue, bool& CallFuncBooleanANDReturnValue, struct FBox& CallFuncGetBoundingBoxReturnValue, int& TempintLoopCounterVariable, double& CallFuncBreakVectorX, double& CallFuncBreakVectorY, double& CallFuncBreakVectorZ, bool& CallFuncLessIntIntReturnValue, int& CallFuncAddIntIntReturnValue, double& CallFuncBreakVectorX1, double& CallFuncBreakVectorY1, double& CallFuncBreakVectorZ1, bool& CallFuncEqualEqualVectorVectorReturnValue, struct FVector& CallFuncSubtractVectorVectorReturnValue, double& CallFuncBreakVectorX2, double& CallFuncBreakVectorY2, double& CallFuncBreakVectorZ2, double& CallFuncBreakVectorX3, double& CallFuncBreakVectorY3, double& CallFuncBreakVectorZ3, double& CallFuncFMaxReturnValue, double& CallFuncFMinReturnValue, double& CallFuncFMinReturnValue1, double& CallFuncFMinReturnValue2, double& CallFuncFMaxReturnValue1, struct FVector& CallFuncMakeVectorReturnValue, double& CallFuncFMaxReturnValue2, struct FVector& CallFuncMakeVectorReturnValue1); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Athena/AthenaFunctionLibrary.AthenaFunctionLibrary_C.UnclampedLerp (Has no native function)
	static void UnclampedLerp(double& A, double& B, double& Alpha, class UObject*& WorldContext, double& ReturnValue, double& CallFuncSubtractDoubleDoubleReturnValue, double& CallFuncMultiplyDoubleDoubleReturnValue, double& CallFuncAddDoubleDoubleReturnValue); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Athena/AthenaFunctionLibrary.AthenaFunctionLibrary_C.MakeSimpleFortEffectContext (Has no native function)
	static struct FGameplayEffectContextHandle MakeSimpleFortEffectContext(class AActor*& Instigator, class AActor*& DamageSource, class UObject*& WorldContext); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Athena/AthenaFunctionLibrary.AthenaFunctionLibrary_C.SpawnLootFromTable (Has no native function)
	static void SpawnLootFromTable(struct FName& TierGroupName, int& WorldLevel, int& ForcedLootTier, struct FVector& Position, struct FVector& Direction, int& OverrideMaxStackCount, bool& bToss, bool& bRandomRotation, bool& bBlockedFromAutoPickup, int& PickupInstigatorHandle, enum EFortPickupSourceTypeFlag& SourceType, enum EFortPickupSpawnSource& Source, class AFortPlayerController*& OptionalOwnerPC, bool& bPickupOnlyRelevantToOwner, class UObject*& WorldContext, struct TArray<class AFortPickup*>& ItemPickupsSpawned, struct TArray<class AFortPickup*>& PickupsSpawned, struct FName& LootTierData, struct TArray<struct FFortItemEntry>& CallFuncPickLootDropsOutLootToDrop, bool& CallFuncPickLootDropsReturnValue, int& CallFuncArrayLengthReturnValue, int& TempintLoopCounterVariable, bool& CallFuncLessIntIntReturnValue, int& CallFuncAddIntIntReturnValue, int& TempintArrayIndexVariable, struct FFortItemEntry& CallFuncArrayGetItem, class UFortWorldItemDefinition*& K2NodeDynamicCastAsFortWorldItemDefinition, bool& K2NodeDynamicCastbSuccess, class AFortPickup*& CallFuncK2SpawnPickupInWorldReturnValue, int& CallFuncArrayAddUniqueReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Athena/AthenaFunctionLibrary.AthenaFunctionLibrary_C.RowToBool (Has no native function)
	static bool RowToBool(struct FScalableFloat& Input, double& Level, class UObject*& WorldContext); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Athena/AthenaFunctionLibrary.AthenaFunctionLibrary_C.AllOnSameTeam (Has no native function)
	static void AllOnSameTeam(class AActor*& Actor, struct TArray<class AActor*>& ActorArray, class UObject*& WorldContext, bool& Result, bool& Result, int& CallFuncArrayLengthReturnValue, int& TempintArrayIndexVariable, int& TempintLoopCounterVariable, class AActor*& CallFuncArrayGetItem, bool& CallFuncOnSameTeamReturnValue, bool& CallFuncLessIntIntReturnValue, int& CallFuncAddIntIntReturnValue); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Athena/AthenaFunctionLibrary.AthenaFunctionLibrary_C.CreateEnvironmentalKnockbackExplosion (Has no native function)
	static void CreateEnvironmentalKnockbackExplosion(struct FVector& ExplosionSourcePoint, double& ExplosionRadius, double& Intensity, double& MinKnockbackAngle, bool& Reverse, class AActor*& SpecificActor, class UObject*& WorldContext, bool& Reverse, struct FVector& VecToCurrentActor, double& MinKnockbackAngle, double& Intensity, class AActor*& CurrentActorBeingLaunched, double& Radius, struct FVector& SourcePoint, int& TempintArrayIndexVariable, bool& CallFuncIsValidReturnValue, struct TArray<class AActor*>& TempobjectVariable, double& CallFuncVSizeReturnValue, struct FVector& CallFuncNormalReturnValue, int& TempintLoopCounterVariable, struct FVector& CallFuncSelectVectorReturnValue, int& CallFuncAddIntIntReturnValue, double& CallFuncVSizeReturnValue1, bool& CallFuncGreaterDoubleDoubleReturnValue, class AFortPawn*& K2NodeDynamicCastAsFortPawn, bool& K2NodeDynamicCastbSuccess, double& CallFuncDivideDoubleDoubleReturnValue, struct FActiveGameplayEffectHandle*& CallFuncApplyGlobalEnvironmentGameplayEffectToActorReturnValue, double& CallFuncSubtractDoubleDoubleReturnValue, double& CallFuncMultiplyDoubleDoubleReturnValue, struct FVector& CallFuncGetActorUpVectorReturnValue, struct FVector& CallFuncGetActorBoundsOrigin, struct FVector& CallFuncGetActorBoundsBoxExtent, struct FVector& CallFuncProjectVectorOnToPlaneReturnValue, double& CallFuncDotVectorVectorReturnValue, struct FVector& CallFuncCrossVectorVectorReturnValue, double& CallFuncDegAcosReturnValue, struct FVector& CallFuncRotateAngleAxisReturnValue, bool& CallFuncLessDoubleDoubleReturnValue, double& CallFuncDotVectorVectorReturnValue1, struct FVector& CallFuncNegateVectorReturnValue, struct FVector& CallFuncRotateAngleAxisReturnValue1, double& CallFuncDotVectorVectorReturnValue2, bool& CallFuncGreaterDoubleDoubleReturnValue1, struct FVector& CallFuncSubtractVectorVectorReturnValue, struct FVector& CallFuncSelectVectorReturnValue1, struct FVector& CallFuncSelectVectorReturnValue2, struct TArray<struct TEnumAsByte<EObjectTypeQuery>>& K2NodeMakeArrayArray, struct FVector& CallFuncSelectVectorReturnValue3, struct TArray<class AActor*>& CallFuncSphereOverlapActorsOutActors, bool& CallFuncSphereOverlapActorsReturnValue, struct FVector& CallFuncMultiplyVectorFloatReturnValue, class AActor*& CallFuncArrayGetItem, int& CallFuncArrayLengthReturnValue, bool& CallFuncLessIntIntReturnValue, float& CallFuncRotateAngleAxisAngleDegImplicitCast, float& CallFuncRotateAngleAxisAngleDegImplicitCast1, float& CallFuncSphereOverlapActorsSphereRadiusImplicitCast); // (Static | Public | HasDefaults | BlueprintCallable | BlueprintEvent)
};

