// BlueprintGeneratedClass /Game/Athena/Items/QuestInteractables/AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C
// Size: 0x28
class UAthenaQuestFunctionLibrary_C : public UBlueprintFunctionLibrary
{

	/* Functions */

	// Function /Game/Athena/Items/QuestInteractables/AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C.Athena_CheckActorHasTags (Has no native function)
	static void AthenaCheckActorHasTags(class AActor*& TargetActor, struct FGameplayTagContainer& TagsToCheck, bool& OnlyExactMatch, class UObject*& WorldContext, bool& bDidActorHaveTags, struct FGameplayTagContainer& TagsWeWant, bool& bOnlyExactMatch, struct TScriptInterface<class IGameplayTagAssetInterface>& K2NodeDynamicCastAsGameplayTagAssetInterface, bool& K2NodeDynamicCastbSuccess, bool& CallFuncDoesImplementInterfaceReturnValue, struct FGameplayTagContainer& CallFuncGetOwnedGameplayTagsTagContainer, bool& CallFuncIsValidReturnValue, struct FGameplayTagContainer& TempstructVariable, bool& CallFuncHasAllTagsReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Athena/Items/QuestInteractables/AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C.Athena_PartyAssistCheck (Has no native function)
	static void AthenaPartyAssistCheck(class AFortPlayerController*& PlayerController, struct FName& ObjectiveBackendName, class UObject*& WorldContext, bool& bIsAssistingObjective, bool& bIsValidPlayerController, bool& CallFuncIsValidReturnValue); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Athena/Items/QuestInteractables/AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C.Athena_PlayQuestRewardFeedback (Has no native function)
	static void AthenaPlayQuestRewardFeedback(bool& PlayFXonPlayer, class USoundBase*& SuccessSound, class UParticleSystem*& SuccessParticles, class UNiagaraSystem*& SuccessNiagara, class UForceFeedbackEffect*& SuccessShake, class AActor*& QuestActor, class AFortPlayerPawn*& PlayerPawn, struct FTransform& EffectTransform, class UObject*& WorldContext, struct FVector& CallFuncBreakTransformLocation, struct FRotator& CallFuncBreakTransformRotation, struct FVector& CallFuncBreakTransformScale, class APlayerController*& CallFuncGetLocalViewingPlayerControllerReturnValue, class UAudioComponent*& CallFuncSpawnSoundAttachedReturnValue, struct FVector& CallFuncK2GetActorLocationReturnValue, class UNiagaraComponent*& CallFuncSpawnSystemAttachedReturnValue, struct FVector& CallFuncAddVectorVectorReturnValue, class UParticleSystemComponent*& CallFuncSpawnEmitterAttachedReturnValue, class UNiagaraComponent*& CallFuncSpawnSystemAtLocationReturnValue, class UParticleSystemComponent*& CallFuncSpawnEmitterAtLocationReturnValue, bool& CallFuncIsValidReturnValue, bool& CallFuncIsValidReturnValue1, bool& CallFuncIsValidReturnValue2, bool& CallFuncIsValidReturnValue3); // (Static | Public | BlueprintCallable | BlueprintEvent)

	// Function /Game/Athena/Items/QuestInteractables/AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C.Athena_IsCreativeOrPlaygroundPlaylist (Has no native function)
	static bool AthenaIsCreativeOrPlaygroundPlaylist(struct FGameplayTagContainer& TagContainer, class UObject*& WorldContext); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Athena/Items/QuestInteractables/AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C.Athena_CheckCreativeMode (Has no native function)
	static void AthenaCheckCreativeMode(class AGameStateBase*& InGameState, class UObject*& WorldContext, bool& CanCompleteQuest, class AFortGameStateAthena*& K2NodeDynamicCastAsFortGameStateAthena, bool& K2NodeDynamicCastbSuccess, struct FGameplayTagContainer& CallFuncGetAthenaPlaylistContextTagsReturnValue, bool& CallFuncHasTagReturnValue, bool& CallFuncHasTagReturnValue1, bool& CallFuncBooleanORReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Athena/Items/QuestInteractables/AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C.Athena_QuestObjectiveCounter (Has no native function)
	static void AthenaQuestObjectiveCounter(class AFortPlayerController*& FortPlayerControllerAthena, class UFortQuestItemDefinition*& ObjectiveItem, struct FDataTableRowHandle& ObjectiveStat, class UObject*& WorldContext, int& QuestCountAchieved, int& QuestCountRequired, bool& CountSuccessfullyReturned, int& LocalRequiredCount, int& LocalAchievedCount, bool& SuccessfullyFoundStage, bool& CallFuncIsValidReturnValue, class UFortQuestManager*& CallFuncGetQuestManagerReturnValue, class UFortQuestItem*& CallFuncGetQuestWithDefinitionReturnValue, class UFortQuestObjectiveInfo*& CallFuncGetObjectiveInfoReturnValue, bool& CallFuncIsValidReturnValue1, bool& CallFuncIsValidReturnValue2); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Athena/Items/QuestInteractables/AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C.Athena_GiveQuestUpdateToPlayers (Has no native function)
	static void AthenaGiveQuestUpdateToPlayers(class UFortQuestItemDefinition*& InQuestItemRef, struct FName& ObjectiveBackendName, struct FDataTableRowHandle& ObjectiveStatEvent, struct TArray<class AFortPlayerController*>& PlayerControllersForUpdate, class UObject*& WorldContext, int& TempintArrayIndexVariable, int& CallFuncArrayLengthReturnValue, class AFortPlayerController*& CallFuncArrayGetItem, bool& CallFuncIsValidReturnValue, class UFortQuestManager*& CallFuncGetQuestManagerReturnValue, class UFortQuestItem*& CallFuncGetQuestWithDefinitionReturnValue, bool& CallFuncIsValidReturnValue1, bool& CallFuncIsValidReturnValue2, bool& CallFuncHasCompletedObjectiveWithNameReturnValue, int& TempintLoopCounterVariable, bool& CallFuncLessIntIntReturnValue, int& CallFuncAddIntIntReturnValue); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Athena/Items/QuestInteractables/AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C.Athena_CheckQuestAndObjectiveCompletionMP (Has no native function)
	static void AthenaCheckQuestAndObjectiveCompletionMP(struct TArray<class AFortPlayerController*>& InPlayerControlle, class UFortQuestItemDefinition*& InQuestItemRef, struct FName& ObjectiveBackendName, class UObject*& WorldContext, bool& QuestIsValid, bool& QuestCompleted, bool& ObjectiveCompleted, bool& ResultObjectiveCompleted, bool& ResultQuestCompleted, bool& ResultQuestIsValid, int& CallFuncArrayLengthReturnValue, int& TempintArrayIndexVariable, int& TempintLoopCounterVariable, class AFortPlayerController*& CallFuncArrayGetItem, bool& CallFuncLessIntIntReturnValue, int& CallFuncAddIntIntReturnValue, bool& CallFuncAthenaCheckQuestAndObjectiveCompletionQuestIsValid, bool& CallFuncAthenaCheckQuestAndObjectiveCompletionQuestCompleted, bool& CallFuncAthenaCheckQuestAndObjectiveCompletionObjectiveCompleted, bool& CallFuncBooleanANDReturnValue, bool& CallFuncBooleanANDReturnValue1, bool& CallFuncBooleanANDReturnValue2); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Athena/Items/QuestInteractables/AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C.Athena_CheckQuestAndObjectiveCompletion (Has no native function)
	static void AthenaCheckQuestAndObjectiveCompletion(class AFortPlayerController*& InPlayerControlle, class UFortQuestItemDefinition*& InQuestItemRef, struct FName& ObjectiveBackendName, class UObject*& WorldContext, bool& QuestIsValid, bool& QuestCompleted, bool& ObjectiveCompleted, bool& CallFuncIsValidReturnValue, bool& CallFuncIsValidReturnValue1, class UFortQuestManager*& CallFuncGetQuestManagerReturnValue, class UFortQuestItem*& CallFuncGetQuestWithDefinitionReturnValue, bool& CallFuncHasCompletedObjectiveWithNameReturnValue, bool& CallFuncHasCompletedQuestReturnValue, bool& CallFuncIsValidReturnValue2); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Athena/Items/QuestInteractables/AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C.Athena_HasPlayerCompletedQuest (Has no native function)
	static void AthenaHasPlayerCompletedQuest(class AFortPlayerController*& InPlayerControlle, class UFortQuestItemDefinition*& InQuestItemRef, class UObject*& WorldContext, bool& HasQuest, bool& QuestCompleted, bool& CallFuncIsValidReturnValue, bool& CallFuncIsValidReturnValue1, class UFortQuestManager*& CallFuncGetQuestManagerReturnValue, class UFortQuestItem*& CallFuncGetQuestWithDefinitionReturnValue, bool& CallFuncHasCompletedQuestReturnValue, bool& CallFuncIsValidReturnValue2); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Athena/Items/QuestInteractables/AthenaQuestFunctionLibrary.AthenaQuestFunctionLibrary_C.Athena_HasQuest (Has no native function)
	static void AthenaHasQuest(class AFortPlayerController*& InPlayerControlle, class UFortQuestItemDefinition*& InQuestItemRef, class UObject*& WorldContext, bool& PlayerHasQuest, bool& CallFuncIsValidReturnValue, bool& CallFuncIsValidReturnValue1, class UFortQuestManager*& CallFuncGetQuestManagerReturnValue, class UFortQuestItem*& CallFuncGetQuestWithDefinitionReturnValue, bool& CallFuncIsValidReturnValue2); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)
};

