// BlueprintGeneratedClass /Game/ArtTools/Tech_Art/Libraries/Macros/B_TechArt_GlobalLibrary.B_TechArt_GlobalLibrary_C
// Size: 0x28
class UB_TechArt_GlobalLibrary_C : public UBlueprintFunctionLibrary
{

	/* Functions */

	// Function /Game/ArtTools/Tech_Art/Libraries/Macros/B_TechArt_GlobalLibrary.B_TechArt_GlobalLibrary_C.GetDynamicMaterialInstance (Has no native function)
	static void GetDynamicMaterialInstance(class UMeshComponent*& MeshComponent, int& MaterialIndex, class UObject*& WorldContext, class UMaterialInstanceDynamic*& MaterialInstanceDynamic, class UMaterialInterface*& CallFuncGetMaterialReturnValue, class UMaterialInstanceDynamic*& K2NodeDynamicCastAsMaterialInstanceDynamic, bool& K2NodeDynamicCastbSuccess, class UMaterialInstanceDynamic*& CallFuncCreateDynamicMaterialInstanceReturnValue); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/ArtTools/Tech_Art/Libraries/Macros/B_TechArt_GlobalLibrary.B_TechArt_GlobalLibrary_C.AreBoundsOverlapping? (Has no native function)
	static void AreBoundsOverlapping(struct FBox& BoundsA, struct FBox& BoundsB, class UObject*& WorldContext, bool& BoundsOverlap, double& CallFuncBreakVectorX, double& CallFuncBreakVectorY, double& CallFuncBreakVectorZ, double& CallFuncBreakVectorX1, double& CallFuncBreakVectorY1, double& CallFuncBreakVectorZ1, double& CallFuncBreakVectorX2, double& CallFuncBreakVectorY2, double& CallFuncBreakVectorZ2, double& CallFuncBreakVectorX3, double& CallFuncBreakVectorY3, double& CallFuncBreakVectorZ3, bool& CallFuncGreaterDoubleDoubleReturnValue, bool& CallFuncGreaterDoubleDoubleReturnValue1, bool& CallFuncGreaterDoubleDoubleReturnValue2, bool& CallFuncBooleanANDReturnValue, bool& CallFuncGreaterDoubleDoubleReturnValue3, bool& CallFuncGreaterDoubleDoubleReturnValue4, bool& CallFuncGreaterDoubleDoubleReturnValue5, bool& CallFuncBooleanANDReturnValue1, bool& CallFuncBooleanANDReturnValue2, bool& CallFuncBooleanANDReturnValue3, bool& CallFuncBooleanANDReturnValue4); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/ArtTools/Tech_Art/Libraries/Macros/B_TechArt_GlobalLibrary.B_TechArt_GlobalLibrary_C.AddActorTag (Has no native function)
	static void AddActorTag(class AActor*& Actor, struct FName& tag, class UObject*& WorldContext, struct TArray<struct FName>& ExistingActorTags, int& CallFuncArrayAddUniqueReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/ArtTools/Tech_Art/Libraries/Macros/B_TechArt_GlobalLibrary.B_TechArt_GlobalLibrary_C.HoudiniInstanceHISMBuilder (Has no native function)
	static void HoudiniInstanceHISMBuilder(class UInstancedStaticMeshComponent*& InstancedStaticMeshComponent, class UDataTable*& InstanceDataTable, double& InstancesCountToImport, bool& RandomScale, double& RandomScaleMin, double& RandomScaleMax, bool& RandomRotationZ, double& RandomRotationZMin, double& RandomRotationZMax, bool& UseWorldSpacePositions, class UObject*& WorldContext, int& TempintLoopCounterVariable, bool& CallFuncIsValidReturnValue, int& CallFuncAddIntIntReturnValue, int& TempintArrayIndexVariable, double& CallFuncRandomFloatInRangeReturnValue, struct FRotator& CallFuncMakeRotatorReturnValue, struct FRotator& CallFuncSelectRotatorReturnValue, double& CallFuncRandomFloatInRangeReturnValue1, struct FVector& CallFuncMakeVectorReturnValue, double& CallFuncDivideDoubleDoubleReturnValue, struct TArray<struct FName>& CallFuncGetDataTableRowNamesOutRowNames, int& CallFuncFTruncReturnValue, struct FName& CallFuncArrayGetItem, int& CallFuncPercentIntIntReturnValue, struct FHoudiniInstanceDataLayout& CallFuncGetDataTableRowFromNameOutRow, bool& CallFuncGetDataTableRowFromNameReturnValue, bool& CallFuncEqualEqualIntIntReturnValue, int& CallFuncArrayLengthReturnValue, struct FVector& CallFuncMakeVectorReturnValue1, bool& CallFuncLessIntIntReturnValue, struct FVector& CallFuncSelectVectorReturnValue, struct FVector& CallFuncMakeVectorReturnValue2, struct FTransform& CallFuncMakeTransformReturnValue, int& CallFuncAddInstanceReturnValue, float& CallFuncMakeRotatorYawImplicitCast, double& CallFuncMakeVectorXImplicitCast, double& CallFuncMakeVectorZImplicitCast, double& CallFuncMakeVectorYImplicitCast, double& CallFuncMakeVectorXImplicitCast1, double& CallFuncMakeVectorYImplicitCast1, double& CallFuncMakeVectorZImplicitCast1); // (Static | Public | HasDefaults | BlueprintCallable | BlueprintEvent)
};

