// BlueprintGeneratedClass /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C
// Size: 0x28
class UCreative_CommonDeviceFunctionLibrary_C : public UBlueprintFunctionLibrary
{

	/* Functions */

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.IsInEditor (Has no native function)
	static void IsInEditor(class UObject*& WorldContext, bool& TRUE, bool& CallFuncInEditorReturnValue); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.Get Team Color For Team Option (Has no native function)
	static void GetTeamColorForTeamOption(class AActor*& ContextActor, struct FCreativeTeamOption*& TeamOption, class UObject*& WorldContext, struct FLinearColor& BaseColor, struct FLinearColor& LightColor, struct FLinearColor& BoldColor, int& ColorIndex, struct TArray<struct FLinearColor>& TempstructVariable, struct TEnumAsByte<EFortTeam>& CallFuncConvertToTeamReturnValue, bool& CallFuncEqualEqualByteByteReturnValue, bool& CallFuncIsValidReturnValue, int& CallFuncSelectIntReturnValue, class AFortMinigame*& CallFuncGetMinigameReturnValue, struct TArray<struct FLinearColor>& TempstructVariable1, bool& CallFuncIsValidReturnValue1, int& CallFuncGetTeamColorIndexReturnValue, struct TArray<struct FLinearColor>& TempstructVariable2, int& CallFuncArrayLengthReturnValue, int& CallFuncPercentIntIntReturnValue, int& CallFuncMaxReturnValue, struct FLinearColor& CallFuncArrayGetItem, struct FLinearColor& CallFuncArrayGetItem1, struct FLinearColor& CallFuncArrayGetItem2); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.Apply Vent Recently Launched Tag or Abort Launch (Has no native function)
	static void ApplyVentRecentlyLaunchedTagorAbortLaunch(class AActor*& ActorToLaunch, class AActor*& VentActor, class UObject*& WorldContext, bool& ShouldLaunch, bool& TempboolVariable, class UAbilitySystemComponent*& CallFuncGetAbilitySystemComponentReturnValue, bool& CallFuncNotPreBoolReturnValue, struct FVector& CallFuncK2GetActorLocationReturnValue, bool& CallFuncIsValidReturnValue, struct TScriptInterface<class IGameplayTagAssetInterface>& K2NodeDynamicCastAsGameplayTagAssetInterface, bool& K2NodeDynamicCastbSuccess, bool& CallFuncHasMatchingGameplayTagReturnValue, bool& CallFuncIsValidReturnValue1, struct TArray<class UClass*>& K2NodeMakeArrayArray); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.Simple Apply Gameplay Effect to Actor (Has no native function)
	static void SimpleApplyGameplayEffecttoActor(class UClass*& GameplayEffect, class AActor*& Actor, class UObject*& WorldContext, class UAbilitySystemComponent*& PlayerAbilitySystemComp, bool& CallFuncIsValidClassReturnValue, bool& CallFuncIsValidReturnValue, struct FVector& CallFuncK2GetActorLocationReturnValue, struct TArray<class UClass*>& K2NodeMakeArrayArray); // (Static | Public | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.Give Ammo To Inventory Owner (Has no native function)
	static void GiveAmmoToInventoryOwner(struct TScriptInterface<class IFortInventoryOwnerInterface>& InventoryOwner, class UFortWorldItemDefinition*& WorldItemDefinition, int& PickupInstigatorHandle, struct TMap<struct TWeakObjectPtr<class UFortWorldItemDefinition>, int>& AmmoToGiveItemDefinitionMap, int& DefaultAmmoToGive, class UObject*& WorldContext, int& NumAmmoToGive, class AFortPlayerController*& PlayerController, class UFortWorldItemDefinition*& TargetAmmoDef, class UFortWeaponItemDefinition*& K2NodeDynamicCastAsFortWeaponItemDefinition, bool& K2NodeDynamicCastbSuccess, bool& CallFuncIsValidReturnValue, class UClass*& CallFuncGetReloadAbilityReturnValue, bool& CallFuncIsValidClassReturnValue, class AFortPlayerController*& K2NodeDynamicCastAsFortPlayerController, bool& K2NodeDynamicCastbSuccess1, class UFortWorldItemDefinition*& CallFuncGetAmmoWorldItemDefinitionBPReturnValue, struct TWeakObjectPtr<class UFortWorldItemDefinition>& CallFuncConvObjectToSoftObjectReferenceReturnValue, bool& TempboolVariable, int& CallFuncMapFindValue, bool& CallFuncMapFindReturnValue, int& K2NodeSelectDefault, bool& CallFuncGreaterIntIntReturnValue, class UFortWorldItem*& CallFuncGiveItemToInventoryOwnerReturnValue, int& CallFuncK2GetItemQuantityOnPlayerReturnValue, bool& CallFuncNotEqualObjectObjectReturnValue, bool& CallFuncEqualEqualIntIntReturnValue, bool& CallFuncIsValidReturnValue1, bool& CallFuncBooleanANDReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.MatchesTagReturnMatch (Has no native function)
	static void MatchesTagReturnMatch(struct FGameplayTagContainer& TagContainer, struct FGameplayTag& tag, bool& ExactMatch, class UObject*& WorldContext, bool& TagFound, struct FGameplayTag& FirstMatchingTag, struct FGameplayTag& FoundTag, int& TempintArrayIndexVariable, struct TArray<struct FGameplayTag>& CallFuncBreakGameplayTagContainerGameplayTags, struct FGameplayTag& CallFuncArrayGetItem, int& CallFuncArrayLengthReturnValue, bool& CallFuncMatchesTagReturnValue, int& TempintLoopCounterVariable, bool& CallFuncLessIntIntReturnValue, int& CallFuncAddIntIntReturnValue, bool& TempboolTrueifbreakwashitVariable, bool& CallFuncIsGameplayTagValidReturnValue, bool& CallFuncNotPreBoolReturnValue, bool& CallFuncBooleanANDReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.Get PlayerState from NetID (Has no native function)
	static void GetPlayerStatefromNetID(struct FUniqueNetIdRepl& UniqueNetId, class UObject*& WorldContext, class AFortPlayerState*& FortPlayerState, class AGameStateBase*& CallFuncGetGameStateReturnValue, int& TempintArrayIndexVariable, bool& CallFuncIsValidReturnValue, int& TempintLoopCounterVariable, class APlayerState*& CallFuncArrayGetItem, class AFortPlayerState*& K2NodeDynamicCastAsFortPlayerState, bool& K2NodeDynamicCastbSuccess, int& CallFuncAddIntIntReturnValue, struct FUniqueNetIdRepl& CallFuncGetPlayerUniqueNetIDReturnValue, bool& CallFuncEqualEqualUniqueNetIdReplUniqueNetIdReplReturnValue, int& CallFuncArrayLengthReturnValue, bool& CallFuncLessIntIntReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.Is Matching Channel ID (Has no native function)
	static void IsMatchingChannelID(class UFortGameplayMessageComponentBase*& A, class UFortGameplayMessageComponentBase*& B, class UObject*& WorldContext, bool& Matches, struct FGameplayTagContainer& CallFuncGetChannelIdReturnValue, struct FGameplayTagContainer& CallFuncGetChannelIdReturnValue1, bool& CallFuncEqualEqualGameplayTagContainerReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.Bool to Bool with Unset (Has no native function)
	static void BooltoBoolwithUnset(bool& Input, class UObject*& WorldContext, struct TEnumAsByte<EBoolWithUnset>& Output, bool& TempboolVariable, struct TEnumAsByte<EBoolWithUnset>& TempbyteVariable, struct TEnumAsByte<EBoolWithUnset>& TempbyteVariable1, struct TEnumAsByte<EBoolWithUnset>& K2NodeSelectDefault); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.Reattach or Create MID (Has no native function)
	static void ReattachorCreateMID(class UPrimitiveComponent*& Mesh, class UMaterialInstanceDynamic*& TargetMID, int& MatId, class UObject*& WorldContext, struct FString& CallFuncConvIntToStringReturnValue, bool& CallFuncIsValidReturnValue, struct FString& CallFuncGetDisplayNameReturnValue, struct FVector& CallFuncK2GetComponentLocationReturnValue, class AActor*& CallFuncGetOwnerReturnValue, struct FString& CallFuncConvVectorToStringReturnValue, struct FString& CallFuncGetDisplayNameReturnValue1, struct FString& CallFuncConcatStrStrReturnValue, struct FString& CallFuncConcatStrStrReturnValue1, struct FString& CallFuncConcatStrStrReturnValue2, struct FName& CallFuncConvStringToNameReturnValue, class UMaterialInstanceDynamic*& CallFuncCreateDynamicMaterialInstanceReturnValue, class UMaterialInterface*& CallFuncGetMaterialReturnValue, bool& CallFuncNotEqualObjectObjectReturnValue); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.Wrapping Modulo (Has no native function)
	static void WrappingModulo(int& A, int& B, class UObject*& WorldContext, int& Out, int& Result, int& CallFuncPercentIntIntReturnValue, int& CallFuncAddIntIntReturnValue, bool& CallFuncLessIntIntReturnValue); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.Animate Float Curve (Has no native function)
	static void AnimateFloatCurve(double& DeltaTime, double& CurrentTime, class UCurveFloat*& FCurve, double& AnimationTime, bool& InvertTime, class UObject*& WorldContext, double& Value, bool& bIsComplete, double& EndTime, double& CurveFloatResult, double& TimeAlpha, bool& CallFuncIsValidReturnValue, bool& TempboolVariable, double& CallFuncSubtractDoubleDoubleReturnValue, double& CallFuncAddDoubleDoubleReturnValue, double& CallFuncDivideDoubleDoubleReturnValue, double& K2NodeSelectDefault, double& CallFuncFClampReturnValue, float& CallFuncGetFloatValueReturnValue, double& TemprealVariable, bool& TempboolVariable1, double& K2NodeSelectDefault1, bool& CallFuncEqualEqualDoubleDoubleReturnValue, float& CallFuncGetFloatValueInTimeImplicitCast, double& K2NodeVariableSetCurveFloatResultImplicitCast); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.TeamToIndex (Has no native function)
	static void TeamToIndex(unsigned char& Team, class UObject*& WorldContext, int& Index, unsigned char& CallFuncMakeLiteralByteReturnValue, unsigned char& CallFuncSubtractByteByteReturnValue, int& CallFuncConvByteToIntReturnValue); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.IndexToTeam (Has no native function)
	static void IndexToTeam(int& Index, class UObject*& WorldContext, unsigned char& Team, unsigned char& CallFuncMakeLiteralByteReturnValue, unsigned char& CallFuncConvIntToByteReturnValue, unsigned char& CallFuncAddByteByteReturnValue); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.IsLogicInPlayMode (Has no native function)
	static void IsLogicInPlayMode(class UFortMinigameLogicComponent*& Logic, class UObject*& WorldContext, bool& PlayMode, bool& CallFuncIsValidReturnValue, bool& CallFuncIsValidReturnValue1, bool& CallFuncIsInPlayModeReturnValue); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.Get Dynamic Team Color (Has no native function)
	static void GetDynamicTeamColor(class AActor*& Actor, class AFortMinigame*& Minigame, struct TEnumAsByte<ECreativeColorSetType>& ColorType, class UObject*& WorldContext, int& ArrayIndex, struct TArray<struct FGameplayTag>& GameplayTags, struct TArray<struct FGameplayTag>& GameplayColorTags, struct TEnumAsByte<ECreativeTeamColor>& TempbyteVariable, class AFortPlayerController*& CallFuncGetFirstLocalFortPlayerControllerReturnValue, bool& K2NodeSwitchEnumCmpSuccess, struct TEnumAsByte<ECreativeTeamColor>& TempbyteVariable1, struct TEnumAsByte<ECreativeTeamColor>& TempbyteVariable2, unsigned char& CallFuncMakeLiteralByteReturnValue, struct TArray<struct FGameplayTag>& K2NodeMakeArrayArray, struct TEnumAsByte<EFortTeamAffiliation>& TempbyteVariable3, struct TEnumAsByte<EFortTeamAffiliation>& CallFuncGetTeamAffiliationReturnValue, unsigned char& CallFuncGetActorPvPTeamIndexTeamIndex, bool& CallFuncGetActorPvPTeamIndexReturnValue, unsigned char& CallFuncAddByteByteReturnValue, struct TEnumAsByte<ECreativeTeamColor>& K2NodeSelectDefault, int& CallFuncConvByteToIntReturnValue, int& CallFuncGetTeamColorIndexReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.Get Team Color Index from Tag (Has no native function)
	static void GetTeamColorIndexfromTag(class AActor*& ActorwithTag, class AFortMinigame*& Minigame, class UObject*& WorldContext, int& ArrayIndex, struct TEnumAsByte<ECreativeColorSetType>& ColorTypeOut, struct FGameplayTag& CheckTag, struct TArray<struct FGameplayTag>& GameplayTags, struct TArray<struct FGameplayTag>& GameplayColorTags, struct FGameplayTagContainer& TempstructVariable, struct TArray<struct FGameplayTag>& K2NodeMakeArrayArray, struct TArray<struct FGameplayTag>& CallFuncBreakGameplayTagContainerGameplayTags, int& TempintArrayIndexVariable, int& TempintLoopCounterVariable, struct FGameplayTag& CallFuncArrayGetItem, int& CallFuncSubtractIntIntReturnValue, bool& CallFuncGreaterEqualIntIntReturnValue, int& CallFuncArrayLengthReturnValue, int& CallFuncSubtractIntIntReturnValue1, int& CallFuncMaxReturnValue, int& CallFuncGetDynamicTeamColorArrayIndex, int& CallFuncGetDynamicTeamColorArrayIndex1, bool& CallFuncEqualEqualGameplayTagReturnValue, bool& CallFuncEqualEqualGameplayTagReturnValue1, int& CallFuncArrayFindReturnValue, bool& CallFuncMatchesTagReturnValue, bool& CallFuncNotEqualIntIntReturnValue, struct TScriptInterface<class IGameplayTagAssetInterface>& K2NodeDynamicCastAsGameplayTagAssetInterface, bool& K2NodeDynamicCastbSuccess, struct FGameplayTagContainer& CallFuncGetOwnedGameplayTagsTagContainer); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.Get Team Color Index or Team Index (Has no native function)
	static int GetTeamColorIndexorTeamIndex(class UFortMinigameLogicComponent*& MinigameLogic, int& TeamIndex, class UObject*& WorldContext); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.IsLocalPawn (Has no native function)
	static void IsLocalPawn(class AActor*& Actor, class UObject*& WorldContext, bool& IsLocalPawn, bool& CallFuncIsDedicatedServerReturnValue, struct TArray<class AFortPlayerController*>& CallFuncGetLocalFortPlayerControllersReturnValue, int& CallFuncArrayLengthReturnValue, int& TempintArrayIndexVariable, int& TempintLoopCounterVariable, class AFortPlayerController*& CallFuncArrayGetItem, class APawn*& CallFuncK2GetPawnReturnValue, bool& CallFuncLessIntIntReturnValue, bool& CallFuncIsValidReturnValue, bool& CallFuncEqualEqualObjectObjectReturnValue, int& CallFuncAddIntIntReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.IsInPlayMode (Has no native function)
	static void IsInPlayMode(class AActor*& Actor, class UObject*& WorldContext, bool& PlayMode, class AFortMinigame*& Minigame, class AFortMinigame*& CallFuncGetMinigameReturnValue, bool& CallFuncIsValidReturnValue, bool& CallFuncIsInPlayModeReturnValue, bool& CallFuncIsValidReturnValue1); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.Get Driver or Pawn Controller (Has no native function)
	static void GetDriverorPawnController(class AActor*& ActorToCheck, class UObject*& WorldContext, bool& ValidController, class AController*& Controller, struct FGameplayTagContainer& DeviceDontTriggerTags, class AController*& Controller, class AFortPlayerPawn*& TempobjectVariable, class AController*& K2NodeDynamicCastAsController, bool& K2NodeDynamicCastbSuccess, bool& CallFuncIsValidReturnValue, class AController*& CallFuncGetControllerReturnValue, class AFortPlayerController*& CallFuncGetFortPlayerControllerFromActorReturnValue, bool& CallFuncIsValidReturnValue1, class UAbilitySystemComponent*& CallFuncGetAbilitySystemComponentReturnValue, bool& CallFuncIsValidReturnValue2, struct TScriptInterface<class IFortVehicleInterface>& K2NodeDynamicCastAsFortVehicleInterface, bool& K2NodeDynamicCastbSuccess1, class AFortPlayerPawn*& CallFuncGetDriverReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.GetMID_FromMaterial (Has no native function)
	static void GetMIDFromMaterial(class UPrimitiveComponent*& Target, int& Index, class UMaterialInterface*& SourceMaterial, class UObject*& WorldContext, class UMaterialInstanceDynamic*& Mid, class AActor*& CallFuncGetOwnerReturnValue, class UMaterialInterface*& CallFuncGetMaterialReturnValue, struct FString& CallFuncGetDisplayNameReturnValue, class UMaterialInstanceDynamic*& K2NodeDynamicCastAsMaterialInstanceDynamic, bool& K2NodeDynamicCastbSuccess, struct FString& CallFuncGetDisplayNameReturnValue1, class UMaterial*& CallFuncGetBaseMaterialReturnValue, struct FVector& CallFuncK2GetComponentLocationReturnValue, bool& CallFuncEqualEqualObjectObjectReturnValue, struct FString& CallFuncConvVectorToStringReturnValue, struct FString& CallFuncConcatStrStrReturnValue, struct FString& CallFuncConcatStrStrReturnValue1, struct FName& CallFuncConvStringToNameReturnValue, class UMaterialInstanceDynamic*& CallFuncCreateDynamicMaterialInstanceReturnValue); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.Refresh Team Change Binding (Has no native function)
	static void RefreshTeamChangeBinding(class UFortMinigameLogicComponent*& MinigameLogic, bool& Unbind, struct FDelegate& Event, class UObject*& WorldContext, bool& CallFuncIsValidReturnValue, bool& CallFuncIsDedicatedServerReturnValue, bool& CallFuncIsValidReturnValue1); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.Update Team Color (Has no native function)
	static void UpdateTeamColor(class UFortMinigameLogicComponent*& MinigameLogic, class UPrimitiveComponent*& Mesh, int& Team, class UObject*& WorldContext, class UMaterialInstanceDynamic*& CallFuncGetMIDMID, int& CallFuncGetTeamColorIndexorTeamIndexReturnValue, float& CallFuncConvIntToFloatReturnValue); // (Static | Public | BlueprintCallable | BlueprintEvent)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.GetMID (Has no native function)
	static void GetMID(class UPrimitiveComponent*& Target, class UObject*& WorldContext, class UMaterialInstanceDynamic*& Mid, struct FString& CallFuncGetDisplayNameReturnValue, struct FVector& CallFuncK2GetComponentLocationReturnValue, class AActor*& CallFuncGetOwnerReturnValue, struct FString& CallFuncConvVectorToStringReturnValue, struct FString& CallFuncGetDisplayNameReturnValue1, bool& CallFuncIsValidReturnValue, struct FString& CallFuncConcatStrStrReturnValue, struct FString& CallFuncConcatStrStrReturnValue1, class UMaterialInterface*& CallFuncGetMaterialReturnValue, struct FName& CallFuncConvStringToNameReturnValue, bool& CallFuncIsValidReturnValue1, class UMaterialInstanceDynamic*& CallFuncCreateDynamicMaterialInstanceReturnValue, class UMaterialInstanceDynamic*& K2NodeDynamicCastAsMaterialInstanceDynamic, bool& K2NodeDynamicCastbSuccess); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.ActorCanTrigger (Has no native function)
	static void ActorCanTrigger(class AActor*& ActorToCheck, class UPrimitiveComponent*& OverlapComponent, class UObject*& WorldContext, bool& CanTrigger, class AController*& Controller, bool& localCanTrigger, struct FGameplayTagContainer& DeviceDontTriggerTags, class AController*& localcontroller, class AFortPlayerPawn*& TempobjectVariable, bool& CallFuncIsValidReturnValue, class AController*& CallFuncGetControllerReturnValue, class AFortPlayerController*& CallFuncGetFortPlayerControllerFromActorReturnValue, class UAbilitySystemComponent*& CallFuncGetAbilitySystemComponentReturnValue, struct TScriptInterface<class IGameplayTagAssetInterface>& CallFuncHasAllMatchingGameplayTagsTagContainerInterfaceCastInput, bool& CallFuncHasAllMatchingGameplayTagsReturnValue, bool& CallFuncIsValidReturnValue1, bool& CallFuncNotPreBoolReturnValue, bool& CallFuncIsValidReturnValue2, struct TScriptInterface<class IFortVehicleInterface>& K2NodeDynamicCastAsFortVehicleInterface, bool& K2NodeDynamicCastbSuccess, class AFortPlayerPawn*& CallFuncGetDriverReturnValue, struct TEnumAsByte<ECollisionChannel>& CallFuncGetCollisionObjectTypeReturnValue, bool& CallFuncEqualEqualByteByteReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.IsActivatedOnPhase (Has no native function)
	static void IsActivatedOnPhase(enum EFortMinigameState& State, int& PhaseIndex, class AActor*& Actor, class UObject*& WorldContext, bool& Enabled, bool& CallFuncEqualEqualByteByteReturnValue, bool& CallFuncEqualEqualIntIntReturnValue, bool& CallFuncBooleanANDReturnValue, bool& CallFuncIsInPlayModePlayMode, unsigned char& CallFuncMakeLiteralByteReturnValue, bool& CallFuncEqualEqualByteByteReturnValue1, bool& CallFuncEqualEqualByteByteReturnValue2, bool& CallFuncEqualEqualIntIntReturnValue1, bool& CallFuncBooleanANDReturnValue1, bool& CallFuncEqualEqualIntIntReturnValue2, bool& CallFuncBooleanANDReturnValue2, bool& CallFuncBooleanANDReturnValue3, bool& CallFuncBooleanORReturnValue, bool& CallFuncBooleanORReturnValue1); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.IsEnabledPhaseMatch (Has no native function)
	static void IsEnabledPhaseMatch(enum EFortMinigameState& State, int& PhaseIndex, class AActor*& Actor, class UObject*& WorldContext, bool& Enabled, unsigned char& CallFuncMakeLiteralByteReturnValue, bool& CallFuncInEditorReturnValue, bool& CallFuncIsInPlayModePlayMode, unsigned char& CallFuncMakeLiteralByteReturnValue1, bool& CallFuncNotPreBoolReturnValue, bool& CallFuncEqualEqualByteByteReturnValue, bool& CallFuncEqualEqualIntIntReturnValue, bool& CallFuncBooleanANDReturnValue, bool& CallFuncIsInPlayModePlayMode1, bool& CallFuncBooleanANDReturnValue1, bool& CallFuncBooleanANDReturnValue2, bool& CallFuncBooleanORReturnValue, bool& CallFuncEqualEqualIntIntReturnValue1, bool& CallFuncLessByteByteReturnValue, bool& CallFuncEqualEqualByteByteReturnValue1, unsigned char& CallFuncMakeLiteralByteReturnValue2, bool& CallFuncEqualEqualIntIntReturnValue2, bool& CallFuncEqualEqualByteByteReturnValue2, bool& CallFuncBooleanANDReturnValue3, bool& CallFuncBooleanANDReturnValue4, bool& CallFuncEqualEqualIntIntReturnValue3, bool& CallFuncEqualEqualIntIntReturnValue4, bool& CallFuncBooleanORReturnValue1, bool& CallFuncBooleanANDReturnValue5, bool& CallFuncBooleanANDReturnValue6, bool& CallFuncBooleanORReturnValue2, bool& CallFuncBooleanORReturnValue3, bool& CallFuncBooleanORReturnValue4); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.IsValidTeam (Has no native function)
	static void IsValidTeam(int& TeamtoCheck, class AActor*& ActorToCheck, class UObject*& WorldContext, bool& Valid, bool& CallFuncIsValidReturnValue, bool& CallFuncEqualEqualIntIntReturnValue, unsigned char& CallFuncConvIntToByteReturnValue, unsigned char& CallFuncGetActorPvPTeamIndexTeamIndex, bool& CallFuncGetActorPvPTeamIndexReturnValue, bool& CallFuncEqualEqualByteByteReturnValue, bool& CallFuncBooleanORReturnValue); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.AwardScore (Has no native function)
	static void AwardScore(class AActor*& Actor, int& Score, struct TEnumAsByte<EAwardScoreType>& Type, class AController*& Controller, class UFortMinigameLogicComponent*& MinigameLogic, struct FGameplayTagContainer& TargetTags, class UObject*& WorldContext, int& localScore, class UFortMinigameManager*& localMinigameManager, bool& CallFuncNotEqualByteByteReturnValue, bool& CallFuncIsValidReturnValue, int& TempintVariable, int& CallFuncMultiplyIntIntReturnValue, struct TEnumAsByte<EAwardScoreType>& TempbyteVariable, class AFortPlayerController*& K2NodeDynamicCastAsFortPlayerController, bool& K2NodeDynamicCastbSuccess, class UFortMinigameManager*& CallFuncGetMinigameManagerReturnValue, class UFortMinigameStatsComponent*& CallFuncGetMinigameStatsComponentReturnValue, bool& CallFuncIsValidReturnValue1, class UFortMinigameStatFilter*& CallFuncGetLoadedStatFromClassReturnValue, class AFortPlayerState*& K2NodeDynamicCastAsFortPlayerState, bool& K2NodeDynamicCastbSuccess1, int& CallFuncGetStatForPlayerReturnValue, struct FGameplayTagContainer& CallFuncGetSourceAndContextTagsOutSourceTags, struct FGameplayTagContainer& CallFuncGetSourceAndContextTagsOutContextTags, int& CallFuncSubtractIntIntReturnValue, int& K2NodeSelectDefault); // (Static | Public | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Creative/Devices/Common/Creative_CommonDeviceFunctionLibrary.Creative_CommonDeviceFunctionLibrary_C.IsOnUnpublishedIsland (Has no native function)
	static void IsOnUnpublishedIsland(class AActor*& Actor, class UObject*& WorldContext, bool& EditMode, enum EFortVolumeType& CallFuncGetExperienceTypeReturnValue, bool& CallFuncEqualEqualByteByteReturnValue); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent | BlueprintPure)
};

