// AnimBlueprintGeneratedClass /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C
// Size: 0xc618
class UFortnite_M_Avg_Player_AnimBlueprint_C : public UFortPlayerAnimInstance
{
	struct FPointerToUberGraphFrame* UberGraphFrame; // 0x1a20 (0x8)
	struct FAnimBlueprintGeneratedMutableData AnimBlueprintMutables; // 0x1a28 (0x150)
	struct FAnimSubsystemInstance* AnimBlueprintExtensionTag; // 0x1b78 (0x8)
	struct FAnimSubsystem_SharedLinkedAnimLayers AnimBlueprintExtensionSharedLinkedAnimLayers; // 0x1b80 (0x18)
	struct FAnimSubsystemInstance* AnimBlueprintExtensionPropertyAccess; // 0x1b98 (0x8)
	struct FAnimSubsystemInstance* AnimBlueprintExtensionBase; // 0x1ba0 (0x8)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose37; // 0x1ba8 (0xc0)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose36; // 0x1c68 (0xc0)
	struct FAnimNode_Root AnimGraphNodeRoot42; // 0x1d28 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose35; // 0x1d48 (0xc0)
	struct FAnimNode_Root AnimGraphNodeRoot41; // 0x1e08 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose34; // 0x1e28 (0xc0)
	struct FAnimNode_Root AnimGraphNodeRoot40; // 0x1ee8 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose33; // 0x1f08 (0xc0)
	struct FAnimNode_Root AnimGraphNodeRoot39; // 0x1fc8 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose32; // 0x1fe8 (0xc0)
	struct FAnimNode_Root AnimGraphNodeRoot38; // 0x20a8 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose31; // 0x20c8 (0xc0)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose30; // 0x2188 (0xc0)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose29; // 0x2248 (0xc0)
	struct FAnimNode_Root AnimGraphNodeRoot37; // 0x2308 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose28; // 0x2328 (0xc0)
	struct FAnimNode_Root AnimGraphNodeRoot36; // 0x23e8 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose27; // 0x2408 (0xc0)
	struct FAnimNode_Root AnimGraphNodeRoot35; // 0x24c8 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose26; // 0x24e8 (0xc0)
	struct FAnimNode_Root AnimGraphNodeRoot34; // 0x25a8 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose25; // 0x25c8 (0xc0)
	struct FAnimNode_Root AnimGraphNodeRoot33; // 0x2688 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose24; // 0x26a8 (0xc0)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose23; // 0x2768 (0xc0)
	struct FAnimNode_Root AnimGraphNodeRoot32; // 0x2828 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose22; // 0x2848 (0xc0)
	struct FAnimNode_Root AnimGraphNodeRoot31; // 0x2908 (0x20)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer58; // 0x2928 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool48; // 0x2970 (0x48)
	struct FAnimNode_RefPose AnimGraphNodeIdentityPose8; // 0x29b8 (0x10)
	struct FAnimNode_Root AnimGraphNodeRoot30; // 0x29c8 (0x20)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer57; // 0x29e8 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool47; // 0x2a30 (0x48)
	struct FAnimNode_RefPose AnimGraphNodeIdentityPose7; // 0x2a78 (0x10)
	struct FAnimNode_Root AnimGraphNodeRoot29; // 0x2a88 (0x20)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer56; // 0x2aa8 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool46; // 0x2af0 (0x48)
	struct FAnimNode_RefPose AnimGraphNodeIdentityPose6; // 0x2b38 (0x10)
	struct FAnimNode_Root AnimGraphNodeRoot28; // 0x2b48 (0x20)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer55; // 0x2b68 (0x48)
	struct FAnimNode_Root AnimGraphNodeRoot27; // 0x2bb0 (0x20)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer54; // 0x2bd0 (0x48)
	struct FAnimNode_Root AnimGraphNodeRoot26; // 0x2c18 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose21; // 0x2c38 (0xc0)
	struct FAnimNode_Root AnimGraphNodeRoot25; // 0x2cf8 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose20; // 0x2d18 (0xc0)
	struct FAnimNode_Root AnimGraphNodeRoot24; // 0x2dd8 (0x20)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool45; // 0x2df8 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer53; // 0x2e40 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer52; // 0x2e88 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer51; // 0x2ed0 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool44; // 0x2f18 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer50; // 0x2f60 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer49; // 0x2fa8 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool43; // 0x2ff0 (0x48)
	struct FAnimNode_RefPose AnimGraphNodeIdentityPose5; // 0x3038 (0x10)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool42; // 0x3048 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer48; // 0x3090 (0x48)
	struct FAnimNode_BlendListByEnum AnimGraphNodeBlendListByEnum11; // 0x30d8 (0x48)
	struct FAnimNode_Root AnimGraphNodeRoot23; // 0x3120 (0x20)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool41; // 0x3140 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer47; // 0x3188 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer46; // 0x31d0 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer45; // 0x3218 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool40; // 0x3260 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer44; // 0x32a8 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer43; // 0x32f0 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool39; // 0x3338 (0x48)
	struct FAnimNode_RefPose AnimGraphNodeIdentityPose4; // 0x3380 (0x10)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool38; // 0x3390 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer42; // 0x33d8 (0x48)
	struct FAnimNode_BlendListByEnum AnimGraphNodeBlendListByEnum10; // 0x3420 (0x48)
	struct FAnimNode_Root AnimGraphNodeRoot22; // 0x3468 (0x20)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer41; // 0x3488 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool37; // 0x34d0 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer40; // 0x3518 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer39; // 0x3560 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool36; // 0x35a8 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer38; // 0x35f0 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool35; // 0x3638 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer37; // 0x3680 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool34; // 0x36c8 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer36; // 0x3710 (0x48)
	struct FAnimNode_RefPose AnimGraphNodeIdentityPose3; // 0x3758 (0x10)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool33; // 0x3768 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer35; // 0x37b0 (0x48)
	struct FAnimNode_BlendListByEnum AnimGraphNodeBlendListByEnum9; // 0x37f8 (0x48)
	struct FAnimNode_Root AnimGraphNodeRoot21; // 0x3840 (0x20)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool32; // 0x3860 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer34; // 0x38a8 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer33; // 0x38f0 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer32; // 0x3938 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool31; // 0x3980 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer31; // 0x39c8 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer30; // 0x3a10 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer29; // 0x3a58 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool30; // 0x3aa0 (0x48)
	struct FAnimNode_BlendListByEnum AnimGraphNodeBlendListByEnum8; // 0x3ae8 (0x48)
	struct FAnimNode_BlendListByEnum AnimGraphNodeBlendListByEnum7; // 0x3b30 (0x48)
	struct FAnimNode_BlendListByEnum AnimGraphNodeBlendListByEnum6; // 0x3b78 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer28; // 0x3bc0 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool29; // 0x3c08 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer27; // 0x3c50 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool28; // 0x3c98 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer26; // 0x3ce0 (0x48)
	struct FAnimNode_BlendListByEnum AnimGraphNodeBlendListByEnum5; // 0x3d28 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer25; // 0x3d70 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool27; // 0x3db8 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer24; // 0x3e00 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool26; // 0x3e48 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer23; // 0x3e90 (0x48)
	struct FAnimNode_BlendListByEnum AnimGraphNodeBlendListByEnum4; // 0x3ed8 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool25; // 0x3f20 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer22; // 0x3f68 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer21; // 0x3fb0 (0x48)
	struct FAnimNode_ModifyCurve AnimGraphNodeModifyCurve; // 0x3ff8 (0x100)
	struct FAnimNode_BlendListByEnum AnimGraphNodeBlendListByEnum3; // 0x40f8 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer20; // 0x4140 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool24; // 0x4188 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer19; // 0x41d0 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer18; // 0x4218 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer17; // 0x4260 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool23; // 0x42a8 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer16; // 0x42f0 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool22; // 0x4338 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer15; // 0x4380 (0x48)
	struct FAnimNode_Root AnimGraphNodeRoot20; // 0x43c8 (0x20)
	struct FAnimNode_Root AnimGraphNodeRoot19; // 0x43e8 (0x20)
	struct FAnimNode_Root AnimGraphNodeRoot18; // 0x4408 (0x20)
	struct FAnimNode_Root AnimGraphNodeRoot17; // 0x4428 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose19; // 0x4448 (0xc0)
	struct FAnimNode_Root AnimGraphNodeRoot16; // 0x4508 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose18; // 0x4528 (0xc0)
	struct FAnimNode_Root AnimGraphNodeRoot15; // 0x45e8 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose17; // 0x4608 (0xc0)
	struct FAnimNode_Root AnimGraphNodeRoot14; // 0x46c8 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose16; // 0x46e8 (0xc0)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose15; // 0x47a8 (0xc0)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose14; // 0x4868 (0xc0)
	struct FAnimNode_Root AnimGraphNodeRoot13; // 0x4928 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose13; // 0x4948 (0xc0)
	struct FAnimNode_Root AnimGraphNodeRoot12; // 0x4a08 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeSubInput; // 0x4a28 (0xc0)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose12; // 0x4ae8 (0xc0)
	struct FAnimNode_Root AnimGraphNodeRoot11; // 0x4ba8 (0x20)
	struct FAnimNode_Slot AnimGraphNodeSlot14; // 0x4bc8 (0x48)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose48; // 0x4c10 (0x28)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose47; // 0x4c38 (0x28)
	struct FAnimNode_Slot AnimGraphNodeSlot13; // 0x4c60 (0x48)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult37; // 0x4ca8 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult36; // 0x4cd0 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult35; // 0x4cf8 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult34; // 0x4d20 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult33; // 0x4d48 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult32; // 0x4d70 (0x28)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer14; // 0x4d98 (0x48)
	struct FAnimNode_StateResult AnimGraphNodeStateResult15; // 0x4de0 (0x20)
	struct FAnimNode_LinkedAnimLayer AnimGraphNodeLinkedAnimLayer18; // 0x4e00 (0xc8)
	struct FAnimNode_RefPose AnimGraphNodeLocalRefPose; // 0x4ec8 (0x10)
	struct FAnimNode_StateResult AnimGraphNodeStateResult14; // 0x4ed8 (0x20)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose46; // 0x4ef8 (0x28)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose45; // 0x4f20 (0x28)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool21; // 0x4f48 (0x48)
	struct FAnimNode_Slot AnimGraphNodeSlot12; // 0x4f90 (0x48)
	struct FAnimNode_StateResult AnimGraphNodeStateResult13; // 0x4fd8 (0x20)
	struct FAnimNode_StateMachine AnimGraphNodeStateMachine4; // 0x4ff8 (0xc8)
	struct FAnimNode_SaveCachedPose AnimGraphNodeSaveCachedPose21; // 0x50c0 (0x100)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose44; // 0x51c0 (0x28)
	struct FAnimNode_LinkedAnimLayer AnimGraphNodeLinkedAnimLayer17; // 0x51e8 (0xc8)
	struct FAnimNode_LinkedAnimGraph AnimGraphNodeLinkedAnimGraph15; // 0x52b0 (0xb8)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool20; // 0x5368 (0x48)
	struct FAnimNode_LinkedAnimGraph AnimGraphNodeLinkedAnimGraph14; // 0x53b0 (0xb8)
	struct FAnimNode_LinkedAnimLayer AnimGraphNodeLinkedAnimLayer16; // 0x5468 (0xc8)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool19; // 0x5530 (0x48)
	struct FAnimNode_LinkedAnimLayer AnimGraphNodeLinkedAnimLayer15; // 0x5578 (0xc8)
	struct FAnimNode_SaveCachedPose AnimGraphNodeSaveCachedPose20; // 0x5640 (0x100)
	struct FAnimNode_Root AnimGraphNodeRoot10; // 0x5740 (0x20)
	struct FAnimNode_LayeredBoneBlend AnimGraphNodeLayeredBoneBlend7; // 0x5760 (0xe0)
	struct FAnimNode_ApplyAdditive AnimGraphNodeApplyAdditive7; // 0x5840 (0xc8)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose43; // 0x5908 (0x28)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer13; // 0x5930 (0x48)
	struct FAnimNode_LayeredBoneBlend AnimGraphNodeLayeredBoneBlend6; // 0x5978 (0xe0)
	struct FAnimNode_BlendListByEnum AnimGraphNodeBlendListByEnum2; // 0x5a58 (0x48)
	struct FAnimNode_Slot AnimGraphNodeSlot11; // 0x5aa0 (0x48)
	struct FAnimNode_ApplyAdditive AnimGraphNodeApplyAdditive6; // 0x5ae8 (0xc8)
	struct FAnimNode_ApplyAdditive AnimGraphNodeApplyAdditive5; // 0x5bb0 (0xc8)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose42; // 0x5c78 (0x28)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool18; // 0x5ca0 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer12; // 0x5ce8 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer11; // 0x5d30 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool17; // 0x5d78 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool16; // 0x5dc0 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer10; // 0x5e08 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer9; // 0x5e50 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer8; // 0x5e98 (0x48)
	struct FAnimNode_Root AnimGraphNodeRoot9; // 0x5ee0 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose11; // 0x5f00 (0xc0)
	struct FAnimNode_SaveCachedPose AnimGraphNodeSaveCachedPose19; // 0x5fc0 (0x100)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose41; // 0x60c0 (0x28)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose40; // 0x60e8 (0x28)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose10; // 0x6110 (0xc0)
	struct FAnimNode_SaveCachedPose AnimGraphNodeSaveCachedPose18; // 0x61d0 (0x100)
	struct FAnimNode_Root AnimGraphNodeRoot8; // 0x62d0 (0x20)
	struct FAnimNode_Slot AnimGraphNodeSlot10; // 0x62f0 (0x48)
	struct FAnimNode_Slot AnimGraphNodeSlot9; // 0x6338 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool15; // 0x6380 (0x48)
	struct FAnimNode_Slot AnimGraphNodeSlot8; // 0x63c8 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer7; // 0x6410 (0x48)
	struct FAnimNode_LayeredBoneBlend AnimGraphNodeLayeredBoneBlend5; // 0x6458 (0xe0)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer6; // 0x6538 (0x48)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose39; // 0x6580 (0x28)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool14; // 0x65a8 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer5; // 0x65f0 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool13; // 0x6638 (0x48)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose9; // 0x6680 (0xc0)
	struct FAnimNode_SaveCachedPose AnimGraphNodeSaveCachedPose17; // 0x6740 (0x100)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose38; // 0x6840 (0x28)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose37; // 0x6868 (0x28)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose36; // 0x6890 (0x28)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool12; // 0x68b8 (0x48)
	struct FAnimNode_LayeredBoneBlend AnimGraphNodeLayeredBoneBlend4; // 0x6900 (0xe0)
	struct FAnimNode_Slot AnimGraphNodeSlot7; // 0x69e0 (0x48)
	struct FAnimNode_Root AnimGraphNodeRoot7; // 0x6a28 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose8; // 0x6a48 (0xc0)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool11; // 0x6b08 (0x48)
	struct FAnimNode_LinkedAnimGraph AnimGraphNodeLinkedAnimGraph13; // 0x6b50 (0xb8)
	struct FAnimNode_ApplyAdditive AnimGraphNodeApplyAdditive4; // 0x6c08 (0xc8)
	struct FAnimNode_SaveCachedPose AnimGraphNodeSaveCachedPose16; // 0x6cd0 (0x100)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose35; // 0x6dd0 (0x28)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose34; // 0x6df8 (0x28)
	struct FAnimNode_Root AnimGraphNodeRoot6; // 0x6e20 (0x20)
	struct FAnimNode_LinkedAnimGraph AnimGraphNodeLinkedAnimGraph12; // 0x6e40 (0xb8)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose7; // 0x6ef8 (0xc0)
	struct FAnimNode_ApplyAdditive AnimGraphNodeApplyAdditive3; // 0x6fb8 (0xc8)
	struct FAnimNode_SaveCachedPose AnimGraphNodeSaveCachedPose15; // 0x7080 (0x100)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose33; // 0x7180 (0x28)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool10; // 0x71a8 (0x48)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose32; // 0x71f0 (0x28)
	struct FAnimNode_Root AnimGraphNodeRoot5; // 0x7218 (0x20)
	struct FAnimNode_LayeredBoneBlend AnimGraphNodeLayeredBoneBlend3; // 0x7238 (0xe0)
	struct FAnimNode_RefPose AnimGraphNodeIdentityPose2; // 0x7318 (0x10)
	struct FAnimNode_LayeredBoneBlend AnimGraphNodeLayeredBoneBlend2; // 0x7328 (0xe0)
	struct FAnimNode_RefPose AnimGraphNodeIdentityPose1; // 0x7408 (0x10)
	struct FAnimNode_Slot AnimGraphNodeSlot6; // 0x7418 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool9; // 0x7460 (0x48)
	struct FAnimNode_LinkedAnimGraph AnimGraphNodeLinkedAnimGraph11; // 0x74a8 (0xb8)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult31; // 0x7560 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult30; // 0x7588 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult29; // 0x75b0 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult28; // 0x75d8 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult27; // 0x7600 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult26; // 0x7628 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult25; // 0x7650 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult24; // 0x7678 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult23; // 0x76a0 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult22; // 0x76c8 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult21; // 0x76f0 (0x28)
	struct FAnimNode_LinkedAnimGraph AnimGraphNodeLinkedAnimGraph10; // 0x7718 (0xb8)
	struct FAnimNode_StateResult AnimGraphNodeStateResult12; // 0x77d0 (0x20)
	struct FAnimNode_BlendSpacePlayer AnimGraphNodeBlendSpacePlayer4; // 0x77f0 (0x70)
	struct FAnimNode_BlendSpacePlayer AnimGraphNodeBlendSpacePlayer3; // 0x7860 (0x70)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool8; // 0x78d0 (0x48)
	struct FAnimNode_BlendSpacePlayer AnimGraphNodeBlendSpacePlayer2; // 0x7918 (0x70)
	struct FAnimNode_BlendSpacePlayer AnimGraphNodeBlendSpacePlayer1; // 0x7988 (0x70)
	struct FAnimNode_BlendListByEnum AnimGraphNodeBlendListByEnum1; // 0x79f8 (0x48)
	struct FAnimNode_BlendSpacePlayer AnimGraphNodeBlendSpacePlayer; // 0x7a40 (0x70)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer4; // 0x7ab0 (0x48)
	struct FAnimNode_ApplyAdditive AnimGraphNodeApplyAdditive2; // 0x7af8 (0xc8)
	struct FAnimNode_StateResult AnimGraphNodeStateResult11; // 0x7bc0 (0x20)
	struct FAnimNode_RefPose AnimGraphNodeIdentityPose; // 0x7be0 (0x10)
	struct FAnimNode_StateResult AnimGraphNodeStateResult10; // 0x7bf0 (0x20)
	struct FAnimNode_StateMachine AnimGraphNodeStateMachine3; // 0x7c10 (0xc8)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose6; // 0x7cd8 (0xc0)
	struct FAnimNode_ApplyAdditive AnimGraphNodeApplyAdditive1; // 0x7d98 (0xc8)
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNodeLocalToComponentSpace1; // 0x7e60 (0x20)
	struct FAnimNode_HandIKRetargeting AnimGraphNodeHandIKRetargeting; // 0x7e80 (0x110)
	struct FAnimNode_Slot AnimGraphNodeSlot5; // 0x7f90 (0x48)
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNodeComponentToLocalSpace1; // 0x7fd8 (0x20)
	struct FAnimNode_Root AnimGraphNodeRoot4; // 0x7ff8 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose5; // 0x8018 (0xc0)
	struct FAnimNode_SaveCachedPose AnimGraphNodeSaveCachedPose14; // 0x80d8 (0x100)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose31; // 0x81d8 (0x28)
	struct FAnimNode_SaveCachedPose AnimGraphNodeSaveCachedPose13; // 0x8200 (0x100)
	struct FAnimNode_LinkedAnimGraph AnimGraphNodeLinkedAnimGraph9; // 0x8300 (0xb8)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose30; // 0x83b8 (0x28)
	struct FAnimNode_LinkedAnimLayer AnimGraphNodeLayer2; // 0x83e0 (0xc8)
	struct FAnimNode_LinkedAnimLayer AnimGraphNodeLinkedAnimLayer14; // 0x84a8 (0xc8)
	struct FAnimNode_LinkedAnimGraph AnimGraphNodeLinkedAnimGraph8; // 0x8570 (0xb8)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose29; // 0x8628 (0x28)
	struct FAnimNode_LinkedAnimLayer AnimGraphNodeLinkedAnimLayer13; // 0x8650 (0xc8)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose4; // 0x8718 (0xc0)
	struct FAnimNode_SaveCachedPose AnimGraphNodeSaveCachedPose12; // 0x87d8 (0x100)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose28; // 0x88d8 (0x28)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose27; // 0x8900 (0x28)
	struct FAnimNode_SaveCachedPose AnimGraphNodeSaveCachedPose11; // 0x8928 (0x100)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose26; // 0x8a28 (0x28)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose25; // 0x8a50 (0x28)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose24; // 0x8a78 (0x28)
	struct FAnimNode_Slot AnimGraphNodeSlot4; // 0x8aa0 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool7; // 0x8ae8 (0x48)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose23; // 0x8b30 (0x28)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose22; // 0x8b58 (0x28)
	struct FAnimNode_SaveCachedPose AnimGraphNodeSaveCachedPose10; // 0x8b80 (0x100)
	struct FAnimNode_Root AnimGraphNodeRoot3; // 0x8c80 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose3; // 0x8ca0 (0xc0)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose2; // 0x8d60 (0xc0)
	struct FAnimNode_RotateRootBone AnimGraphNodeRotateRootBone; // 0x8e20 (0xa8)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool6; // 0x8ec8 (0x48)
	struct FAnimNode_SaveCachedPose AnimGraphNodeSaveCachedPose9; // 0x8f10 (0x100)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose21; // 0x9010 (0x28)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose20; // 0x9038 (0x28)
	struct FAnimNode_LayeredBoneBlend AnimGraphNodeLayeredBoneBlend1; // 0x9060 (0xe0)
	struct FAnimNode_Root AnimGraphNodeRoot2; // 0x9140 (0x20)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose1; // 0x9160 (0xc0)
	struct FAnimNode_Slot AnimGraphNodeSlot3; // 0x9220 (0x48)
	struct FAnimNode_SaveCachedPose AnimGraphNodeSaveCachedPose8; // 0x9268 (0x100)
	struct FAnimNode_Slot AnimGraphNodeSlot2; // 0x9368 (0x48)
	struct FAnimNode_SaveCachedPose AnimGraphNodeSaveCachedPose7; // 0x93b0 (0x100)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose19; // 0x94b0 (0x28)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool5; // 0x94d8 (0x48)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose18; // 0x9520 (0x28)
	struct FAnimNode_Slot AnimGraphNodeSlot1; // 0x9548 (0x48)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose17; // 0x9590 (0x28)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose16; // 0x95b8 (0x28)
	struct FAnimNode_LinkedAnimLayer AnimGraphNodeLinkedAnimLayer12; // 0x95e0 (0xc8)
	struct FAnimNode_SaveCachedPose AnimGraphNodeSaveCachedPose6; // 0x96a8 (0x100)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose15; // 0x97a8 (0x28)
	struct FAnimNode_Root AnimGraphNodeRoot1; // 0x97d0 (0x20)
	struct FAnimNode_RotationOffsetBlendSpace AnimGraphNodeRotationOffsetBlendSpace2; // 0x97f0 (0x118)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool4; // 0x9908 (0x48)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool3; // 0x9950 (0x48)
	struct FAnimNode_RotationOffsetBlendSpace AnimGraphNodeRotationOffsetBlendSpace1; // 0x9998 (0x118)
	struct FAnimNode_RotationOffsetBlendSpace AnimGraphNodeRotationOffsetBlendSpace; // 0x9ab0 (0x118)
	struct FAnimNode_LinkedInputPose AnimGraphNodeLinkedInputPose; // 0x9bc8 (0xc0)
	struct FAnimNode_SaveCachedPose AnimGraphNodeSaveCachedPose5; // 0x9c88 (0x100)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose14; // 0x9d88 (0x28)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose13; // 0x9db0 (0x28)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose12; // 0x9dd8 (0x28)
	struct FAnimNode_Root AnimGraphNodeRoot; // 0x9e00 (0x20)
	struct FAnimNode_SaveCachedPose AnimGraphNodeSaveCachedPose4; // 0x9e20 (0x100)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult20; // 0x9f20 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult19; // 0x9f48 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult18; // 0x9f70 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult17; // 0x9f98 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult16; // 0x9fc0 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult15; // 0x9fe8 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult14; // 0xa010 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult13; // 0xa038 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult12; // 0xa060 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult11; // 0xa088 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult10; // 0xa0b0 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult9; // 0xa0d8 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult8; // 0xa100 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult7; // 0xa128 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult6; // 0xa150 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult5; // 0xa178 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult4; // 0xa1a0 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult3; // 0xa1c8 (0x28)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult2; // 0xa1f0 (0x28)
	struct FAnimNode_LinkedAnimGraph AnimGraphNodeLinkedAnimGraph7; // 0xa218 (0xb8)
	struct FAnimNode_LinkedAnimGraph AnimGraphNodeLinkedAnimGraph6; // 0xa2d0 (0xb8)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool2; // 0xa388 (0x48)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose11; // 0xa3d0 (0x28)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose10; // 0xa3f8 (0x28)
	struct FAnimNode_LinkedAnimLayer AnimGraphNodeLinkedAnimLayer11; // 0xa420 (0xc8)
	struct FAnimNode_ApplyAdditive AnimGraphNodeApplyAdditive; // 0xa4e8 (0xc8)
	struct FAnimNode_StateResult AnimGraphNodeStateResult9; // 0xa5b0 (0x20)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose9; // 0xa5d0 (0x28)
	struct FAnimNode_LinkedAnimGraph AnimGraphNodeLinkedAnimGraph5; // 0xa5f8 (0xb8)
	struct FAnimNode_StateResult AnimGraphNodeStateResult8; // 0xa6b0 (0x20)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult1; // 0xa6d0 (0x28)
	struct FAnimNode_StateMachine AnimGraphNodeStateMachine2; // 0xa6f8 (0xc8)
	struct FAnimNode_StateResult AnimGraphNodeStateResult7; // 0xa7c0 (0x20)
	struct FAnimNode_LinkedAnimGraph AnimGraphNodeLinkedAnimGraph4; // 0xa7e0 (0xb8)
	struct FAnimNode_StateResult AnimGraphNodeStateResult6; // 0xa898 (0x20)
	struct FAnimNode_TransitionResult AnimGraphNodeTransitionResult; // 0xa8b8 (0x28)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer3; // 0xa8e0 (0x48)
	struct FAnimNode_BlendListByEnum AnimGraphNodeBlendListByEnum; // 0xa928 (0x48)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer2; // 0xa970 (0x48)
	struct FAnimNode_StateResult AnimGraphNodeStateResult5; // 0xa9b8 (0x20)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer1; // 0xa9d8 (0x48)
	struct FAnimNode_StateResult AnimGraphNodeStateResult4; // 0xaa20 (0x20)
	struct FAnimNode_LinkedAnimGraph AnimGraphNodeLinkedAnimGraph3; // 0xaa40 (0xb8)
	struct FAnimNode_StateResult AnimGraphNodeStateResult3; // 0xaaf8 (0x20)
	struct FAnimNode_SequencePlayer AnimGraphNodeSequencePlayer; // 0xab18 (0x48)
	struct FAnimNode_StateResult AnimGraphNodeStateResult2; // 0xab60 (0x20)
	struct FAnimNode_LinkedAnimGraph AnimGraphNodeLinkedAnimGraph2; // 0xab80 (0xb8)
	struct FAnimNode_StateResult AnimGraphNodeStateResult1; // 0xac38 (0x20)
	struct FAnimNode_StateMachine AnimGraphNodeStateMachine1; // 0xac58 (0xc8)
	struct FAnimNode_SaveCachedPose AnimGraphNodeSaveCachedPose3; // 0xad20 (0x100)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose8; // 0xae20 (0x28)
	struct FAnimNode_SaveCachedPose AnimGraphNodeSaveCachedPose2; // 0xae48 (0x100)
	struct FAnimNode_SaveCachedPose AnimGraphNodeSaveCachedPose1; // 0xaf48 (0x100)
	struct FAnimNode_LinkedAnimLayer AnimGraphNodeLayer1; // 0xb048 (0xc8)
	struct FAnimNode_LinkedAnimLayer AnimGraphNodeLayer; // 0xb110 (0xc8)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose7; // 0xb1d8 (0x28)
	struct FAnimNode_LinkedAnimLayer AnimGraphNodeLinkedAnimLayer10; // 0xb200 (0xc8)
	struct FAnimNode_SaveCachedPose AnimGraphNodeSaveCachedPose; // 0xb2c8 (0x100)
	struct FAnimNode_LinkedAnimLayer AnimGraphNodeLinkedAnimLayer9; // 0xb3c8 (0xc8)
	struct FAnimNode_LayeredBoneBlend AnimGraphNodeLayeredBoneBlend; // 0xb490 (0xe0)
	struct FAnimNode_LinkedAnimGraph AnimGraphNodeLinkedAnimGraph1; // 0xb570 (0xb8)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool1; // 0xb628 (0x48)
	struct FFortAnimNode_ScaleCharacterBones FortAnimGraphNodeScaleCharacterBones; // 0xb670 (0xd8)
	struct FAnimNode_Inertialization AnimGraphNodeInertialization; // 0xb748 (0x100)
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNodeLocalToComponentSpace; // 0xb848 (0x20)
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNodeComponentToLocalSpace; // 0xb868 (0x20)
	struct FAnimNode_Slot AnimGraphNodeSlot; // 0xb888 (0x48)
	struct FAnimNode_LinkedAnimLayer AnimGraphNodeLinkedAnimLayer8; // 0xb8d0 (0xc8)
	struct FAnimNode_LinkedAnimLayer AnimGraphNodeLinkedAnimLayer7; // 0xb998 (0xc8)
	struct FAnimNode_LinkedAnimLayer AnimGraphNodeLinkedAnimLayer6; // 0xba60 (0xc8)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose6; // 0xbb28 (0x28)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose5; // 0xbb50 (0x28)
	struct FAnimNode_LinkedAnimLayer AnimGraphNodeLinkedAnimLayer5; // 0xbb78 (0xc8)
	struct FAnimNode_LinkedAnimLayer AnimGraphNodeLinkedAnimLayer4; // 0xbc40 (0xc8)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose4; // 0xbd08 (0x28)
	struct FAnimNode_LinkedAnimLayer AnimGraphNodeLinkedAnimLayer3; // 0xbd30 (0xc8)
	struct FAnimNode_LinkedAnimLayer AnimGraphNodeLinkedAnimLayer2; // 0xbdf8 (0xc8)
	struct FAnimNode_LinkedAnimLayer AnimGraphNodeLinkedAnimLayer1; // 0xbec0 (0xc8)
	struct FAnimNode_LinkedAnimLayer AnimGraphNodeLinkedAnimLayer; // 0xbf88 (0xc8)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose3; // 0xc050 (0x28)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose2; // 0xc078 (0x28)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose1; // 0xc0a0 (0x28)
	struct FAnimNode_UseCachedPose AnimGraphNodeUseCachedPose; // 0xc0c8 (0x28)
	struct FAnimNode_BlendListByInt AnimGraphNodeBlendListByInt; // 0xc0f0 (0x48)
	struct FAnimNode_StateResult AnimGraphNodeStateResult; // 0xc138 (0x20)
	struct FAnimNode_StateMachine AnimGraphNodeStateMachine; // 0xc158 (0xc8)
	struct FAnimNode_BlendListByBool AnimGraphNodeBlendListByBool; // 0xc220 (0x48)
	struct FAnimNode_LinkedAnimGraph AnimGraphNodeLinkedAnimGraph; // 0xc268 (0xb8)
	bool CustomPropertybHasMotorcyclePassenger05121225461E24240C03038F19993CBE; // 0xc320 (0x1)
	bool CustomPropertybIsMotorcyclePassenger05121225461E24240C03038F19993CBE; // 0xc321 (0x1)
	bool CustomPropertybIsMotorcycleDriver05121225461E24240C03038F19993CBE; // 0xc322 (0x1)
	bool CustomPropertyParaGlideTriggerAnimEE06BC0D4AF7A3598BB824A5286F89C8; // 0xc323 (0x1)
	struct FName CustomPropertyEmoteAnimOffsetCurveNameD066576F42932FCE06C5E8B658C15225; // 0xc324 (0x4)
	struct FVector CustomPropertyLeftHandOverrideD066576F42932FCE06C5E8B658C15225; // 0xc328 (0x18)
	struct FVector CustomPropertyRightHandOverrideD066576F42932FCE06C5E8B658C15225; // 0xc340 (0x18)
	bool CustomPropertyIsHidingInPropD066576F42932FCE06C5E8B658C15225; // 0xc358 (0x1)
	unsigned char unreflected_c359[0x3]; // 0xc359 (0x3) 
	struct FFortAnimInput_AdjustedAim CustomPropertyInputParam72CED7AF4FEDEFE487025CB4B92A64EE; // 0xc35c (0x23c)
	struct FMulticastInlineDelegate MenuScreenDispatcher; // 0xc598 (0x10)
	double StartAnimBlendTime; // 0xc5a8 (0x8)
	double PivotAnimBlendTime; // 0xc5b0 (0x8)
	double CrouchPlayRate; // 0xc5b8 (0x8)
	bool IsSnowman; // 0xc5c0 (0x1)
	bool ShouldTrigerGrappleMontage; // 0xc5c1 (0x1)
	unsigned char unreflected_c5c2[0x6]; // 0xc5c2 (0x6) 
	struct FMulticastInlineDelegate IndigoBoost; // 0xc5c8 (0x10)
	bool ParaGlideUseAltGliderCam; // 0xc5d8 (0x1)
	unsigned char unreflected_c5d9[0x7]; // 0xc5d9 (0x7) 
	struct FVector LeftHandOverride; // 0xc5e0 (0x18)
	struct FVector RightHandOverride; // 0xc5f8 (0x18)
	bool ParaGlideTriggerAnim; // 0xc610 (0x1)
	unsigned char unreflected_c611[0x3]; // 0xc611 (0x3) 
	struct FName EmoteAnimOffsetCurveName; // 0xc614 (0x4)

	/* Functions */

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.MovementMode_AimOffset (Has no native function)
	void MovementModeAimOffset(struct FPoseLink& InAimOffsetsPose, struct FPoseLink& InSourcePosePreAimOffsets, struct FPoseLink& MovementModeAimOffset); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.MovementMode_FinalPoseOverride (Has no native function)
	void MovementModeFinalPoseOverride(struct FPoseLink& InFinalPose, struct FPoseLink& MovementModeFinalPoseOverride); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.MovementMode_FullBodyOverride (Has no native function)
	void MovementModeFullBodyOverride(struct FPoseLink& InputPoseFullBody, struct FPoseLink& MovementModeFullBodyOverride); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.MovementMode_SourcePose (Has no native function)
	void MovementModeSourcePose(struct FPoseLink& InSourcePoseBase, struct FPoseLink& MovementModeSourcePose); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.MovementMode_LocomotionAdditives (Has no native function)
	void MovementModeLocomotionAdditives(struct FPoseLink& InLocomotionAdditivesPose, struct FPoseLink& MovementModeLocomotionAdditives); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.MovementMode_LowerBodyOverride (Has no native function)
	void MovementModeLowerBodyOverride(struct FPoseLink& InLowerBodyPose, struct FPoseLink& InSourcePose, struct FPoseLink& InSourcePosePreUpperBodySlot, struct FPoseLink& MovementModeLowerBodyOverride); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.CharacterSkeletalControlPostLegIK (Has no native function)
	void CharacterSkeletalControlPostLegIK(struct FPoseLink& InPosePostLegIK, struct FPoseLink& CharacterSkeletalControlPostLegIK); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.FullBodyOverride (Has no native function)
	void FullBodyOverride(struct FPoseLink& PassThroughFullBodyPose, struct FPoseLink& FullBodyOverride); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.ItemPreIK (Has no native function)
	void ItemPreIK(struct FPoseLink& InPosePreIK, struct FPoseLink& ItemPreIK); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.ItemFullBodyOverride (Has no native function)
	void ItemFullBodyOverride(struct FPoseLink& InPoseFullBody, struct FPoseLink& ItemFullBodyOverride); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.ItemAimOffset (Has no native function)
	void ItemAimOffset(struct FPoseLink& InPoseAimOffset, double& AimOffsetAlpha, double& Yaw, double& Pitch, struct FPoseLink& InPoseUpperLowerPreMeleeAO, struct FPoseLink& ItemAimOffset); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.ItemSkeletalControl (Has no native function)
	void ItemSkeletalControl(struct FPoseLink& InPose, struct FPoseLink& ItemSkeletalControl); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.ItemSwimJumpSurfaceEnd (Has no native function)
	void ItemSwimJumpSurfaceEnd(struct FPoseLink& ItemSwimJumpSurfaceEnd); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.ItemSwimJumpSurfaceLoop (Has no native function)
	void ItemSwimJumpSurfaceLoop(struct FPoseLink& ItemSwimJumpSurfaceLoop); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.ItemSwimJumpFallLoop (Has no native function)
	void ItemSwimJumpFallLoop(struct FPoseLink& ItemSwimJumpFallLoop); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.ItemSwimJumpStartLoop (Has no native function)
	void ItemSwimJumpStartLoop(struct FPoseLink& ItemSwimJumpStartLoop); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.ItemSwimJumpStart (Has no native function)
	void ItemSwimJumpStart(struct FPoseLink& ItemSwimJumpStart); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.ItemUpperBody (Has no native function)
	void ItemUpperBody(struct FPoseLink& InPoseUpperBody, struct FFortAnimInput_AdjustedAim& InputParam, struct FPoseLink& ItemUpperBody); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.ItemIdleAdditive (Has no native function)
	void ItemIdleAdditive(struct FPoseLink& InPoseIdleAdditive, struct FPoseLink& ItemIdleAdditive); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.ItemJumpUpAdditive (Has no native function)
	void ItemJumpUpAdditive(struct FPoseLink& ItemJumpUpAdditive); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.ItemJumpLoopAdditive (Has no native function)
	void ItemJumpLoopAdditive(struct FPoseLink& ItemJumpLoopAdditive); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.ItemFallAdditive (Has no native function)
	void ItemFallAdditive(struct FPoseLink& ItemFallAdditive); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.ItemFallLandAdditive (Has no native function)
	void ItemFallLandAdditive(struct FPoseLink& ItemFallLandAdditive); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.ItemJetPackStartAdditive (Has no native function)
	void ItemJetPackStartAdditive(struct FPoseLink& ItemJetPackStartAdditive); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.ItemJetPackJumpAdditive (Has no native function)
	void ItemJetPackJumpAdditive(struct FPoseLink& ItemJetPackJumpAdditive); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.ItemZipLineStartAdditive (Has no native function)
	void ItemZipLineStartAdditive(struct FPoseLink& ItemZipLineStartAdditive); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.ItemLowerBodyMovement (Has no native function)
	void ItemLowerBodyMovement(struct FPoseLink& InPoseLowerBodyMovement, struct FPoseLink& ItemLowerBodyMovement); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.ItemRelaxedEntry (Has no native function)
	void ItemRelaxedEntry(struct FPoseLink& InPoseRelaxedEntry, struct FPoseLink& ItemRelaxedEntry); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.VehicleFinalPoseOverride (Has no native function)
	void VehicleFinalPoseOverride(struct FPoseLink& InFinalPose, struct FPoseLink& VehicleFinalPoseOverride); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.VehicleSplitBodyOverride (Has no native function)
	void VehicleSplitBodyOverride(struct FPoseLink& InPoseSplitBody, struct FPoseLink& InPoseUpperAndLowerBody, struct FFortAnimInput_TurnInPlace& TurnInPlace, struct FPoseLink& InPoseUpperAndLowerBodyRemoveRoot, struct FPoseLink& VehicleSplitBodyOverride); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.VehicleFullBodyOverride (Has no native function)
	void VehicleFullBodyOverride(struct FPoseLink& InPoseFullBody, struct FPoseLink& VehicleFullBodyOverride); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.VehicleLowerBodyOverride (Has no native function)
	void VehicleLowerBodyOverride(struct FPoseLink& InPoseLowerBodyDefault, struct FPoseLink& InPoseUpperBody, struct FPoseLink& VehicleLowerBodyOverride); // (HasOutParms | BlueprintCallable)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.SourcePoseLayer (Has no native function)
	void SourcePoseLayer(struct FPoseLink& SourcePoseLayer); // (HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.UpperBodyAdjustmentsLayer (Has no native function)
	void UpperBodyAdjustmentsLayer(struct FPoseLink& InPoseUpperBodyAdjustments, struct FPoseLink& InPosePostUpperBodySlot, struct FPoseLink& UpperBodyAdjustmentsLayer); // (HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.FullBodySlotLayer (Has no native function)
	void FullBodySlotLayer(struct FPoseLink& InFullBodyPose, struct FPoseLink& FullBodySlotLayer); // (HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.DebugLayer (Has no native function)
	void DebugLayer(struct FPoseLink& InPoseDebug, struct FPoseLink& DebugLayer); // (HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.FacialCurvesLayer (Has no native function)
	void FacialCurvesLayer(struct FPoseLink& InPoseFacialCurves, struct FPoseLink& FacialCurvesLayer); // (HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.FullBodyAdditivesLayer (Has no native function)
	void FullBodyAdditivesLayer(struct FPoseLink& InPoseFullBodyAdditives, struct FPoseLink& FullBodyAdditivesLayer); // (HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.LocomotionLayer (Has no native function)
	void LocomotionLayer(struct FPoseLink& InSourcePoseLoco, struct FPoseLink& InSourcePosePreUpperBodySlot, struct FPoseLink& LocomotionLayer); // (HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.LowerBodyBlendLayer (Has no native function)
	void LowerBodyBlendLayer(struct FPoseLink& BasePose, struct FPoseLink& LowerBody, struct FPoseLink& LowerBodyBlendLayer); // (HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.SourcePoseAdjustmentsLayer (Has no native function)
	void SourcePoseAdjustmentsLayer(struct FPoseLink& InSourcePose, struct FPoseLink& SourcePoseAdjustmentsLayer); // (HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.UpperBodyAimingOffsetsLayer (Has no native function)
	void UpperBodyAimingOffsetsLayer(struct FPoseLink& InPose, struct FPoseLink& UpperBodyAimingOffsetsLayer); // (HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.AnimGraph (Has no native function)
	void AnimGraph(struct FPoseLink& AnimGraph); // (HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.AnimNotify_Melee_Swing_L (Has no native function)
	void AnimNotifyMeleeSwingL(); // (BlueprintCallable | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.AnimNotify_Melee_Swing_R (Has no native function)
	void AnimNotifyMeleeSwingR(); // (BlueprintCallable | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.AnimNotify_playFacialAnim (Has no native function)
	void AnimNotifyplayFacialAnim(); // (BlueprintCallable | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.AnimNotify_IndigoLaunch (Has no native function)
	void AnimNotifyIndigoLaunch(); // (BlueprintCallable | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.AnimNotify_Melee_Swing_L_End (Has no native function)
	void AnimNotifyMeleeSwingLEnd(); // (BlueprintCallable | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.AnimNotify_Melee_Swing_R_End (Has no native function)
	void AnimNotifyMeleeSwingREnd(); // (BlueprintCallable | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.AnimNotify_Melee_Swing_L_2 (Has no native function)
	void AnimNotifyMeleeSwingL2(); // (BlueprintCallable | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.AnimNotify_Melee_Swing_R_2 (Has no native function)
	void AnimNotifyMeleeSwingR2(); // (BlueprintCallable | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.AnimNotify_CreateToolFlyModeLoop_Entered (Has no native function)
	void AnimNotifyCreateToolFlyModeLoopEntered(); // (BlueprintCallable | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.AnimNotify_CreateToolFlyModeStart_Entered (Has no native function)
	void AnimNotifyCreateToolFlyModeStartEntered(); // (BlueprintCallable | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.AnimNotify_OpenGlider (Has no native function)
	void AnimNotifyOpenGlider(); // (BlueprintCallable | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.BlueprintProcessAnimInputEvent (Has no native function)
	void BlueprintProcessAnimInputEvent(class UFortAnimInputEvent*& AnimInputEvent); // (Event | Protected | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.ExecuteUbergraph_Fortnite_M_Avg_Player_AnimBlueprint (Has no native function)
	void ExecuteUbergraphFortniteMAvgPlayerAnimBlueprint(int& EntryPoint, class APawn*& CallFuncTryGetPawnOwnerReturnValue, class APawn*& CallFuncTryGetPawnOwnerReturnValue1, class AFortPawn*& K2NodeDynamicCastAsFortPawn, bool& K2NodeDynamicCastbSuccess, class AFortPawn*& K2NodeDynamicCastAsFortPawn1, bool& K2NodeDynamicCastbSuccess1, struct TScriptInterface<class IInterfacePlayerPawn_C>& K2NodeDynamicCastAsInterfacePlayerPawn, bool& K2NodeDynamicCastbSuccess2, struct TScriptInterface<class IInterfacePlayerPawn_C>& K2NodeDynamicCastAsInterfacePlayerPawn1, bool& K2NodeDynamicCastbSuccess3, class AGameStateBase*& CallFuncGetGameStateReturnValue, class AFortGameStateZone*& K2NodeDynamicCastAsFortGameStateZone, bool& K2NodeDynamicCastbSuccess4, class APawn*& CallFuncTryGetPawnOwnerReturnValue2, class APawn*& CallFuncTryGetPawnOwnerReturnValue3, class AFortPawn*& K2NodeDynamicCastAsFortPawn2, bool& K2NodeDynamicCastbSuccess5, class AFortPawn*& K2NodeDynamicCastAsFortPawn3, bool& K2NodeDynamicCastbSuccess6, struct TScriptInterface<class IInterfacePlayerPawn_C>& K2NodeDynamicCastAsInterfacePlayerPawn2, bool& K2NodeDynamicCastbSuccess7, struct TScriptInterface<class IInterfacePlayerPawn_C>& K2NodeDynamicCastAsInterfacePlayerPawn3, bool& K2NodeDynamicCastbSuccess8, class APawn*& CallFuncTryGetPawnOwnerReturnValue4, class APawn*& CallFuncTryGetPawnOwnerReturnValue5, class AFortPawn*& K2NodeDynamicCastAsFortPawn4, bool& K2NodeDynamicCastbSuccess9, class AFortPawn*& K2NodeDynamicCastAsFortPawn5, bool& K2NodeDynamicCastbSuccess10, struct TScriptInterface<class IInterfacePlayerPawn_C>& K2NodeDynamicCastAsInterfacePlayerPawn4, bool& K2NodeDynamicCastbSuccess11, struct TScriptInterface<class IInterfacePlayerPawn_C>& K2NodeDynamicCastAsInterfacePlayerPawn5, bool& K2NodeDynamicCastbSuccess12, class UFortAnimInputEvent*& K2NodeEventAnimInputEvent, class UFortAnimInputEvent_Bool*& K2NodeDynamicCastAsFortAnimInputEventBool, bool& K2NodeDynamicCastbSuccess13, bool& CallFuncIsNamedReturnValue, bool& CallFuncIsNamedReturnValue1); // (Final | 0x00008000)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.Indigo_Boost__DelegateSignature (Has no native function)
	void IndigoBoostDelegateSignature(); // (Public | Delegate | BlueprintCallable | BlueprintEvent)

	// Function /Game/Characters/Player/Male/Male_Avg_Base/Fortnite_M_Avg_Player_AnimBlueprint.Fortnite_M_Avg_Player_AnimBlueprint_C.MenuScreenDispatcher__DelegateSignature (Has no native function)
	void MenuScreenDispatcherDelegateSignature(class UFortPlayerAnimInstance*& CharPart); // (Public | Delegate | BlueprintCallable | BlueprintEvent)
};

