// Class /Script/FortniteGame.FortInputData
// Size: 0x950
class UFortInputData : public UPrimaryDataAsset
{
	struct FName ConfigDName; // 0x30 (0x4)
	struct FName ConfigEName; // 0x34 (0x4)
	struct FName ConfigFName; // 0x38 (0x4)
	struct FName ConfigGName; // 0x3c (0x4)
	struct FName ConfigDAthenaName; // 0x40 (0x4)
	struct FName ConfigEAthenaName; // 0x44 (0x4)
	struct FName ConfigFAthenaName; // 0x48 (0x4)
	struct FName ConfigGAthenaName; // 0x4c (0x4)
	struct FName ConfigHAthenaName; // 0x50 (0x4)
	struct FName ConfigCustomAthenaName; // 0x54 (0x4)
	struct FName GamepadAbility1Name; // 0x58 (0x4)
	struct FName GamepadAbility2Name; // 0x5c (0x4)
	struct FName GamepadAbility1AName; // 0x60 (0x4)
	struct FName GamepadAbility1BName; // 0x64 (0x4)
	struct FName GamepadAbility2AName; // 0x68 (0x4)
	struct FName GamepadAbility2BName; // 0x6c (0x4)
	struct FName GamepadAbility3AName; // 0x70 (0x4)
	struct FName GamepadAbility3BName; // 0x74 (0x4)
	struct FName GamepadPreviousBuildingName; // 0x78 (0x4)
	struct FName GamepadNextBuildingName; // 0x7c (0x4)
	struct FName GamepadBuildingSlot1Name; // 0x80 (0x4)
	struct FName GamepadBuildingSlot2Name; // 0x84 (0x4)
	struct FName GamepadBuildingSlot3Name; // 0x88 (0x4)
	struct FName GamepadBuildingSlot4Name; // 0x8c (0x4)
	struct FName GamepadToggleHarvestWeaponName; // 0x90 (0x4)
	struct FName GamepadToggleHarvestWeaponOrAltInteractName; // 0x94 (0x4)
	struct FName GamepadToggleCreativePhoneWeaponName; // 0x98 (0x4)
	struct FName GamepadToggleHarvestOrHoldCreativePhoneName; // 0x9c (0x4)
	struct FName GamepadSelectPreviousWeaponName; // 0xa0 (0x4)
	struct FName GamepadSelectNextWeaponName; // 0xa4 (0x4)
	struct FName GamepadQuickWeaponName; // 0xa8 (0x4)
	struct FName GamepadQuickWeapon1Name; // 0xac (0x4)
	struct FName GamepadQuickWeapon2Name; // 0xb0 (0x4)
	struct FName GamepadQuickWeapon3Name; // 0xb4 (0x4)
	struct FName GamepadQuickWeapon4Name; // 0xb8 (0x4)
	struct FName GamepadHoldToBuildName; // 0xbc (0x4)
	struct FName GamepadCreativeQuickbarSelectNextName; // 0xc0 (0x4)
	struct FName GamepadCreativeQuickbarSelectPreviousName; // 0xc4 (0x4)
	struct FName GamepadNextWeaponOrHarvestHoldName; // 0xc8 (0x4)
	struct FName GamepadNextWeaponOrAltInteractOrHarvestHoldName; // 0xcc (0x4)
	struct FName GamepadTapSelectPreviousWeaponForChordAbilities; // 0xd0 (0x4)
	struct FName GamepadTapSelectNextWeaponForChordAbilities; // 0xd4 (0x4)
	struct FName GamepadTrapPickerName; // 0xd8 (0x4)
	struct FName GamepadUseOrTrapPickerName; // 0xdc (0x4)
	struct FName GamepadUseOrTrapPickerAndPlaceName; // 0xe0 (0x4)
	struct FName GamepadChangeMaterialOrHarvestHoldName; // 0xe4 (0x4)
	struct FName GamepadSwitchModeOrEditBuildingName; // 0xe8 (0x4)
	struct FName GamepadImproveOrRotateBuildingPieceName; // 0xec (0x4)
	struct FName GamepadRepairHoldOrRotateBuildingPieceName; // 0xf0 (0x4)
	struct FName GamepadPerformBuildingEditInteractionOrCancelPersonalVehicleName; // 0xf4 (0x4)
	struct FName DBNOCarryHoistName; // 0xf8 (0x4)
	struct FName AlternateInteractCarryName; // 0xfc (0x4)
	struct FName HotbarKey1Name; // 0x100 (0x4)
	struct FName HotbarKey2Name; // 0x104 (0x4)
	struct FName HotbarKey3Name; // 0x108 (0x4)
	struct FName HotbarKey4Name; // 0x10c (0x4)
	struct FName HotbarKey5Name; // 0x110 (0x4)
	struct FName HotbarKey6Name; // 0x114 (0x4)
	struct FName HotbarKey7Name; // 0x118 (0x4)
	struct FName HotbarKey8Name; // 0x11c (0x4)
	struct FName HotbarKey9Name; // 0x120 (0x4)
	struct FName HotbarKey10Name; // 0x124 (0x4)
	struct FName HotbarKeyF1Name; // 0x128 (0x4)
	struct FName HotbarKeyF2Name; // 0x12c (0x4)
	struct FName HotbarKeyF3Name; // 0x130 (0x4)
	struct FName HotbarKeyF4Name; // 0x134 (0x4)
	struct FName HotbarKeyF5Name; // 0x138 (0x4)
	struct FName HotbarKeyF6Name; // 0x13c (0x4)
	struct FName HotbarKeyF7Name; // 0x140 (0x4)
	struct FName HotbarKeyF8Name; // 0x144 (0x4)
	struct FName HotbarKeyF9Name; // 0x148 (0x4)
	struct FName HotbarKeyF10Name; // 0x14c (0x4)
	struct FName HotbarKeyF11Name; // 0x150 (0x4)
	struct FName HotbarKeyF12Name; // 0x154 (0x4)
	struct FName CreativeQuickbarActivateClutchName; // 0x158 (0x4)
	struct FName CreativeQuickbarKey1Name; // 0x15c (0x4)
	struct FName CreativeQuickbarKey2Name; // 0x160 (0x4)
	struct FName CreativeQuickbarKey3Name; // 0x164 (0x4)
	struct FName CreativeQuickbarKey4Name; // 0x168 (0x4)
	struct FName CreativeQuickbarKey5Name; // 0x16c (0x4)
	struct FName CreativeQuickbarKey6Name; // 0x170 (0x4)
	struct FName CreativeQuickbarKey7Name; // 0x174 (0x4)
	struct FName CreativeQuickbarKey8Name; // 0x178 (0x4)
	struct FName TrapPickerName; // 0x17c (0x4)
	struct FName ChangeMaterialName; // 0x180 (0x4)
	struct FName BuildConfirmName; // 0x184 (0x4)
	struct FName PerformBuildingEditInteractionName; // 0x188 (0x4)
	struct FName PerformBuildingImprovementInteractionName; // 0x18c (0x4)
	struct FName PickerConfirmName; // 0x190 (0x4)
	struct FName EndOfZonePickerConfirmName; // 0x194 (0x4)
	struct FName PickerCancelName; // 0x198 (0x4)
	struct FName EmotePickerName; // 0x19c (0x4)
	struct FName SquadQuickChatPickerName; // 0x1a0 (0x4)
	struct FName SwitchQuickBarName; // 0x1a4 (0x4)
	struct FName UseName; // 0x1a8 (0x4)
	struct FName UseOrReloadName; // 0x1ac (0x4)
	struct FName ReloadName; // 0x1b0 (0x4)
	struct FName InventoryOrChatHoldName; // 0x1b4 (0x4)
	struct FName FireName; // 0x1b8 (0x4)
	struct FName TargetName; // 0x1bc (0x4)
	struct FName RotatePrimitiveClockwiseName; // 0x1c0 (0x4)
	struct FName ToggleFullScreenMapName; // 0x1c4 (0x4)
	struct FName GamepadToggleFullScreenMapName; // 0x1c8 (0x4)
	struct FName GamepadToggleFullScreenMapWhileBuildingName; // 0x1cc (0x4)
	struct FName GamepadToggleFullScreenMapWhileEditingName; // 0x1d0 (0x4)
	struct FName ToggleInventoryName; // 0x1d4 (0x4)
	struct FName GamepadToggleInventoryName; // 0x1d8 (0x4)
	struct FName GamepadToggleInventoryWhileBuildingName; // 0x1dc (0x4)
	struct FName GamepadToggleInventoryWhileEditingName; // 0x1e0 (0x4)
	struct FName JumpName; // 0x1e4 (0x4)
	struct FName GamepadJumpName; // 0x1e8 (0x4)
	struct FName CrouchName; // 0x1ec (0x4)
	struct FName CrouchWhileBuildingName; // 0x1f0 (0x4)
	struct FName CrouchWhileEditingName; // 0x1f4 (0x4)
	struct FName CrouchOrRepairName; // 0x1f8 (0x4)
	struct FName CrouchOrRepairWhileBuildingName; // 0x1fc (0x4)
	struct FName CrouchOrRepairWhileEditingName; // 0x200 (0x4)
	struct FName ToggleQuestVOMuteName; // 0x204 (0x4)
	struct FName QuickHealingName; // 0x208 (0x4)
	struct FName ShoppingCartCoastName; // 0x20c (0x4)
	struct FName CannonShootName; // 0x210 (0x4)
	struct FName GamepadCannonShootName; // 0x214 (0x4)
	struct FName CannonCoastName; // 0x218 (0x4)
	struct FName GamepadCannonCoastName; // 0x21c (0x4)
	struct FName GolfCartEBrakeName; // 0x220 (0x4)
	struct FName GamepadGolfCartEBrakeLeftName; // 0x224 (0x4)
	struct FName GamepadGolfCartEBrakeRightName; // 0x228 (0x4)
	struct FName GamepadGolfCartForwardName; // 0x22c (0x4)
	struct FName GamepadGolfCartReverseName; // 0x230 (0x4)
	struct FName GolfCartHonkName; // 0x234 (0x4)
	struct FName JackalBoostName; // 0x238 (0x4)
	struct FName JackalJumpName; // 0x23c (0x4)
	struct FName GamepadJackalJumpName; // 0x240 (0x4)
	struct FName GamepadJackalBoostLeftName; // 0x244 (0x4)
	struct FName GamepadJackalBoostRightName; // 0x248 (0x4)
	struct FName JackalUseOrExitName; // 0x24c (0x4)
	struct FName GamepadJackalExitName; // 0x250 (0x4)
	struct FName GamepadJackalUseOrExitName; // 0x254 (0x4)
	struct FName HamsterballBoostName; // 0x258 (0x4)
	struct FName HamsterballShootName; // 0x25c (0x4)
	struct FName HamsterballExtendName; // 0x260 (0x4)
	struct FName GamepadHamsterballBoostLeftName; // 0x264 (0x4)
	struct FName GamepadHamsterballBoostRightName; // 0x268 (0x4)
	struct FName GamepadHamsterballShootName; // 0x26c (0x4)
	struct FName GamepadHamsterballExtendName; // 0x270 (0x4)
	struct FName BiplanePitchForward; // 0x274 (0x4)
	struct FName BiplanePitchForwardSecondary; // 0x278 (0x4)
	struct FName BiplaneRollRightName; // 0x27c (0x4)
	struct FName BiplaneRollLeftName; // 0x280 (0x4)
	struct FName BiplaneRollInvertName; // 0x284 (0x4)
	struct FName BiplaneStartEngineName; // 0x288 (0x4)
	struct FName BiplaneStopEngineName; // 0x28c (0x4)
	struct FName BiplaneTaxiBackwardsName; // 0x290 (0x4)
	struct FName BiplaneBoostName; // 0x294 (0x4)
	struct FName BiplaneShootName; // 0x298 (0x4)
	struct FName BiplaneFreelookName; // 0x29c (0x4)
	struct FName GamepadBiplanePitchForward; // 0x2a0 (0x4)
	struct FName GamepadBiplaneRollRightName; // 0x2a4 (0x4)
	struct FName GamepadBiplaneRollLeftName; // 0x2a8 (0x4)
	struct FName GamepadBiplaneRollInvertName; // 0x2ac (0x4)
	struct FName GamepadBiplaneStartEngineName; // 0x2b0 (0x4)
	struct FName GamepadBiplaneStopEngineName; // 0x2b4 (0x4)
	struct FName GamepadBiplaneTaxiBackwardsName; // 0x2b8 (0x4)
	struct FName GamepadBiplaneBoostName; // 0x2bc (0x4)
	struct FName GamepadBiplaneShootName; // 0x2c0 (0x4)
	struct FName HoagieBoostName; // 0x2c4 (0x4)
	struct FName GamepadHoagieBoostName; // 0x2c8 (0x4)
	struct FName OstrichBoostName; // 0x2cc (0x4)
	struct FName GamepadOstrichBoostName; // 0x2d0 (0x4)
	struct FName OstrichJumpName; // 0x2d4 (0x4)
	struct FName GamepadOstrichJumpName; // 0x2d8 (0x4)
	struct FName OstrichPrimaryFireName; // 0x2dc (0x4)
	struct FName GamepadOstrichPrimaryFireName; // 0x2e0 (0x4)
	struct FName OstrichSecondaryFireName; // 0x2e4 (0x4)
	struct FName GamepadOstrichSecondaryFireName; // 0x2e8 (0x4)
	struct FName OstrichShieldBoostName; // 0x2ec (0x4)
	struct FName GamepadOstrichShieldBoostName; // 0x2f0 (0x4)
	struct FName OstrichSelfDestructName; // 0x2f4 (0x4)
	struct FName GamepadOstrichSelfDestructName; // 0x2f8 (0x4)
	struct FName TogglePickAxeName; // 0x2fc (0x4)
	struct FName GamepadResetCameraName; // 0x300 (0x4)
	struct FName GamepadTogglePickAxeHoldGyroName; // 0x304 (0x4)
	struct FName GamepadToggleCrouchHoldGyroName; // 0x308 (0x4)
	struct FName GamepadGyroModifierName; // 0x30c (0x4)
	struct FName GamepadResetCameraHoldGyroName; // 0x310 (0x4)
	struct FName ToggleCreativePhoneName; // 0x314 (0x4)
	struct FName ToggleQuickMenuName; // 0x318 (0x4)
	struct FName GamepadSquadQuickChatPickerName; // 0x31c (0x4)
	struct FName GamepadEmotePickerOrReplayLastEmoteHoldName; // 0x320 (0x4)
	struct FName GamepadEmotePickerOrReplayLastEmoteHoldWhileBuildingName; // 0x324 (0x4)
	struct FName GamepadEmotePickerOrReplayLastEmoteHoldWhileEditingName; // 0x328 (0x4)
	struct FName GamepadChatPickerName; // 0x32c (0x4)
	struct FName GamepadSwitchModeName; // 0x330 (0x4)
	struct FName CreativeMoveToolEquippedGrabOrLetGoName; // 0x334 (0x4)
	struct FName CreativeMoveToolEquippedCopyGrabOrDuplicateName; // 0x338 (0x4)
	struct FName CreativePossessPropActivateName; // 0x33c (0x4)
	struct FName CreativeMoveToolEquippedDeleteName; // 0x340 (0x4)
	struct FName CreativeToggleGhostName; // 0x344 (0x4)
	struct FName CreativeToggleInvulnerablityName; // 0x348 (0x4)
	struct FName CreativeToggleHeatmapName; // 0x34c (0x4)
	struct FName CreativeMoveToolMultiSelectName; // 0x350 (0x4)
	struct FName CreativeMoveToolClearMultiSelectName; // 0x354 (0x4)
	struct FName CreativeMoveObjectsFreelyLetGoName; // 0x358 (0x4)
	struct FName CreativeMoveObjectsFreelyDuplicateName; // 0x35c (0x4)
	struct FName CreativeMoveObjectsFreelyDropToFloorName; // 0x360 (0x4)
	struct FName CreativeMoveObjectsFreelyRotateClockwiseName; // 0x364 (0x4)
	struct FName CreativeMoveObjectsFreelyRotateCounterclockwiseName; // 0x368 (0x4)
	struct FName CreativeMoveObjectsFreelySwitchAxisName; // 0x36c (0x4)
	struct FName CreativeMoveObjectsFreelyPushName; // 0x370 (0x4)
	struct FName CreativeMoveObjectsFreelyPullName; // 0x374 (0x4)
	struct FName CreativeMoveObjectsFreelyExitName; // 0x378 (0x4)
	struct FName CreativeMoveObjectsFreelyChangePrecisionLevelName; // 0x37c (0x4)
	struct FName CreativeMoveBuildingsOnGridLetGoName; // 0x380 (0x4)
	struct FName CreativeMoveBuildingsOnGridDuplicateName; // 0x384 (0x4)
	struct FName CreativeMoveBuildingsOnGridRotateClockwiseName; // 0x388 (0x4)
	struct FName CreativeMoveBuildingsOnGridRotateCounterclockwiseName; // 0x38c (0x4)
	struct FName CreativeMoveBuildingsOnGridMirrorName; // 0x390 (0x4)
	struct FName CreativeMoveBuildingsOnGridExitName; // 0x394 (0x4)
	struct FName CreativeMoveBuildingsOnGridChangePrecisionLevelName; // 0x398 (0x4)
	struct FName CreativeFlyUpName; // 0x39c (0x4)
	struct FName CreativeFlyDownName; // 0x3a0 (0x4)
	struct FName CreativeIslandPanelSupportAffiliateName; // 0x3a4 (0x4)
	struct FName CreativeIslandPanelStartMinigameName; // 0x3a8 (0x4)
	struct FName CreativeIslandPanelToggleDetailsName; // 0x3ac (0x4)
	struct TMap<struct FGameplayTag, struct FScreenLabelText> ScreenLabels; // 0x3b0 (0x50)
	struct FText MoveLabel; // 0x400 (0x18)
	struct FText LookLabel; // 0x418 (0x18)
	struct FText SwitchQuickbarLabel; // 0x430 (0x18)
	struct FText JumpLabel; // 0x448 (0x18)
	struct FText SprintLabel; // 0x460 (0x18)
	struct FText AutoSprintLabel; // 0x478 (0x18)
	struct FText NextWeaponLabel; // 0x490 (0x18)
	struct FText PreviousWeaponLabel; // 0x4a8 (0x18)
	struct FText NextWeaponTapLabel; // 0x4c0 (0x18)
	struct FText PreviousWeaponTapLabel; // 0x4d8 (0x18)
	struct FText NextBuildingPieceLabel; // 0x4f0 (0x18)
	struct FText PreviousBuildingPieceLabel; // 0x508 (0x18)
	struct FText GamepadStairSelectAndPlaceLabel; // 0x520 (0x18)
	struct FText GamepadRoofSelectAndPlaceLabel; // 0x538 (0x18)
	struct FText GamepadWallSelectAndPlaceLabel; // 0x550 (0x18)
	struct FText GamepadFloorSelectAndPlaceLabel; // 0x568 (0x18)
	struct FText GamepadTrapSelectAndPlaceLabel; // 0x580 (0x18)
	struct FText GamepadTrapPickerHoldLabel; // 0x598 (0x18)
	struct FText GamepadChangeMaterialOrTrapPickerLabel; // 0x5b0 (0x18)
	struct FText HarvestWeaponHoldLabel; // 0x5c8 (0x18)
	struct FText HarvestWeaponLabel; // 0x5e0 (0x18)
	struct FText AimDownSightsLabel; // 0x5f8 (0x18)
	struct FText AimDownSightsHeavyMeleeLabel; // 0x610 (0x18)
	struct FText Ability1Label; // 0x628 (0x18)
	struct FText Ability2Label; // 0x640 (0x18)
	struct FText Ability3Label; // 0x658 (0x18)
	struct FText Gadget1Label; // 0x670 (0x18)
	struct FText Gadget2Label; // 0x688 (0x18)
	struct FText RotateBuildingLabel; // 0x6a0 (0x18)
	struct FText RotateBuildingTapRepairHoldLabel; // 0x6b8 (0x18)
	struct FText BuildingEditResetLabel; // 0x6d0 (0x18)
	struct FText ReloadLabel; // 0x6e8 (0x18)
	struct FText ReloadTapLabel; // 0x700 (0x18)
	struct FText CraftAmmoHoldLabel; // 0x718 (0x18)
	struct FText InteractTapHoldLabel; // 0x730 (0x18)
	struct FText UseOrReloadLabel; // 0x748 (0x18)
	struct FText CrouchLabel; // 0x760 (0x18)
	struct FText ToggleFullScreenMapLabel; // 0x778 (0x18)
	struct FText ToggleInventoryLabel; // 0x790 (0x18)
	struct FText GameMenuLabel; // 0x7a8 (0x18)
	struct FText PlaceBuildingOrTrapConfirmLabel; // 0x7c0 (0x18)
	struct FText AttackConfirmLabel; // 0x7d8 (0x18)
	struct FText ChangeMaterialLabel; // 0x7f0 (0x18)
	struct FText EmoteLabel; // 0x808 (0x18)
	struct FText EmoteOrQuickChatOrSpotEnemyLabel; // 0x820 (0x18)
	struct FText ChatHoldLabel; // 0x838 (0x18)
	struct FText PickTrapTapLabel; // 0x850 (0x18)
	struct FText TrapInventoryHoldLabel; // 0x868 (0x18)
	struct FText PickTrapTapHoldLabel; // 0x880 (0x18)
	struct FText PickTrapLabel; // 0x898 (0x18)
	struct FText EditBuildingPieceHoldLabel; // 0x8b0 (0x18)
	struct FText SwitchQuickBarTapLabel; // 0x8c8 (0x18)
	struct FText DeployHoverboardLabel; // 0x8e0 (0x18)
	struct FText RepairOrImproveLabel; // 0x8f8 (0x18)
	struct FText RepairLabel; // 0x910 (0x18)
	struct FText RepairHoldLabel; // 0x928 (0x18)
	struct TArray<struct FFortActionKeyMapping> InputOptionsList; // 0x940 (0x10)

	/* Functions */

	// Function /Script/FortniteGame.FortInputData.GetUseOrReloadLabel (Underlying native function: GetUseOrReloadLabel 0x8a07b08)
	struct FText GetUseOrReloadLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetTrapInventoryHoldLabel (Underlying native function: GetTrapInventoryHoldLabel 0x8a07a94)
	struct FText GetTrapInventoryHoldLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetToggleInventoryLabel (Underlying native function: GetToggleInventoryLabel 0x8a07a20)
	struct FText GetToggleInventoryLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetToggleFullScreenMapLabel (Underlying native function: GetToggleFullScreenMapLabel 0x8a079ac)
	struct FText GetToggleFullScreenMapLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetSwitchQuickBarTapLabel (Underlying native function: GetSwitchQuickBarTapLabel 0x8a078c4)
	struct FText GetSwitchQuickBarTapLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetSwitchQuickbarLabel (Underlying native function: GetSwitchQuickbarLabel 0x8a07938)
	struct FText GetSwitchQuickbarLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetSprintLabel (Underlying native function: GetSprintLabel 0x8a07850)
	struct FText GetSprintLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetScreenLabel (Underlying native function: GetScreenLabel 0x8a07640)
	struct FText GetScreenLabel(struct FName& PresetName, enum EFortInputActionGroup& InputActionGroup, struct FName& ActionName, bool& bRichText); // (Final | 0x00000002 | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetRotateBuildingTapRepairHoldLabel (Underlying native function: GetRotateBuildingTapRepairHoldLabel 0x8a075cc)
	struct FText GetRotateBuildingTapRepairHoldLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetRotateBuildingLabel (Underlying native function: GetRotateBuildingLabel 0x8a07558)
	struct FText GetRotateBuildingLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetRepairOrImproveLabel (Underlying native function: GetRepairOrImproveLabel 0x8a074e4)
	struct FText GetRepairOrImproveLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetRepairLabel (Underlying native function: GetRepairLabel 0x8a07470)
	struct FText GetRepairLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetRepairHoldLabel (Underlying native function: GetRepairHoldLabel 0x8a073fc)
	struct FText GetRepairHoldLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetReloadTapLabel (Underlying native function: GetReloadTapLabel 0x8a07388)
	struct FText GetReloadTapLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetReloadLabel (Underlying native function: GetReloadLabel 0x8a07314)
	struct FText GetReloadLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetPreviousWeaponTapLabel (Underlying native function: GetPreviousWeaponTapLabel 0x8a072a0)
	struct FText GetPreviousWeaponTapLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetPreviousWeaponLabel (Underlying native function: GetPreviousWeaponLabel 0x8a0722c)
	struct FText GetPreviousWeaponLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetPreviousBuildingPieceLabel (Underlying native function: GetPreviousBuildingPieceLabel 0x8a071b8)
	struct FText GetPreviousBuildingPieceLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetPlaceBuildingOrTrapConfirmLabel (Underlying native function: GetPlaceBuildingOrTrapConfirmLabel 0x8a06ff0)
	struct FText GetPlaceBuildingOrTrapConfirmLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetPickTrapTapLabel (Underlying native function: GetPickTrapTapLabel 0x8a06f7c)
	struct FText GetPickTrapTapLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetPickTrapTapHoldLabel (Underlying native function: GetPickTrapTapHoldLabel 0x8a06f08)
	struct FText GetPickTrapTapHoldLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetPickTrapLabel (Underlying native function: GetPickTrapLabel 0x8a06e94)
	struct FText GetPickTrapLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetNextWeaponTapLabel (Underlying native function: GetNextWeaponTapLabel 0x8a06d0c)
	struct FText GetNextWeaponTapLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetNextWeaponLabel (Underlying native function: GetNextWeaponLabel 0x8a06c98)
	struct FText GetNextWeaponLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetNextBuildingPieceLabel (Underlying native function: GetNextBuildingPieceLabel 0x8a06c24)
	struct FText GetNextBuildingPieceLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetMoveLabel (Underlying native function: GetMoveLabel 0x8a06bb0)
	struct FText GetMoveLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure)

	// Function /Script/FortniteGame.FortInputData.GetLookLabel (Underlying native function: GetLookLabel 0x8a06b3c)
	struct FText GetLookLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetJumpLabel (Underlying native function: GetJumpLabel 0x8a06ac8)
	struct FText GetJumpLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetInteractTapHoldLabel (Underlying native function: GetInteractTapHoldLabel 0x8a06a54)
	struct FText GetInteractTapHoldLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetHarvestWeaponLabel (Underlying native function: GetHarvestWeaponLabel 0x8a069bc)
	struct FText GetHarvestWeaponLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetHarvestWeaponHoldLabel (Underlying native function: GetHarvestWeaponHoldLabel 0x8a06948)
	struct FText GetHarvestWeaponHoldLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetGamepadWallSelectAndPlaceLabel (Underlying native function: GetGamepadWallSelectAndPlaceLabel 0x8a068bc)
	struct FText GetGamepadWallSelectAndPlaceLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetGamepadTrapSelectAndPlaceLabel (Underlying native function: GetGamepadTrapSelectAndPlaceLabel 0x8a06848)
	struct FText GetGamepadTrapSelectAndPlaceLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetGamepadTrapPickerHoldLabel (Underlying native function: GetGamepadTrapPickerHoldLabel 0x8a067d4)
	struct FText GetGamepadTrapPickerHoldLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetGamepadStairSelectAndPlaceLabel (Underlying native function: GetGamepadStairSelectAndPlaceLabel 0x8a06760)
	struct FText GetGamepadStairSelectAndPlaceLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetGamepadRoofSelectAndPlaceLabel (Underlying native function: GetGamepadRoofSelectAndPlaceLabel 0x8a066ec)
	struct FText GetGamepadRoofSelectAndPlaceLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetGamepadFloorSelectAndPlaceLabel (Underlying native function: GetGamepadFloorSelectAndPlaceLabel 0x8a06678)
	struct FText GetGamepadFloorSelectAndPlaceLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetGamepadChangeMaterialOrTrapPickerLabel (Underlying native function: GetGamepadChangeMaterialOrTrapPickerLabel 0x8a06604)
	struct FText GetGamepadChangeMaterialOrTrapPickerLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetGameMenuLabel (Underlying native function: GetGameMenuLabel 0x8a06590)
	struct FText GetGameMenuLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetGadget2Label (Underlying native function: GetGadget2Label 0x8a0651c)
	struct FText GetGadget2Label(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetGadget1Label (Underlying native function: GetGadget1Label 0x8a064a8)
	struct FText GetGadget1Label(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetFortInputDataForBlueprint (Underlying native function: GetFortInputDataForBlueprint 0x8a063ec)
	static class UFortInputData* GetFortInputDataForBlueprint(); // (Final | Native | Static | Public | BlueprintCallable | BlueprintPure)

	// Function /Script/FortniteGame.FortInputData.GetEmoteOrQuickChatOrSpotEnemyLabel (Underlying native function: GetEmoteOrQuickChatOrSpotEnemyLabel 0x8a06378)
	struct FText GetEmoteOrQuickChatOrSpotEnemyLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetEmoteLabel (Underlying native function: GetEmoteLabel 0x8a06304)
	struct FText GetEmoteLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetEditBuildingPieceHoldLabel (Underlying native function: GetEditBuildingPieceHoldLabel 0x8a06290)
	struct FText GetEditBuildingPieceHoldLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetDeployHoverboardLabel (Underlying native function: GetDeployHoverboardLabel 0x8a0621c)
	struct FText GetDeployHoverboardLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetCrouchLabel (Underlying native function: GetCrouchLabel 0x8a061a8)
	struct FText GetCrouchLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetCraftAmmoHoldLabel (Underlying native function: GetCraftAmmoHoldLabel 0x8a06134)
	struct FText GetCraftAmmoHoldLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetChatHoldLabel (Underlying native function: GetChatHoldLabel 0x8a06054)
	struct FText GetChatHoldLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetChangeMaterialLabel (Underlying native function: GetChangeMaterialLabel 0x8a05fe0)
	struct FText GetChangeMaterialLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetBuildingEditResetLabel (Underlying native function: GetBuildingEditResetLabel 0x8a05f6c)
	struct FText GetBuildingEditResetLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetAutoSprintLabel (Underlying native function: GetAutoSprintLabel 0x8a05ef8)
	struct FText GetAutoSprintLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetAttackConfirmLabel (Underlying native function: GetAttackConfirmLabel 0x8a05e84)
	struct FText GetAttackConfirmLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetAimDownSightsLabel (Underlying native function: GetAimDownSightsLabel 0x8a05e10)
	struct FText GetAimDownSightsLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetAimDownSightsHeavyMeleeLabel (Underlying native function: GetAimDownSightsHeavyMeleeLabel 0x8a05d9c)
	struct FText GetAimDownSightsHeavyMeleeLabel(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetAbility3Label (Underlying native function: GetAbility3Label 0x8a05d08)
	struct FText GetAbility3Label(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetAbility2Label (Underlying native function: GetAbility2Label 0x8a05c94)
	struct FText GetAbility2Label(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortInputData.GetAbility1Label (Underlying native function: GetAbility1Label 0x8a05c20)
	struct FText GetAbility1Label(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)
};

