// Class /Script/FortniteGame.FortGameUserSettings
// Size: 0xb98
class UFortGameUserSettings : public UGameUserSettings
{
	float MouseSensitivity; // 0x148 (0x4)
	int FortniteReleaseVersion; // 0x14c (0x4)
	unsigned char unreflected_150[0x18]; // 0x150 (0x18) 
	bool UnlockConsoleFPS; // 0x168 (0x1)
	bool LastAppliedUnlockConsoleFPS; // 0x169 (0x1)
	unsigned char unreflected_16a[0x6]; // 0x16a (0x6) 
	struct FString CurrentFpsModeString; // 0x170 (0x10)
	struct FString CurrentDeviceProfileOverrideSuffix; // 0x180 (0x10)
	int SubGameSelectCountAthena; // 0x190 (0x4)
	unsigned char unreflected_194[0x4]; // 0x194 (0x4) 
	struct FDateTime* SubGameLastSelectedTimeAthena; // 0x198 (0x8)
	int SubGameSelectCountCampaign; // 0x1a0 (0x4)
	unsigned char unreflected_1a4[0x4]; // 0x1a4 (0x4) 
	struct FDateTime* SubGameLastSelectedTimeCampaign; // 0x1a8 (0x8)
	struct FDateTime* LastTimeSettingsSnapshotUploaded; // 0x1b0 (0x8)
	struct FDateTime* FirstLoginOnDevice; // 0x1b8 (0x8)
	float SafeZone; // 0x1c0 (0x4)
	bool bIsSafeZoneSet; // 0x1c4 (0x1)
	unsigned char unreflected_1c5[0x3]; // 0x1c5 (0x3) 
	int CachedPlayerLevel; // 0x1c8 (0x4)
	bool bShowActorsWithSeasonItemTagMapIndicators; // 0x1cc (0x1)
	unsigned char unreflected_1cd[0x3]; // 0x1cd (0x3) 
	int CachedBattleStars; // 0x1d0 (0x4)
	int CachedAlienStylePoints; // 0x1d4 (0x4)
	int CachedStylePoints; // 0x1d8 (0x4)
	unsigned char unreflected_1dc[0x4]; // 0x1dc (0x4) 
	struct TMap<struct FString, int> CachedClaimableRewards; // 0x1e0 (0x50)
	int CachedHighestBattlePassUnlockedPage; // 0x230 (0x4)
	bool bShowCareerTabBang; // 0x234 (0x1)
	unsigned char unreflected_235[0x3]; // 0x235 (0x3) 
	struct FString CustomVoiceChatInputDevice; // 0x238 (0x10)
	struct FString CustomVoiceChatOutputDevice; // 0x248 (0x10)
	struct FString CustomVoiceChatInputDeviceId; // 0x258 (0x10)
	struct FString CustomVoiceChatOutputDeviceId; // 0x268 (0x10)
	bool bMotionBlur; // 0x278 (0x1)
	bool bShowGrass; // 0x279 (0x1)
	bool bShowFPS; // 0x27a (0x1)
	bool bUseGPUCrashDebugging; // 0x27b (0x1)
	unsigned char unreflected_27c[0x2]; // 0x27c (0x2) 
	bool bUserRenderingAPIWasMigratedThisSession; // 0x27e (0x1)
	bool bLatencyTweak1; // 0x27f (0x1)
	int LatencyTweak2; // 0x280 (0x4)
	bool bLatencyFlash; // 0x284 (0x1)
	enum EFortAntiAliasingMethod FortAntiAliasingMethod; // 0x285 (0x1)
	enum EFortTemporalSuperResolutionSetting TemporalSuperResolutionQuality; // 0x286 (0x1)
	unsigned char unreflected_287[0x1]; // 0x287 (0x1) 
	int DLSSQuality; // 0x288 (0x4)
	bool bUseNanite; // 0x28c (0x1)
	unsigned char unreflected_28d[0x3]; // 0x28d (0x3) 
	int DesiredGlobalIlluminationQuality; // 0x290 (0x4)
	int DesiredReflectionQuality; // 0x294 (0x4)
	int PreNaniteGlobalIlluminationQuality; // 0x298 (0x4)
	int PreNaniteReflectionQuality; // 0x29c (0x4)
	bool bRayTracing; // 0x2a0 (0x1)
	bool b120FpsMode; // 0x2a1 (0x1)
	unsigned char unreflected_2a2[0x2]; // 0x2a2 (0x2) 
	int FrontendFrameRateLimit; // 0x2a4 (0x4)
	float DisplayGamma; // 0x2a8 (0x4)
	unsigned char unreflected_2ac[0x4]; // 0x2ac (0x4) 
	float UserInterfaceContrast; // 0x2b0 (0x4)
	unsigned char unreflected_2b4[0x4]; // 0x2b4 (0x4) 
	struct TMap<struct FName, struct FDateTime*> NamedTimes; // 0x2b8 (0x50)
	struct TMap<struct FName, int> NamedCounts; // 0x308 (0x50)
	int BattlePassOverrideTracker; // 0x358 (0x4)
	unsigned char unreflected_35c[0x4]; // 0x35c (0x4) 
	struct FString NewestProgressiveCosmeticSetSeen; // 0x360 (0x10)
	struct TMap<enum EAthenaCustomizationCategory, enum EInventoryContentSortType> CurrentLockerSorts; // 0x370 (0x50)
	bool bHasUsedBattlePassCrewUpsellNavButton; // 0x3c0 (0x1)
	bool bHasSeenLockerArchivingCleanupTooltip; // 0x3c1 (0x1)
	bool bHasSeenGeneralArchiveModeTooltip; // 0x3c2 (0x1)
	bool bHasSeenEmotesArchiveModeTooltip; // 0x3c3 (0x1)
	bool bHasSeenArchiveFilterTooltip; // 0x3c4 (0x1)
	bool bHasSeenArchivedItemsTooltip; // 0x3c5 (0x1)
	bool bHasSeenDonutShopSequence; // 0x3c6 (0x1)
	unsigned char unreflected_3c7[0x1]; // 0x3c7 (0x1) 
	float DonutIdleGameHighScore; // 0x3c8 (0x4)
	unsigned char unreflected_3cc[0x4]; // 0x3cc (0x4) 
	struct TMap<struct FString, enum EFortOfferSeenLevel> DisplayAssetPathToOfferSeenLevel; // 0x3d0 (0x50)
	struct TMap<struct FName, struct FDateTime*> ItemShopSectionsSeenStateLastResetDates; // 0x420 (0x50)
	struct FPlaylistData LastSelectedPlaylist; // 0x470 (0x58)
	bool LastSelectedFillOption; // 0x4c8 (0x1)
	bool bLastSelectedPrivateMatchOption; // 0x4c9 (0x1)
	unsigned char unreflected_4ca[0x6]; // 0x4ca (0x6) 
	struct TMap<struct FName, struct FSavedCustomMatchOptions> CustomMatchOptions; // 0x4d0 (0x50)
	struct TMap<struct FName, int> CreativeOptions; // 0x520 (0x50)
	bool bHasSeenCreativePhoneTutorial; // 0x570 (0x1)
	bool bHasSeenCreativeHeatmapTutorial; // 0x571 (0x1)
	unsigned char unreflected_572[0x2]; // 0x572 (0x2) 
	int CreativeOptionLastUsedCategory; // 0x574 (0x4)
	int CreativeOptionLastUsedIndexInCategory; // 0x578 (0x4)
	unsigned char unreflected_57c[0x24]; // 0x57c (0x24) 
	struct TMap<struct FString, struct FString> LastSelectedChildActivityMap; // 0x5a0 (0x50)
	struct FString LastNewsVersionViewedBR; // 0x5f0 (0x10)
	struct FString LastNewsVersionViewedCreative; // 0x600 (0x10)
	struct FString LastNewsVersionViewedSTW; // 0x610 (0x10)
	struct FString LastPRMEtag; // 0x620 (0x10)
	struct FString LastPlaylistInfoVersionViewedBR; // 0x630 (0x10)
	struct FString LastFrontEndBackPlateStageUsed[0x2]; // 0x640 (0x10) (ARRAY) 
	bool bEulaAccepted; // 0x660 (0x1)
	unsigned char unreflected_661[0x7]; // 0x661 (0x7) 
	struct FString EulaAcceptedUserId; // 0x668 (0x10)
	struct FDateTime* LastEulaCheckTime; // 0x678 (0x8)
	struct FHUDLayoutData HUDLayoutData[0x3]; // 0x680 (0x10) (ARRAY) 
	struct FFortMobileHUDProfileIdentifier ActiveHUDProfileIdentifier; // 0x6b0 (0x14)
	int bTimesSeenBacchusLoadTutorial; // 0x6c4 (0x4)
	bool bHasSeenTapToShoot; // 0x6c8 (0x1)
	unsigned char unreflected_6c9[0x3]; // 0x6c9 (0x3) 
	int NumTimesSeeingPanningTip; // 0x6cc (0x4)
	struct FFireModeData FireModeData; // 0x6d0 (0x5)
	unsigned char unreflected_6d5[0x3]; // 0x6d5 (0x3) 
	struct FFortSimpleGameStats SimpleMobileStats; // 0x6d8 (0x20)
	bool bDesiredHeadphoneMode; // 0x6f8 (0x1)
	unsigned char unreflected_6f9[0x7]; // 0x6f9 (0x7) 
	struct FString AudioOutputDeviceId; // 0x700 (0x10)
	bool bUseHeadphoneMode; // 0x710 (0x1)
	unsigned char unreflected_711[0x3]; // 0x711 (0x3) 
	int InitialBenchmarkState; // 0x714 (0x4)
	bool bDisableMouseAcceleration; // 0x718 (0x1)
	enum ESavedAccountType ChosenLoginType; // 0x719 (0x1)
	unsigned char unreflected_71a[0x6]; // 0x71a (0x6) 
	struct FMulticastInlineDelegate OnViewDistanceQualityChanged; // 0x720 (0x10)
	struct FMulticastInlineDelegate OnShadowQualityChanged; // 0x730 (0x10)
	struct FMulticastInlineDelegate OnGlobalIlluminationQualityChanged; // 0x740 (0x10)
	struct FMulticastInlineDelegate OnReflectionQualityChanged; // 0x750 (0x10)
	struct FMulticastInlineDelegate OnAntiAliasingQualityChanged; // 0x760 (0x10)
	struct FMulticastInlineDelegate OnTextureQualityChanged; // 0x770 (0x10)
	struct FMulticastInlineDelegate OnEffectsQualityChanged; // 0x780 (0x10)
	struct FMulticastInlineDelegate OnPostProcessQualityChanged; // 0x790 (0x10)
	unsigned char unreflected_7a0[0x70]; // 0x7a0 (0x70) 
	struct TArray<struct FSavedCredentials> Credentials; // 0x810 (0x10)
	int SocialImportOptedOutVersion; // 0x820 (0x4)
	int VKImportOptedOutVersion; // 0x824 (0x4)
	bool bHasSeenErebusSocialImport; // 0x828 (0x1)
	bool bHasSeenFriendImportToast; // 0x829 (0x1)
	unsigned char unreflected_82a[0x6]; // 0x82a (0x6) 
	struct FDateTime* LastSocialImportPromptTime; // 0x830 (0x8)
	bool bAutoImportFriendEnabled; // 0x838 (0x1)
	bool bSeenLetoSellModal; // 0x839 (0x1)
	unsigned char unreflected_83a[0x2]; // 0x83a (0x2) 
	int SocialImportPromptCountCurrentVersion; // 0x83c (0x4)
	int SocialImportPromptCountAllVersions; // 0x840 (0x4)
	int VKImportPromptCountCurrentVersion; // 0x844 (0x4)
	int VKImportPromptCountAllVersions; // 0x848 (0x4)
	bool bSocialImportDisplayed; // 0x84c (0x1)
	bool bAccountItemWarningShownThisLaunch; // 0x84d (0x1)
	unsigned char unreflected_84e[0x2]; // 0x84e (0x2) 
	struct FDateTime* LastAccountItemWarningTime; // 0x850 (0x8)
	bool bMultiFactorAuthModalOpOut; // 0x858 (0x1)
	unsigned char unreflected_859[0x7]; // 0x859 (0x7) 
	struct FDateTime* LastEnableMFAModalPromptTime; // 0x860 (0x8)
	struct FDateTime* LastVKImportPromptTime; // 0x868 (0x8)
	struct FDateTime* LastAffiliateToastTime; // 0x870 (0x8)
	struct TMap<struct FString, struct FDateTime*> FailedInviteMap; // 0x878 (0x50)
	int MobileRecommendationDismissedVersion; // 0x8c8 (0x4)
	enum EShowInGamePictureInPicture ShowLiveStreamPictureInPictureInMatchV2; // 0x8cc (0x1)
	unsigned char unreflected_8cd[0x3]; // 0x8cd (0x3) 
	int64_t CurrentLivePiPStreamOverrideCounter; // 0x8d0 (0x8)
	struct FString SelectedFrontEnd; // 0x8d8 (0x10)
	bool bNeverShowMobileLink; // 0x8e8 (0x1)
	bool bHasShownMobileLink; // 0x8e9 (0x1)
	unsigned char unreflected_8ea[0x1]; // 0x8ea (0x1) 
	bool bDesiredAllowLowPowerMode; // 0x8eb (0x1)
	unsigned char unreflected_8ec[0x4]; // 0x8ec (0x4) 
	struct FMulticastInlineDelegate OnAllowVideoPlaybackChanged; // 0x8f0 (0x10)
	bool bHasMigratedDownloadSettings; // 0x900 (0x1)
	bool bSendAppsFlyerEventOnInstallation; // 0x901 (0x1)
	bool bAllowFullGameDownload; // 0x902 (0x1)
	bool bAllowFullGameDownloadOverride; // 0x903 (0x1)
	bool bAllowElectraPlayerDownload; // 0x904 (0x1)
	bool bAllowElectraPlayerDownloadOverride; // 0x905 (0x1)
	bool bAllowCellularDownload; // 0x906 (0x1)
	unsigned char unreflected_907[0x19]; // 0x907 (0x19) 
	enum EFortAllowDownloadHighResMipsBehavior AutoDownloadHighResTexturesBehavior; // 0x920 (0x1)
	unsigned char unreflected_921[0x1f]; // 0x921 (0x1f) 
	int64_t LastAutoDownloadHighResTextureReminder; // 0x940 (0x8)
	bool bResumeUserCanceledOrPausedDownload; // 0x948 (0x1)
	bool bForceNoPatchingForDownloads; // 0x949 (0x1)
	bool bAutoLaunchFullGame; // 0x94a (0x1)
	bool bAllowDownloadHighResMips; // 0x94b (0x1)
	enum EFortContentQualityLevel ContentQualityLevelSelected; // 0x94c (0x1)
	unsigned char unreflected_94d[0x53]; // 0x94d (0x53) 
	bool bAllowLowPowerMode; // 0x9a0 (0x1)
	bool bAllowVideoPlayback; // 0x9a1 (0x1)
	enum EFortMobileFPSMode MobileFPSMode; // 0x9a2 (0x1)
	unsigned char unreflected_9a3[0x12d]; // 0x9a3 (0x12d) 
	struct FString MobileQualitySettingsResetDefaultsGUID; // 0xad0 (0x10)
	bool bHasSeenSamsungPressureSensorWarning; // 0xae0 (0x1)
	bool bNeverDisplaySamsungPressureSensorWarning; // 0xae1 (0x1)
	bool bHasRecentlySeenBadMatchPopup; // 0xae2 (0x1)
	unsigned char unreflected_ae3[0x1]; // 0xae3 (0x1) 
	int MatchesSinceLastBadMatchPopup; // 0xae4 (0x4)
	bool bHasAlreadyRatedOnGooglePlay; // 0xae8 (0x1)
	unsigned char unreflected_ae9[0x3]; // 0xae9 (0x3) 
	int DaysToSnoozeBeforeNextGooglePlayRating; // 0xaec (0x4)
	int GooglePlayRatingDelayedOccurences; // 0xaf0 (0x4)
	bool bShowTemperature; // 0xaf4 (0x1)
	unsigned char unreflected_af5[0x3]; // 0xaf5 (0x3) 
	struct FDateTime* LastGameStartNotificationSentTime; // 0xaf8 (0x8)
	struct TArray<int> ScheduledNotifications; // 0xb00 (0x10)
	int LastYearForcedDisplayWinterfestInfoButton; // 0xb10 (0x4)
	int LastYearWinterfestWasSeen; // 0xb14 (0x4)
	struct TArray<struct FSocialStatusSerialized> FriendSocialStatuses; // 0xb18 (0x10)
	bool bHasSeenSidekickWelcomePopup; // 0xb28 (0x1)
	bool bHasSeenLobbyModeSetNotification; // 0xb29 (0x1)
	bool bHasSeenLobbyModeChangedNotification; // 0xb2a (0x1)
	bool bHasSeenDiscoveryModeSetNotification; // 0xb2b (0x1)
	unsigned char unreflected_b2c[0x4]; // 0xb2c (0x4) 
	struct TSet<struct FString> HasSeenDiscoveryDetailsModeSetNotificationMnemonics; // 0xb30 (0x50)
	bool bHasSeenCreatorPageFirstTimeTooltip; // 0xb80 (0x1)
	unsigned char unreflected_b81[0x7]; // 0xb81 (0x7) 
	bool LowInputLatencyModeIsEnabled; // 0xb88 (0x1)
	bool bNeedsToSeeFireModeSelectionReminder; // 0xb89 (0x1)
	unsigned char unreflected_b8a[0x2]; // 0xb8a (0x2) 
	int MatchesSinceInitialFireModeSelection; // 0xb8c (0x4)
	unsigned char padding_b90[0x8]; // 0xb90 (0x8)

	/* Functions */

	// Function /Script/FortniteGame.FortGameUserSettings.ToggleScalabilityMode (Underlying native function: ToggleScalabilityMode 0x890fe8c)
	void ToggleScalabilityMode(enum EFortScalabilityMode& Mode, bool& bEnabled, bool& bForceApply, bool& bApplyImmediately); // (Final | Native | Public | BlueprintCallable)

	// Function /Script/FortniteGame.FortGameUserSettings.SetUserInterfaceContrast (Underlying native function: SetUserInterfaceContrast 0x890fc9c)
	void SetUserInterfaceContrast(float& InContrast); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetUseLatencyTweak2 (Underlying native function: SetUseLatencyTweak2 0x890fc20)
	void SetUseLatencyTweak2(int& InLatencyTweak2); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetUseLatencyTweak1 (Underlying native function: SetUseLatencyTweak1 0x890fba0)
	void SetUseLatencyTweak1(bool& bEnabled); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetUseLatencyFlash (Underlying native function: SetUseLatencyFlash 0x890fb20)
	void SetUseLatencyFlash(bool& bEnabled); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetUseGPUCrashDebugging (Underlying native function: SetUseGPUCrashDebugging 0x890fa78)
	void SetUseGPUCrashDebugging(bool& bEnabled); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetTemporalSuperResolutionQuality (Underlying native function: SetTemporalSuperResolutionQuality 0x890f9f4)
	void SetTemporalSuperResolutionQuality(int& InTSRQuality); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetShowTemperature (Underlying native function: SetShowTemperature 0x890f96c)
	void SetShowTemperature(bool& bNewValue); // (Final | 0x00000002 | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetShowCareerTabBang (Underlying native function: SetShowCareerTabBang 0x890f8ec)
	void SetShowCareerTabBang(bool& Value); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetShowActorsWithSeasonItemTagMapIndicators (Underlying native function: SetShowActorsWithSeasonItemTagMapIndicators 0x890f86c)
	void SetShowActorsWithSeasonItemTagMapIndicators(bool& bInShowActorsWithSeasonItemTagMapIndicators); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetSafeZone (Underlying native function: SetSafeZone 0x890f7dc)
	void SetSafeZone(float& Value); // (Final | 0x00000002 | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetResolutionFraction (Underlying native function: SetResolutionFraction 0x890f758)
	void SetResolutionFraction(float& ResolutionFraction); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetRenderingAPISelection (Underlying native function: SetRenderingAPISelection 0x890f6d8)
	void SetRenderingAPISelection(enum ERHIType& InRenderingAPI); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetReflectionQualityForGameMode (Underlying native function: SetReflectionQualityForGameMode 0x5d6f3b0)
	void SetReflectionQualityForGameMode(int& NewReflectionQuality); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetNaniteEnabled (Underlying native function: SetNaniteEnabled 0x890f618)
	void SetNaniteEnabled(bool& bEnable); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetMobileFPSMode (Underlying native function: SetMobileFPSMode 0x890f598)
	void SetMobileFPSMode(enum EFortMobileFPSMode& Mode); // (Final | Native | Public | BlueprintCallable)

	// Function /Script/FortniteGame.FortGameUserSettings.SetMeshQuality (Underlying native function: SetMeshQuality 0x890f518)
	void SetMeshQuality(int& Value); // (Final | 0x00000002 | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetLastSelectedFillOption (Underlying native function: SetLastSelectedFillOption 0x890f498)
	void SetLastSelectedFillOption(bool& FillOption); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetHasSeenTapToShoot (Underlying native function: SetHasSeenTapToShoot 0x890f404)
	void SetHasSeenTapToShoot(bool& bHasSeenIt); // (Final | Native | Public | BlueprintCallable)

	// Function /Script/FortniteGame.FortGameUserSettings.SetHasSeenPanningTip (Underlying native function: SetHasSeenPanningTip 0x890f380)
	void SetHasSeenPanningTip(bool& bHasSeenIt); // (Final | Native | Public | BlueprintCallable)

	// Function /Script/FortniteGame.FortGameUserSettings.SetHasSeenLobbyModeChangedNotification (Underlying native function: SetHasSeenLobbyModeChangedNotification 0x890f2ec)
	void SetHasSeenLobbyModeChangedNotification(bool& bHasSeen); // (Final | Native | Public | BlueprintCallable)

	// Function /Script/FortniteGame.FortGameUserSettings.SetHasSeenCreativePhoneTutorial (Underlying native function: SetHasSeenCreativePhoneTutorial 0x890f258)
	void SetHasSeenCreativePhoneTutorial(bool& bHasSeenCreativePhoneTutorial); // (Final | Native | Public | BlueprintCallable)

	// Function /Script/FortniteGame.FortGameUserSettings.SetHasSeenCreativeHeatmapTutorial (Underlying native function: SetHasSeenCreativeHeatmapTutorial 0x890f1c4)
	void SetHasSeenCreativeHeatmapTutorial(bool& bHasSeenCreativeHeatmapTutorial); // (Final | Native | Public | BlueprintCallable)

	// Function /Script/FortniteGame.FortGameUserSettings.SetHardwareRayTracingEnabled (Underlying native function: SetHardwareRayTracingEnabled 0x890f144)
	void SetHardwareRayTracingEnabled(bool& bEnable); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetGlobalIlluminationQualityForGameMode (Underlying native function: SetGlobalIlluminationQualityForGameMode 0x5d6f2b0)
	void SetGlobalIlluminationQualityForGameMode(int& NewGlobalIlluminationQuality); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetDonutShopSequenceMarkedAsSeen (Underlying native function: SetDonutShopSequenceMarkedAsSeen 0x890ef10)
	void SetDonutShopSequenceMarkedAsSeen(bool& bHasSeen); // (Final | Native | Public | BlueprintCallable)

	// Function /Script/FortniteGame.FortGameUserSettings.SetDLSSQuality (Underlying native function: SetDLSSQuality 0x890edf4)
	void SetDLSSQuality(int& InDLSSQuality); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetDisplayGamma (Underlying native function: SetDisplayGamma 0x890ee78)
	void SetDisplayGamma(float& InGamma); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetCachedStylePoints (Underlying native function: SetCachedStylePoints 0x890ecc4)
	void SetCachedStylePoints(int& Value); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetCachedPlayerLevel (Underlying native function: SetCachedPlayerLevel 0x890ec48)
	void SetCachedPlayerLevel(int& Value); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetCachedHighestBattlePassUnlockedPage (Underlying native function: SetCachedHighestBattlePassUnlockedPage 0x890ebcc)
	void SetCachedHighestBattlePassUnlockedPage(int& Value); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetCachedClaimableRewards (Underlying native function: SetCachedClaimableRewards 0x890ea24)
	void SetCachedClaimableRewards(struct FString& ClaimableRewardsPageType, int& ClaimableRewards); // (Final | 0x00000002 | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetCachedBattleStars (Underlying native function: SetCachedBattleStars 0x890e9a8)
	void SetCachedBattleStars(int& Value); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetCachedAlienStylePoints (Underlying native function: SetCachedAlienStylePoints 0x890e92c)
	void SetCachedAlienStylePoints(int& Value); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetAutoDownloadHighResTexturesBool (Underlying native function: SetAutoDownloadHighResTexturesBool 0x890e8a4)
	void SetAutoDownloadHighResTexturesBool(bool& bValue); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetAudioOutputDeviceId (Underlying native function: SetAudioOutputDeviceId 0x283c520)
	void SetAudioOutputDeviceId(struct FString& InAudioOutputDeviceId); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.SetAntiAliasingMethod (Underlying native function: SetAntiAliasingMethod 0x890e828)
	void SetAntiAliasingMethod(int& InFrameResolveMethod); // (Final | Native | Public)

	// Function /Script/FortniteGame.FortGameUserSettings.ResetToDefaultDeviceScalability (Underlying native function: ResetToDefaultDeviceScalability 0x890e814)
	void ResetToDefaultDeviceScalability(); // (Final | 0x00000002 | Native | Public | BlueprintCallable)

	// Function /Script/FortniteGame.FortGameUserSettings.ResetScalabilityModes (Underlying native function: ResetScalabilityModes 0x890e7a4)
	void ResetScalabilityModes(); // (Final | Native | Public | BlueprintCallable)

	// Function /Script/FortniteGame.FortGameUserSettings.IsVideoPlaybackAllowed (Underlying native function: IsVideoPlaybackAllowed 0x890e750)
	bool IsVideoPlaybackAllowed(); // (Final | Native | Public | BlueprintCallable)

	// Function /Script/FortniteGame.FortGameUserSettings.IsLowInputLatencyModeEnabled (Underlying native function: IsLowInputLatencyModeEnabled 0x890e580)
	bool IsLowInputLatencyModeEnabled(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.IsInPerformanceMode (Underlying native function: IsInPerformanceMode 0x473dc44)
	bool IsInPerformanceMode(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.IsHeadphoneModeEnabled (Underlying native function: IsHeadphoneModeEnabled 0x890e4bc)
	bool IsHeadphoneModeEnabled(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.IsDynamicResolutionSupported (Underlying native function: IsDynamicResolutionSupported 0x890e394)
	bool IsDynamicResolutionSupported(); // (Final | 0x00000002 | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.HasRecordedStat (Underlying native function: HasRecordedStat 0x890e094)
	bool HasRecordedStat(struct FName& RecordName); // (Final | Native | Public | HasOutParms | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetWillBeLetoGame (Underlying native function: GetWillBeLetoGame 0x2486284)
	bool GetWillBeLetoGame(); // (Final | 0x00000002 | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetUserInterfaceContrast (Underlying native function: GetUserInterfaceContrast 0x2d00eec)
	float GetUserInterfaceContrast(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetUseLatencyTweak2 (Underlying native function: GetUseLatencyTweak2 0x2d00a7c)
	int GetUseLatencyTweak2(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetUseLatencyTweak1 (Underlying native function: GetUseLatencyTweak1 0x2d00a64)
	bool GetUseLatencyTweak1(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetUseLatencyFlash (Underlying native function: GetUseLatencyFlash 0x890df6c)
	bool GetUseLatencyFlash(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetUseGPUCrashDebugging (Underlying native function: GetUseGPUCrashDebugging 0x2d00a4c)
	bool GetUseGPUCrashDebugging(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetTemporalSuperResolutionQuality (Underlying native function: GetTemporalSuperResolutionQuality 0x2b91548)
	int GetTemporalSuperResolutionQuality(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetShowTemperature (Underlying native function: GetShowTemperature 0x890dd08)
	bool GetShowTemperature(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetShowCareerTabBang (Underlying native function: GetShowCareerTabBang 0x890dcf0)
	bool GetShowCareerTabBang(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetShowActorsWithSeasonItemTagMapIndicators (Underlying native function: GetShowActorsWithSeasonItemTagMapIndicators 0x890dcd8)
	bool GetShowActorsWithSeasonItemTagMapIndicators(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetSafeZone (Underlying native function: GetSafeZone 0x2d00f34)
	float GetSafeZone(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetResolutionFraction (Underlying native function: GetResolutionFraction 0x1503588)
	float GetResolutionFraction(); // (Final | 0x00000002 | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetRenderingAPISelection (Underlying native function: GetRenderingAPISelection 0x2d00f04)
	enum ERHIType GetRenderingAPISelection(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetRenderingAPI (Underlying native function: GetRenderingAPI 0x890dc70)
	enum ERHIType GetRenderingAPI(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetReflectionQualityForGameMode (Underlying native function: GetReflectionQualityForGameMode 0x5d6f230)
	int GetReflectionQualityForGameMode(); // (Final | 0x00000002 | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetNaniteEnabled (Underlying native function: GetNaniteEnabled 0x2d00f1c)
	bool GetNaniteEnabled(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetMeshQuality (Underlying native function: GetMeshQuality 0x2b63484)
	int GetMeshQuality(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetLastSelectedFillOption (Underlying native function: GetLastSelectedFillOption 0x7596c00)
	bool GetLastSelectedFillOption(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetHasSeenTapToShoot (Underlying native function: GetHasSeenTapToShoot 0x890d9cc)
	bool GetHasSeenTapToShoot(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetHasSeenPanningTip (Underlying native function: GetHasSeenPanningTip 0x890d9b0)
	bool GetHasSeenPanningTip(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetHasSeenCreativePhoneTutorial (Underlying native function: GetHasSeenCreativePhoneTutorial 0x8245d88)
	bool GetHasSeenCreativePhoneTutorial(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetHasSeenCreativeHeatmapTutorial (Underlying native function: GetHasSeenCreativeHeatmapTutorial 0x890d998)
	bool GetHasSeenCreativeHeatmapTutorial(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetHardwareRayTracingEnabled (Underlying native function: GetHardwareRayTracingEnabled 0x2d7813c)
	bool GetHardwareRayTracingEnabled(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetGlobalIlluminationQualityForGameMode (Underlying native function: GetGlobalIlluminationQualityForGameMode 0x5d6f200)
	int GetGlobalIlluminationQualityForGameMode(); // (Final | 0x00000002 | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetFireModeData (Underlying native function: GetFireModeData 0x890d834)
	struct FFireModeData GetFireModeData(); // (Final | 0x00000002 | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetDLSSQuality (Underlying native function: GetDLSSQuality 0x890d784)
	int GetDLSSQuality(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetDisplayGamma (Underlying native function: GetDisplayGamma 0x2d00ed4)
	float GetDisplayGamma(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetCachedStylePoints (Underlying native function: GetCachedStylePoints 0x8719de4)
	int GetCachedStylePoints(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetCachedPlayerLevel (Underlying native function: GetCachedPlayerLevel 0x890d76c)
	int GetCachedPlayerLevel(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetCachedHighestBattlePassUnlockedPage (Underlying native function: GetCachedHighestBattlePassUnlockedPage 0x890d754)
	int GetCachedHighestBattlePassUnlockedPage(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetCachedClaimableRewards (Underlying native function: GetCachedClaimableRewards 0x890d5b8)
	int GetCachedClaimableRewards(struct FString& ClaimableRewardsPageType); // (Final | 0x00000002 | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetCachedBattleStars (Underlying native function: GetCachedBattleStars 0x890d5a0)
	int GetCachedBattleStars(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetCachedAlienStylePoints (Underlying native function: GetCachedAlienStylePoints 0x890d588)
	int GetCachedAlienStylePoints(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetAutoDownloadHighResTextures (Underlying native function: GetAutoDownloadHighResTextures 0x2b3f250)
	bool GetAutoDownloadHighResTextures(); // (Final | Native | Public | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetAudioOutputDeviceId (Underlying native function: GetAudioOutputDeviceId 0x2713bf4)
	struct FString GetAudioOutputDeviceId(); // (Final | Native | Public | BlueprintCallable | BlueprintPure | Const)

	// Function /Script/FortniteGame.FortGameUserSettings.GetAntiAliasingMethod (Underlying native function: GetAntiAliasingMethod 0x2b91464)
	int GetAntiAliasingMethod(); // (Final | Native | Public | Const)
};

