// VerseClass /VerseFortniteInternal/_Verse/VNI/VerseFortniteInternal.Game_Player_PlayerInventory
// Size: 0x28
class UGame_Player_PlayerInventory : public UObject
{

	/* Functions */

	// Function /VerseFortniteInternal/_Verse/VNI/VerseFortniteInternal.Game_Player_PlayerInventory._L_2fFortnite_2ecom_2fGame_2fPlayer_2fPlayerInventory_N_RTryAddToInventory_L_Nplayer_M_N_Kchar_M_Nint_M_Nlogic_R (Underlying native function: _L_2fFortnite_2ecom_2fGame_2fPlayer_2fPlayerInventory_N_RTryAddToInventory_L_Nplayer_M_N_Kchar_M_Nint_M_Nlogic_R 0x707f648)
	static void L2fFortnite2ecom2fGame2fPlayer2fPlayerInventoryNRTryAddToInventoryLNplayerMNKcharMNintMNlogicR(struct Ftuple_Lplayer_M_Kchar_Mint_Mlogic_R& verse0xB2CDDD72Argument); // (Final | Native | Static | Public | BlueprintCallable)

	// Function /VerseFortniteInternal/_Verse/VNI/VerseFortniteInternal.Game_Player_PlayerInventory._L_2fFortnite_2ecom_2fGame_2fPlayer_2fPlayerInventory_N_RTryAddItemToInventory_L_Nplayer_M_Nfort__item__definition_M_Nint_M_Nlogic_R (Underlying native function: _L_2fFortnite_2ecom_2fGame_2fPlayer_2fPlayerInventory_N_RTryAddItemToInventory_L_Nplayer_M_Nfort__item__definition_M_Nint_M_Nlogic_R 0x707f640)
	static void L2fFortnite2ecom2fGame2fPlayer2fPlayerInventoryNRTryAddItemToInventoryLNplayerMNfortitemdefinitionMNintMNlogicR(struct Ftuple_Lplayer_Mfort__item__definition_Mint_Mlogic_R& verse0xB2CDDD72Argument); // (Final | Native | Static | Public | HasOutParms | BlueprintCallable)

	// Function /VerseFortniteInternal/_Verse/VNI/VerseFortniteInternal.Game_Player_PlayerInventory._L_2fFortnite_2ecom_2fGame_2fPlayer_2fPlayerInventory_N_RRemoveFromInventory_L_Nplayer_M_N_Kchar_M_Nint_R (Underlying native function: _L_2fFortnite_2ecom_2fGame_2fPlayer_2fPlayerInventory_N_RRemoveFromInventory_L_Nplayer_M_N_Kchar_M_Nint_R 0x707f638)
	static unsigned char L2fFortnite2ecom2fGame2fPlayer2fPlayerInventoryNRRemoveFromInventoryLNplayerMNKcharMNintR(struct Ftuple_Lplayer_M_Kchar_Mint_R& verse0xB2CDDD72Argument); // (Final | Native | Static | Public | HasOutParms | BlueprintCallable)

	// Function /VerseFortniteInternal/_Verse/VNI/VerseFortniteInternal.Game_Player_PlayerInventory._L_2fFortnite_2ecom_2fGame_2fPlayer_2fPlayerInventory_N_RClearDroppableItems_L_Nplayer_R (Underlying native function: _L_2fFortnite_2ecom_2fGame_2fPlayer_2fPlayerInventory_N_RClearDroppableItems_L_Nplayer_R 0x707f630)
	static void L2fFortnite2ecom2fGame2fPlayer2fPlayerInventoryNRClearDroppableItemsLNplayerR(class USimulation_player*& verse0xB2CDDD72Argument); // (Final | Native | Static | Public | BlueprintCallable)

	// Function /VerseFortniteInternal/_Verse/VNI/VerseFortniteInternal.Game_Player_PlayerInventory.$InitCDO (Has no native function)
	void $InitCDO(); // ()
};

