// BlueprintGeneratedClass /Game/Abilities/Player/GC/GC_Abilities_Activation_DBNOResurrect.GC_Abilities_Activation_DBNOResurrect_C
// Size: 0x210
class UGC_Abilities_Activation_DBNOResurrect_C : public UFortGameplayCueNotify_Burst
{

	/* Functions */

	// Function /Game/Abilities/Player/GC/GC_Abilities_Activation_DBNOResurrect.GC_Abilities_Activation_DBNOResurrect_C.OnBurst (Has no native function)
	void OnBurst(class AActor*& MyTarget, struct FGameplayCueParameters& Parameters, struct TArray<class UParticleSystemComponent*>& ParticleComponents, struct TArray<class UAudioComponent*>& AudioComponents, class ULegacyCameraShake*& BurstCameraShakeInstance, class ADecalActor*& BurstDecalInstance, class UParticleSystemComponent*& CallFuncArrayGetItem, float& CallFuncBreakGameplayCueParametersNormalizedMagnitude, float& CallFuncBreakGameplayCueParametersRawMagnitude, struct FGameplayEffectContextHandle& CallFuncBreakGameplayCueParametersEffectContext, struct FGameplayTag& CallFuncBreakGameplayCueParametersMatchedTagName, struct FGameplayTag& CallFuncBreakGameplayCueParametersOriginalTag, struct FGameplayTagContainer& CallFuncBreakGameplayCueParametersAggregatedSourceTags, struct FGameplayTagContainer& CallFuncBreakGameplayCueParametersAggregatedTargetTags, struct FVector& CallFuncBreakGameplayCueParametersLocation, struct FVector& CallFuncBreakGameplayCueParametersNormal, class AActor*& CallFuncBreakGameplayCueParametersInstigator, class AActor*& CallFuncBreakGameplayCueParametersEffectCauser, class UObject*& CallFuncBreakGameplayCueParametersSourceObject, class UPhysicalMaterial*& CallFuncBreakGameplayCueParametersPhysicalMaterial, int& CallFuncBreakGameplayCueParametersGameplayEffectLevel, int& CallFuncBreakGameplayCueParametersAbilityLevel, class USceneComponent*& CallFuncBreakGameplayCueParametersTargetAttachComponent, bool& CallFuncBreakGameplayCueParametersbReplicateLocationWhenUsingMinimalRepProxy, struct FVector& CallFuncMakeVectorReturnValue, struct FRotator& CallFuncMakeRotFromXReturnValue, struct FHitResult& CallFuncK2SetWorldLocationAndRotationSweepHitResult, double& CallFuncDivideDoubleDoubleReturnValue, struct FVector& CallFuncMakeVectorReturnValue1, double& CallFuncMakeVectorXImplicitCast, double& CallFuncMakeVectorYImplicitCast, double& CallFuncDivideDoubleDoubleAImplicitCast); // (Event | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent | Const)
};

