// BlueprintGeneratedClass /Game/Athena/GameplayCueNotifies/GCN_Athena_HidingProp_Wobble.GCN_Athena_HidingProp_Wobble_C
// Size: 0x210
class UGCN_Athena_HidingProp_Wobble_C : public UFortGameplayCueNotify_Burst
{

	/* Functions */

	// Function /Game/Athena/GameplayCueNotifies/GCN_Athena_HidingProp_Wobble.GCN_Athena_HidingProp_Wobble_C.OnBurst (Has no native function)
	void OnBurst(class AActor*& MyTarget, struct FGameplayCueParameters& Parameters, struct TArray<class UParticleSystemComponent*>& ParticleComponents, struct TArray<class UAudioComponent*>& AudioComponents, class ULegacyCameraShake*& BurstCameraShakeInstance, class ADecalActor*& BurstDecalInstance, float& CallFuncBreakGameplayCueParametersNormalizedMagnitude, float& CallFuncBreakGameplayCueParametersRawMagnitude, struct FGameplayEffectContextHandle& CallFuncBreakGameplayCueParametersEffectContext, struct FGameplayTag& CallFuncBreakGameplayCueParametersMatchedTagName, struct FGameplayTag& CallFuncBreakGameplayCueParametersOriginalTag, struct FGameplayTagContainer& CallFuncBreakGameplayCueParametersAggregatedSourceTags, struct FGameplayTagContainer& CallFuncBreakGameplayCueParametersAggregatedTargetTags, struct FVector& CallFuncBreakGameplayCueParametersLocation, struct FVector& CallFuncBreakGameplayCueParametersNormal, class AActor*& CallFuncBreakGameplayCueParametersInstigator, class AActor*& CallFuncBreakGameplayCueParametersEffectCauser, class UObject*& CallFuncBreakGameplayCueParametersSourceObject, class UPhysicalMaterial*& CallFuncBreakGameplayCueParametersPhysicalMaterial, int& CallFuncBreakGameplayCueParametersGameplayEffectLevel, int& CallFuncBreakGameplayCueParametersAbilityLevel, class USceneComponent*& CallFuncBreakGameplayCueParametersTargetAttachComponent, bool& CallFuncBreakGameplayCueParametersbReplicateLocationWhenUsingMinimalRepProxy, struct FTransform& CallFuncGetTransformReturnValue, class ABuildingSMActor*& K2NodeDynamicCastAsBuildingStaticMesh, bool& K2NodeDynamicCastbSuccess, struct FVector& CallFuncTransformLocationReturnValue, double& CallFuncGetTimeSecondsReturnValue, float& CallFuncStartBounceAnimationStartTimeImplicitCast); // (Event | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent | Const)
};

