// BlueprintGeneratedClass /Game/Athena/GameplayCueNotifies/GCN_Athena_Tether_FallLanding.GCN_Athena_Tether_FallLanding_C
// Size: 0x210
class UGCN_Athena_Tether_FallLanding_C : public UFortGameplayCueNotify_Burst
{

	/* Functions */

	// Function /Game/Athena/GameplayCueNotifies/GCN_Athena_Tether_FallLanding.GCN_Athena_Tether_FallLanding_C.OnBurst (Has no native function)
	void OnBurst(class AActor*& MyTarget, struct FGameplayCueParameters& Parameters, struct TArray<class UParticleSystemComponent*>& ParticleComponents, struct TArray<class UAudioComponent*>& AudioComponents, class ULegacyCameraShake*& BurstCameraShakeInstance, class ADecalActor*& BurstDecalInstance, class UAudioComponent*& CallFuncArrayGetItem, float& CallFuncBreakGameplayCueParametersNormalizedMagnitude, float& CallFuncBreakGameplayCueParametersRawMagnitude, struct FGameplayEffectContextHandle& CallFuncBreakGameplayCueParametersEffectContext, struct FGameplayTag& CallFuncBreakGameplayCueParametersMatchedTagName, struct FGameplayTag& CallFuncBreakGameplayCueParametersOriginalTag, struct FGameplayTagContainer& CallFuncBreakGameplayCueParametersAggregatedSourceTags, struct FGameplayTagContainer& CallFuncBreakGameplayCueParametersAggregatedTargetTags, struct FVector& CallFuncBreakGameplayCueParametersLocation, struct FVector& CallFuncBreakGameplayCueParametersNormal, class AActor*& CallFuncBreakGameplayCueParametersInstigator, class AActor*& CallFuncBreakGameplayCueParametersEffectCauser, class UObject*& CallFuncBreakGameplayCueParametersSourceObject, class UPhysicalMaterial*& CallFuncBreakGameplayCueParametersPhysicalMaterial, int& CallFuncBreakGameplayCueParametersGameplayEffectLevel, int& CallFuncBreakGameplayCueParametersAbilityLevel, class USceneComponent*& CallFuncBreakGameplayCueParametersTargetAttachComponent, bool& CallFuncBreakGameplayCueParametersbReplicateLocationWhenUsingMinimalRepProxy, class AFortPlayerPawn*& K2NodeDynamicCastAsFortPlayerPawn, bool& K2NodeDynamicCastbSuccess, int& CallFuncFTruncReturnValue, class AFortWaterBodyActor*& CallFuncGetCurrentWaterBodyReturnValue, struct TScriptInterface<class IAudioParameterControllerInterface>& CallFuncSetIntParameterselfCastInput, bool& CallFuncIsValidReturnValue, struct FVector& CallFuncK2GetActorLocationReturnValue, struct FWaterSurfaceInfo& CallFuncGetWaterSurfaceInfoStructOutWaterSurfaceInfo, class AController*& CallFuncGetControllerReturnValue, class AFortPlayerController*& K2NodeDynamicCastAsFortPlayerController, bool& K2NodeDynamicCastbSuccess1, float& CallFuncConvIntToFloatReturnValue, struct TScriptInterface<class ICameraLensEffectInterface>& CallFuncAddGenericCameraLensEffectReturnValue, class UFXSystemComponent*& CallFuncSpawnFXAtLocationReturnValue, bool& CallFuncGreaterDoubleDoubleReturnValue, double& CallFuncGreaterDoubleDoubleAImplicitCast, double& CallFuncFTruncAImplicitCast); // (Event | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent | Const)
};

