// BlueprintGeneratedClass /Game/Athena/GameplayCueNotifies/GCN_Athena_HidingProp_HayStack_Rustle.GCN_Athena_HidingProp_HayStack_Rustle_C
// Size: 0x210
class UGCN_Athena_HidingProp_HayStack_Rustle_C : public UFortGameplayCueNotify_Burst
{

	/* Functions */

	// Function /Game/Athena/GameplayCueNotifies/GCN_Athena_HidingProp_HayStack_Rustle.GCN_Athena_HidingProp_HayStack_Rustle_C.OnBurst (Has no native function)
	void OnBurst(class AActor*& MyTarget, struct FGameplayCueParameters& Parameters, struct TArray<class UParticleSystemComponent*>& ParticleComponents, struct TArray<class UAudioComponent*>& AudioComponents, class ULegacyCameraShake*& BurstCameraShakeInstance, class ADecalActor*& BurstDecalInstance, int& CallFuncArrayLengthReturnValue, float& CallFuncBreakGameplayCueParametersNormalizedMagnitude, float& CallFuncBreakGameplayCueParametersRawMagnitude, struct FGameplayEffectContextHandle& CallFuncBreakGameplayCueParametersEffectContext, struct FGameplayTag& CallFuncBreakGameplayCueParametersMatchedTagName, struct FGameplayTag& CallFuncBreakGameplayCueParametersOriginalTag, struct FGameplayTagContainer& CallFuncBreakGameplayCueParametersAggregatedSourceTags, struct FGameplayTagContainer& CallFuncBreakGameplayCueParametersAggregatedTargetTags, struct FVector& CallFuncBreakGameplayCueParametersLocation, struct FVector& CallFuncBreakGameplayCueParametersNormal, class AActor*& CallFuncBreakGameplayCueParametersInstigator, class AActor*& CallFuncBreakGameplayCueParametersEffectCauser, class UObject*& CallFuncBreakGameplayCueParametersSourceObject, class UPhysicalMaterial*& CallFuncBreakGameplayCueParametersPhysicalMaterial, int& CallFuncBreakGameplayCueParametersGameplayEffectLevel, int& CallFuncBreakGameplayCueParametersAbilityLevel, class USceneComponent*& CallFuncBreakGameplayCueParametersTargetAttachComponent, bool& CallFuncBreakGameplayCueParametersbReplicateLocationWhenUsingMinimalRepProxy, struct FVector& CallFuncK2GetActorLocationReturnValue, unsigned char& CallFuncGetActorTeamReturnValue, int& TempintArrayIndexVariable, int& TempintLoopCounterVariable, class UParticleSystemComponent*& CallFuncArrayGetItem, struct FHitResult& CallFuncK2SetWorldLocationSweepHitResult, bool& CallFuncLessIntIntReturnValue, int& CallFuncAddIntIntReturnValue, struct TArray<class AFortPlayerController*>& TempobjectVariable, struct TArray<struct TEnumAsByte<EFortTeamAffiliation>>& K2NodeMakeArrayArray); // (Event | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent | Const)
};

