// BlueprintGeneratedClass /Ascender/GameplayCues/GCN_Ascender_SpeedLines.GCN_Ascender_SpeedLines_C
// Size: 0x218
class UGCN_Ascender_SpeedLines_C : public UFortGameplayCueNotify_Burst
{
	class UMaterialInterface* DecalMaterial; // 0x210 (0x8)

	/* Functions */

	// Function /Ascender/GameplayCues/GCN_Ascender_SpeedLines.GCN_Ascender_SpeedLines_C.OnBurst (Has no native function)
	void OnBurst(class AActor*& MyTarget, struct FGameplayCueParameters& Parameters, struct TArray<class UParticleSystemComponent*>& ParticleComponents, struct TArray<class UAudioComponent*>& AudioComponents, class ULegacyCameraShake*& BurstCameraShakeInstance, class ADecalActor*& BurstDecalInstance, class UParticleSystemComponent*& CallFuncArrayGetItem, int& CallFuncArrayLengthReturnValue, struct FHitResult& CallFuncK2AddWorldOffsetSweepHitResult, bool& CallFuncGreaterIntIntReturnValue, struct FHitResult& CallFuncK2SetWorldRotationSweepHitResult, struct FVector& CallFuncGetForwardVectorReturnValue, struct FVector& CallFuncK2GetComponentLocationReturnValue, struct FVector& CallFuncMultiplyVectorFloatReturnValue, struct FVector& CallFuncAddVectorVectorReturnValue, struct TArray<class AActor*>& TempobjectVariable, struct FVector& CallFuncSubtractVectorVectorReturnValue, struct FVector& CallFuncAddVectorVectorReturnValue1, struct TArray<struct TEnumAsByte<EObjectTypeQuery>>& K2NodeMakeArrayArray, struct FHitResult& CallFuncLineTraceSingleForObjectsOutHit, bool& CallFuncLineTraceSingleForObjectsReturnValue, bool& CallFuncBreakHitResultbBlockingHit, bool& CallFuncBreakHitResultbInitialOverlap, float& CallFuncBreakHitResultTime, float& CallFuncBreakHitResultDistance, struct FVector& CallFuncBreakHitResultLocation, struct FVector& CallFuncBreakHitResultImpactPoint, struct FVector& CallFuncBreakHitResultNormal, struct FVector& CallFuncBreakHitResultImpactNormal, class UPhysicalMaterial*& CallFuncBreakHitResultPhysMat, class AActor*& CallFuncBreakHitResultHitActor, class UPrimitiveComponent*& CallFuncBreakHitResultHitComponent, struct FName& CallFuncBreakHitResultHitBoneName, struct FName& CallFuncBreakHitResultBoneName, int& CallFuncBreakHitResultHitItem, int& CallFuncBreakHitResultElementIndex, int& CallFuncBreakHitResultFaceIndex, struct FVector& CallFuncBreakHitResultTraceStart, struct FVector& CallFuncBreakHitResultTraceEnd, struct FVector& CallFuncMultiplyVectorFloatReturnValue1, struct FRotator& CallFuncConvVectorToRotatorReturnValue, struct FRotator& CallFuncConvVectorToRotatorReturnValue1, struct FHitResult& CallFuncK2SetWorldLocationAndRotationSweepHitResult, class UDecalComponent*& CallFuncSpawnDecalAtLocationReturnValue); // (Event | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent | Const)
};

