// BlueprintGeneratedClass /Irwin/AI/Prey/Nug/Abilities/GE_NPC_Irwin_Prey_Nug_BehaviorPhaseIntroBehaviorActive.GE_NPC_Irwin_Prey_Nug_BehaviorPhaseIntroBehaviorActive_C
// Size: 0x858
class UGE_NPC_Irwin_Prey_Nug_BehaviorPhaseIntroBehaviorActive_C : public UGE_NPC_Parent_BehaviorPhaseIntroBehaviorActive_C
{
};

