// BlueprintGeneratedClass /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C
// Size: 0x28
class UMissionBlueprintFunctionLibrary_C : public UBlueprintFunctionLibrary
{

	/* Functions */

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.Any Player Pawn Near Location (Has no native function)
	static void AnyPlayerPawnNearLocation(double& DistanceToCheck, struct FVector& Location, struct TArray<class AFortPlayerPawn*>& IgnorePlayerPawns, class UObject*& WorldContext, bool& IsPawnNearLocation, struct TArray<class AFortPawn*>& PawnsNearLocation, struct TArray<class AFortPlayerPawn*>& FilteredPlayerPawns, struct TArray<class AFortPawn*>& Pawns, int& TempintLoopCounterVariable, struct TArray<class AFortPlayerPawn*>& CallFuncGetAllFortPlayerPawnsOutFortPlayerPawns, int& CallFuncAddIntIntReturnValue, int& CallFuncArrayLengthReturnValue, int& TempintArrayIndexVariable, class AFortPawn*& CallFuncArrayGetItem, int& CallFuncArrayLengthReturnValue1, bool& CallFuncAthenaCheckActorHasTagsbDidActorHaveTags, bool& CallFuncLessIntIntReturnValue, struct FVector& CallFuncK2GetActorLocationReturnValue, int& TempintLoopCounterVariable1, double& CallFuncDistanceBetweenTwoVectorsDistance, bool& CallFuncLessIntIntReturnValue1, bool& CallFuncLessEqualDoubleDoubleReturnValue, int& CallFuncAddIntIntReturnValue1, int& TempintArrayIndexVariable1, class AFortPlayerPawn*& CallFuncArrayGetItem1, int& CallFuncArrayLengthReturnValue2, bool& CallFuncArrayRemoveItemReturnValue, bool& CallFuncGreaterEqualIntIntReturnValue, class AFortPawn*& TempobjectVariable, int& CallFuncArrayAddUniqueReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.GetSeasonalEventManager (Has no native function)
	static void GetSeasonalEventManager(class UObject*& WorldContextObject, class UObject*& WorldContext, class UFortSeasonalEventManager*& SeasonalEventManager, class UGameInstance*& CallFuncGetGameInstanceReturnValue, class UFortGameInstance*& K2NodeDynamicCastAsFortGameInstance, bool& K2NodeDynamicCastbSuccess, class UFortSeasonalEventManager*& CallFuncGetEventManagerReturnValue); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent | BlueprintPure)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.NPC_CanBeElemental (Has no native function)
	static void NPCCanBeElemental(struct FGameplayTag& PawnTag, class UObject*& WorldContext, bool& Value, struct FGameplayTagContainer& ElementalEnablePawnTag, bool& CallFuncHasTagReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.LaunchHoverboard (Has no native function)
	static void LaunchHoverboard(class AActor*& HoverboardActor, struct FVector& LaunchVelocity, struct FName& ForceFeedbackTag, class UObject*& WorldContext, bool& Success, class AFortAthenaJackalVehicle*& Hoverboard, class AFortAthenaJackalVehicle*& K2NodeDynamicCastAsFortAthenaJackalVehicle, bool& K2NodeDynamicCastbSuccess, struct TScriptInterface<class IFortVehicleInterface>& CallFuncGetDriverselfCastInput, class AFortPlayerPawn*& CallFuncGetDriverReturnValue, struct TScriptInterface<class IGameplayTagAssetInterface>& CallFuncHasMatchingGameplayTagselfCastInput, bool& CallFuncHasMatchingGameplayTagReturnValue, bool& CallFuncIsValidReturnValue, class AController*& CallFuncGetControllerReturnValue, class AFortPlayerController*& K2NodeDynamicCastAsFortPlayerController, bool& K2NodeDynamicCastbSuccess1, struct TScriptInterface<class IFortVehicleInterface>& CallFuncSetIgnoreNextFallingDamageselfCastInput, struct FActiveGameplayEffectHandle*& CallFuncApplyGlobalEnvironmentGameplayEffectToActorReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.NPC_ConvertTagToNameText (Has no native function)
	static void NPCConvertTagToNameText(struct FGameplayTag& PawnTag, class UObject*& WorldContext, struct FText& Name, bool& GameplayTagsK2NodeSwitchGameplayTagCmpSuccess); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.CheckBasicVectorToActorLineOfSight (Has no native function)
	static void CheckBasicVectorToActorLineOfSight(struct FVector& VectorA, class AActor*& ActorB, struct FVector& ActorBLocationOffset, struct TEnumAsByte<ETraceTypeQuery>& TraceChannel, struct TEnumAsByte<EDrawDebugTrace>& DrawDebugType, double& DrawTime, struct TArray<class AActor*>& ActorsToIgnore, bool& bTraceComplex, bool& bRequireThatTraceHitActorB, class UObject*& WorldContext, bool& InLineOfSight, double& Distance, bool& Result, bool& CallFuncIsValidReturnValue, struct FVector& CallFuncK2GetActorLocationReturnValue, struct FVector& CallFuncAddVectorVectorReturnValue, double& CallFuncVectorDistanceReturnValue, struct FHitResult& CallFuncLineTraceSingleOutHit, bool& CallFuncLineTraceSingleReturnValue, bool& CallFuncBreakHitResultbBlockingHit, bool& CallFuncBreakHitResultbInitialOverlap, float& CallFuncBreakHitResultTime, float& CallFuncBreakHitResultDistance, struct FVector& CallFuncBreakHitResultLocation, struct FVector& CallFuncBreakHitResultImpactPoint, struct FVector& CallFuncBreakHitResultNormal, struct FVector& CallFuncBreakHitResultImpactNormal, class UPhysicalMaterial*& CallFuncBreakHitResultPhysMat, class AActor*& CallFuncBreakHitResultHitActor, class UPrimitiveComponent*& CallFuncBreakHitResultHitComponent, struct FName& CallFuncBreakHitResultHitBoneName, struct FName& CallFuncBreakHitResultBoneName, int& CallFuncBreakHitResultHitItem, int& CallFuncBreakHitResultElementIndex, int& CallFuncBreakHitResultFaceIndex, struct FVector& CallFuncBreakHitResultTraceStart, struct FVector& CallFuncBreakHitResultTraceEnd, bool& CallFuncEqualEqualObjectObjectReturnValue, float& CallFuncLineTraceSingleDrawTimeImplicitCast, double& K2NodeFunctionResultDistanceImplicitCast); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.CheckBasicActorLineOfSight (Has no native function)
	static void CheckBasicActorLineOfSight(class AActor*& ActorA, struct FVector& ActorALocationOffset, class AActor*& ActorB, struct FVector& ActorBLocationOffset, bool& UseActorHalfHeightForSight, struct TEnumAsByte<ETraceTypeQuery>& TraceChannel, struct TEnumAsByte<EDrawDebugTrace>& DrawDebugType, double& DrawTime, bool& bTraceComplex, class UObject*& WorldContext, bool& InLineOfSight, double& Distance, struct FVector& ActorBOffset, struct FVector& ActorAOffset, struct FVector& ActorBStartVector, struct FVector& ActorAStartVector, bool& Result, bool& CallFuncIsValidReturnValue, struct FVector& CallFuncK2GetActorLocationReturnValue, struct FVector& CallFuncGetActorBoundsOrigin, struct FVector& CallFuncGetActorBoundsBoxExtent, struct FVector& CallFuncK2GetActorLocationReturnValue1, double& CallFuncBreakVectorX, double& CallFuncBreakVectorY, double& CallFuncBreakVectorZ, double& CallFuncFClampReturnValue, bool& CallFuncIsValidReturnValue1, double& CallFuncDivideDoubleDoubleReturnValue, struct FVector& CallFuncMakeVectorReturnValue, struct FVector& CallFuncK2GetActorLocationReturnValue2, struct FVector& CallFuncAddVectorVectorReturnValue, struct FVector& CallFuncGetActorBoundsOrigin1, struct FVector& CallFuncGetActorBoundsBoxExtent1, struct TArray<class AActor*>& K2NodeMakeArrayArray, double& CallFuncBreakVectorX1, double& CallFuncBreakVectorY1, double& CallFuncBreakVectorZ1, struct FVector& CallFuncK2GetActorLocationReturnValue3, double& CallFuncFClampReturnValue1, double& CallFuncDivideDoubleDoubleReturnValue1, struct FVector& CallFuncAddVectorVectorReturnValue1, struct FVector& CallFuncMakeVectorReturnValue1, struct FVector& CallFuncAddVectorVectorReturnValue2, struct FVector& CallFuncAddVectorVectorReturnValue3, struct FHitResult& CallFuncLineTraceSingleOutHit, bool& CallFuncLineTraceSingleReturnValue, bool& CallFuncBreakHitResultbBlockingHit, bool& CallFuncBreakHitResultbInitialOverlap, float& CallFuncBreakHitResultTime, float& CallFuncBreakHitResultDistance, struct FVector& CallFuncBreakHitResultLocation, struct FVector& CallFuncBreakHitResultImpactPoint, struct FVector& CallFuncBreakHitResultNormal, struct FVector& CallFuncBreakHitResultImpactNormal, class UPhysicalMaterial*& CallFuncBreakHitResultPhysMat, class AActor*& CallFuncBreakHitResultHitActor, class UPrimitiveComponent*& CallFuncBreakHitResultHitComponent, struct FName& CallFuncBreakHitResultHitBoneName, struct FName& CallFuncBreakHitResultBoneName, int& CallFuncBreakHitResultHitItem, int& CallFuncBreakHitResultElementIndex, int& CallFuncBreakHitResultFaceIndex, struct FVector& CallFuncBreakHitResultTraceStart, struct FVector& CallFuncBreakHitResultTraceEnd, bool& CallFuncEqualEqualObjectObjectReturnValue, float& CallFuncLineTraceSingleDrawTimeImplicitCast, double& K2NodeFunctionResultDistanceImplicitCast); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.NPC_LockThenRotateInPlace (Has no native function)
	static void NPCLockThenRotateInPlace(bool& LockedInPlace, class AFortPlayerPawn*& PlayerPawn, class AFortAIPawn*& SurvivorPawn, class UObject*& WorldContext, struct FStruct_SurvivorScriptedAbilities& SurvivorAbilities, struct FGameplayEventData& K2NodeMakeStructGameplayEventData, struct FGameplayEventData& K2NodeMakeStructGameplayEventData1); // (Static | Public | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.GetControllersNearActorThatRequireQuestObjective (Has no native function)
	static void GetControllersNearActorThatRequireQuestObjective(double& Distance, class AActor*& Actor, class UFortQuestItemDefinition*& QuestItem, struct FName& QuestItemBackendObjectiveName, class UObject*& WorldContext, struct TArray<class AFortPlayerController*>& PlayerControllersNearbyThatRequireQuest, bool& SuccessfullyFoundPlayer, struct FName& LocalBackendName, class UFortQuestItemDefinition*& LocalQuestItem, struct TArray<class AFortPlayerController*>& ControllersWhoRequireQuestObjective, struct TArray<class AFortPlayerController*>& ControllersNearbyArray, bool& FoundPlayer, bool& CallFuncAnyPlayerNearActorIsPlayerNearActor, struct TArray<class AFortPlayerPawn*>& CallFuncAnyPlayerNearActorPlayersNearActor, int& CallFuncArrayLengthReturnValue, bool& CallFuncIsValidReturnValue, bool& CallFuncIsValidReturnValue1, int& TempintArrayIndexVariable, class AFortPlayerPawn*& CallFuncArrayGetItem, class AController*& CallFuncGetControllerReturnValue, int& TempintLoopCounterVariable, class AFortPlayerController*& K2NodeDynamicCastAsFortPlayerController, bool& K2NodeDynamicCastbSuccess, bool& CallFuncLessIntIntReturnValue, int& CallFuncAddIntIntReturnValue, int& TempintArrayIndexVariable1, class AFortPlayerController*& CallFuncArrayGetItem1, int& CallFuncArrayLengthReturnValue1, bool& CallFuncDoesPlayerHaveQuestQuestValid, class AFortPlayerController*& CallFuncDoesPlayerHaveQuestPlayerControllerRef, int& TempintLoopCounterVariable1, int& CallFuncArrayAddUniqueReturnValue, bool& CallFuncLessIntIntReturnValue1, int& CallFuncAddIntIntReturnValue1, int& CallFuncArrayAddUniqueReturnValue1); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.HaveAllPlayersCompletedQuest (Has no native function)
	static void HaveAllPlayersCompletedQuest(class UFortQuestItemDefinition*& QuestItem, class UObject*& WorldContext, bool& AllPlayersCompletedQuest, bool& NotCompleted, int& TempintArrayIndexVariable, struct TArray<class AFortPlayerController*>& CallFuncGetAllFortPlayerControllersReturnValue, class AFortPlayerController*& CallFuncArrayGetItem, int& CallFuncArrayLengthReturnValue, class UFortQuestManager*& CallFuncGetQuestManagerReturnValue, bool& CallFuncIsValidReturnValue, class UFortQuestItem*& CallFuncGetQuestWithDefinitionReturnValue, bool& CallFuncHasCompletedQuestReturnValue, bool& CallFuncIsValidReturnValue1, int& TempintLoopCounterVariable, bool& CallFuncLessIntIntReturnValue, int& CallFuncAddIntIntReturnValue, bool& TempboolTrueifbreakwashitVariable, bool& CallFuncNotPreBoolReturnValue, bool& CallFuncBooleanANDReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.HasPlayerCompletedQuestObjectiveHandle (Has no native function)
	static void HasPlayerCompletedQuestObjectiveHandle(class AFortPlayerController*& PlayerController, class UFortQuestItemDefinition*& QuestReference, struct FDataTableRowHandle& QuestBackendObjectiveHandle, class UObject*& WorldContext, class AFortPlayerController*& PlayerControllerOut, bool& CompletedQuestObjective, bool& HasCompletedObjective, bool& CallFuncIsValidReturnValue, bool& CallFuncIsValidReturnValue1, class UFortQuestManager*& CallFuncGetQuestManagerReturnValue, class UFortQuestItem*& CallFuncGetQuestWithDefinitionReturnValue, bool& CallFuncIsValidReturnValue2, bool& CallFuncHasCompletedObjectiveReturnValue); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.DoesAnyPlayerRequireQuestObjective (Has no native function)
	static void DoesAnyPlayerRequireQuestObjective(class UFortQuestItemDefinition*& QuestReference, struct FDataTableRowHandle& QuestObjectiveHandle, class UObject*& WorldContext, struct TArray<class AFortPlayerController*>& PlayerControllersWhoRequireObjective, bool& SomebodyRequiresObjective, struct TArray<class AFortPlayerController*>& ControllersWhoRequireObjective, bool& SomebodyNeededTheObjective, int& TempintArrayIndexVariable, struct TArray<class AFortPlayerController*>& CallFuncGetAllFortPlayerControllersReturnValue, class AFortPlayerController*& CallFuncArrayGetItem, int& CallFuncArrayLengthReturnValue, bool& CallFuncIsValidReturnValue, class UFortQuestManager*& CallFuncGetQuestManagerReturnValue, class UFortQuestItem*& CallFuncGetQuestWithDefinitionReturnValue, int& CallFuncArrayLengthReturnValue1, bool& CallFuncIsValidReturnValue1, bool& CallFuncGreaterEqualIntIntReturnValue, bool& CallFuncHasCompletedObjectiveReturnValue, bool& CallFuncIsValidReturnValue2, int& TempintLoopCounterVariable, int& CallFuncArrayAddUniqueReturnValue, bool& CallFuncLessIntIntReturnValue, int& CallFuncAddIntIntReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.HideParticleComponentsAttachedToMesh (Has no native function)
	static void HideParticleComponentsAttachedToMesh(class UStaticMeshComponent*& MeshComponent, class UObject*& WorldContext, bool& SuccessfullyDeactivatedParticle, bool& FoundParticle, bool& CallFuncIsValidReturnValue, struct TArray<class USceneComponent*>& CallFuncGetChildrenComponentsChildren, int& CallFuncArrayLengthReturnValue, int& CallFuncArrayLengthReturnValue1, int& TempintArrayIndexVariable, bool& CallFuncGreaterEqualIntIntReturnValue, class USceneComponent*& CallFuncArrayGetItem, class UParticleSystemComponent*& K2NodeDynamicCastAsCascadeParticleSystemComponent, bool& K2NodeDynamicCastbSuccess, bool& CallFuncIsValidReturnValue1, int& TempintLoopCounterVariable, bool& CallFuncLessIntIntReturnValue, int& CallFuncAddIntIntReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.HasPlayerCompletedQuestObjective (Has no native function)
	static void HasPlayerCompletedQuestObjective(class AFortPlayerController*& PlayerController, class UFortQuestItemDefinition*& QuestReference, struct FName& QuestBackendObjectiveName, class UObject*& WorldContext, class AFortPlayerController*& PlayerControllerOut, bool& CompletedQuestObjective, bool& HasCompletedObjective, bool& CallFuncEqualEqualNameNameReturnValue, bool& CallFuncIsValidReturnValue, bool& CallFuncIsValidReturnValue1, class UFortQuestManager*& CallFuncGetQuestManagerReturnValue, class UFortQuestItem*& CallFuncGetQuestWithDefinitionReturnValue, bool& CallFuncIsValidReturnValue2, bool& CallFuncIsValidReturnValue3, bool& CallFuncHasCompletedObjectiveWithNameReturnValue); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.GetContributingControllersNearActor (Has no native function)
	static void GetContributingControllersNearActor(double& Distance, class AActor*& Actor, class UObject*& WorldContext, struct TArray<class AFortPlayerController*>& PlayerControllersNearby, bool& SuccessfullyFoundPlayer, struct TArray<class AFortPlayerController*>& ControllersNearbyArray, bool& FoundPlayer, bool& CallFuncAnyPlayerNearActorIsPlayerNearActor, struct TArray<class AFortPlayerPawn*>& CallFuncAnyPlayerNearActorPlayersNearActor, bool& CallFuncIsValidReturnValue, int& CallFuncArrayLengthReturnValue, int& TempintArrayIndexVariable, class AFortPlayerPawn*& CallFuncArrayGetItem, class AController*& CallFuncGetControllerReturnValue, class AFortPlayerController*& K2NodeDynamicCastAsFortPlayerController, bool& K2NodeDynamicCastbSuccess, int& TempintLoopCounterVariable, int& CallFuncArrayAddUniqueReturnValue, bool& CallFuncLessIntIntReturnValue, int& CallFuncAddIntIntReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.PointLocationsBetweenTwoVectors (Has no native function)
	static void PointLocationsBetweenTwoVectors(struct FVector& Vector1, struct FVector& Vector2, int& HowManyPoints, class UObject*& WorldContext, struct TArray<struct FVector>& VectorPoints, bool& SuccessfullyFoundPoints, bool& WasSuccessful, struct TArray<struct FVector>& ResultVectorArray, struct FVector& DifferenceVector, bool& CallFuncGreaterEqualIntIntReturnValue, struct FVector& CallFuncSubtractVectorVectorReturnValue, struct FVector& CallFuncDivideVectorIntReturnValue, int& CallFuncArrayLengthReturnValue, bool& CallFuncGreaterEqualIntIntReturnValue1, int& TempintVariable, int& CallFuncAddIntIntReturnValue, struct FVector& CallFuncMultiplyVectorIntReturnValue, struct FVector& CallFuncAddVectorVectorReturnValue, int& CallFuncArrayAddUniqueReturnValue, bool& CallFuncLessEqualIntIntReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.GetCurrentDifficulty (Has no native function)
	static void GetCurrentDifficulty(class UObject*& WorldContext, double& Difficulty, bool& Success, class AGameStateBase*& CallFuncGetGameStateReturnValue, class AFortGameStateZone*& K2NodeDynamicCastAsFortGameStateZone, bool& K2NodeDynamicCastbSuccess, float& CallFuncGetGameDifficultyReturnValue, double& K2NodeFunctionResultDifficultyImplicitCast); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.ApplyDifficultyOffset (Has no native function)
	static void ApplyDifficultyOffset(struct FName& RowName, double& BaseDifficulty, class UObject*& WorldContext, bool& Success, struct TEnumAsByte<EEvaluateCurveTableResult>& CallFuncEvaluateCurveTableRowOutResult, float& CallFuncEvaluateCurveTableRowOutXY, double& CallFuncGetCurrentDifficultyDifficulty, bool& CallFuncGetCurrentDifficultySuccess, bool& K2NodeSwitchEnumCmpSuccess, double& CallFuncSubtractDoubleDoubleReturnValue, double& CallFuncAddDoubleDoubleReturnValue, float& CallFuncEvaluateCurveTableRowInXYImplicitCast, double& CallFuncAddDoubleDoubleAImplicitCast, float& CallFuncAdjustWaveBasedGameDifficultyfDifficultyAddModImplicitCast); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.DistanceBetweenTwoVectors (Has no native function)
	static void DistanceBetweenTwoVectors(struct FVector& vector1, struct FVector& vector2, class UObject*& WorldContext, double& Distance, struct FVector& CallFuncSubtractVectorVectorReturnValue, double& CallFuncVSizeReturnValue); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.HasPlayerCompletedQuest (Has no native function)
	static void HasPlayerCompletedQuest(class AFortPlayerController*& PlayerController, class UFortQuestItemDefinition*& QuestReference, struct FName& QuestBackendName, class UObject*& WorldContext, class AFortPlayerController*& PlayerControllerOut, bool& CompletedQuest, bool& HasCompletedQuest, bool& CallFuncEqualEqualNameNameReturnValue, bool& CallFuncEqualEqualNameNameReturnValue1, bool& CallFuncIsValidReturnValue, bool& CallFuncHasComponentForWorldProcessingUpdatesReturnValue, struct FString& CallFuncGetPersistentNameReturnValue, bool& CallFuncIsValidReturnValue1, class UFortPlayerStateComponent_Quests*& CallFuncGetComponentByClassReturnValue, class UFortQuestManager*& CallFuncGetQuestManagerReturnValue, bool& CallFuncIsValidReturnValue2, class UFortQuestItem*& CallFuncGetQuestWithDefinitionReturnValue, bool& CallFuncIsValidReturnValue3, bool& CallFuncIsValidReturnValue4, bool& CallFuncHasCompletedObjectiveWithNameReturnValue, bool& CallFuncHasCompletedQuestReturnValue, bool& CallFuncIsQuestInstanceCompletedReturnValue, bool& CallFuncIsQuestInstanceObjectiveCompletedReturnValue); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.SeperatePlayersWhoNeedQuest (Has no native function)
	static void SeperatePlayersWhoNeedQuest(class UFortQuestItemDefinition*& QuestItemReference, struct FName& QuestObjectiveBackendName, class UObject*& WorldContext, struct TArray<class AFortPlayerController*>& PlayersWhoNeedQuest, struct TArray<class AFortPlayerController*>& PlayersWhoDoNotNeedQuest, struct TArray<class AFortPlayerController*>& NotRequireQuest, struct TArray<class AFortPlayerController*>& RequireQuest, int& TempintArrayIndexVariable, struct TArray<class AFortPlayerController*>& CallFuncGetAllFortPlayerControllersReturnValue, class AFortPlayerController*& CallFuncArrayGetItem, int& CallFuncArrayLengthReturnValue, bool& CallFuncIsValidReturnValue, class UFortQuestManager*& CallFuncGetQuestManagerReturnValue, class UFortQuestItem*& CallFuncGetQuestWithDefinitionReturnValue, bool& CallFuncHasCompletedObjectiveWithNameReturnValue, bool& CallFuncIsValidReturnValue1, int& CallFuncArrayAddUniqueReturnValue, int& CallFuncArrayAddUniqueReturnValue1, int& TempintLoopCounterVariable, int& CallFuncArrayAddUniqueReturnValue2, bool& CallFuncLessIntIntReturnValue, int& CallFuncAddIntIntReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.BasicBuildingItemDrop (Has no native function)
	static void BasicBuildingItemDrop(struct TEnumAsByte<EnumEventWorldItemDrop>& ItemDropLevel, struct FVector& LootDropLocation, class UObject*& WorldContext, int& ItemsToSpawnPerRoll, struct FVector& SpawnVector, double& CallFuncRandomFloatInRangeReturnValue, bool& K2NodeSwitchEnumCmpSuccess, double& CallFuncRandomFloatInRangeReturnValue1, double& CallFuncRandomFloatInRangeReturnValue2, double& CallFuncRandomFloatInRangeReturnValue3, double& CallFuncRandomFloatInRangeReturnValue4, double& CallFuncRandomFloatInRangeReturnValue5, int& TempintVariable, bool& CallFuncLessEqualIntIntReturnValue, int& CallFuncAddIntIntReturnValue, double& CallFuncBreakVectorX, double& CallFuncBreakVectorY, double& CallFuncBreakVectorZ, double& CallFuncBreakVectorX1, double& CallFuncBreakVectorY1, double& CallFuncBreakVectorZ1, double& CallFuncAddDoubleDoubleReturnValue, double& CallFuncAddDoubleDoubleReturnValue1, double& CallFuncAddDoubleDoubleReturnValue2, double& CallFuncAddDoubleDoubleReturnValue3, double& CallFuncAddDoubleDoubleReturnValue4, struct FVector& CallFuncMakeVectorReturnValue, double& CallFuncAddDoubleDoubleReturnValue5, class AFortPickup*& CallFuncK2SpawnPickupInWorldReturnValue, struct FVector& CallFuncMakeVectorReturnValue1, class AFortPickup*& CallFuncK2SpawnPickupInWorldReturnValue1, double& CallFuncBreakVectorX2, double& CallFuncBreakVectorY2, double& CallFuncBreakVectorZ2, bool& K2NodeMultiGateFirstRun, int& K2NodeMultiGateData, bool& K2NodeMultiGateScratchBool, int& K2NodeMultiGateScratchIndex, double& CallFuncAddDoubleDoubleReturnValue6, double& CallFuncAddDoubleDoubleReturnValue7, double& CallFuncAddDoubleDoubleReturnValue8, struct FVector& CallFuncMakeVectorReturnValue2, class AFortPickup*& CallFuncK2SpawnPickupInWorldReturnValue2); // (Static | Public | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.GetBuildingRecommendation (Has no native function)
	static void GetBuildingRecommendation(struct FName& RowName, class UObject*& WorldContext, int& BuildingCount, bool& RowFound, double& CallFuncGetCurrentDifficultyDifficulty, bool& CallFuncGetCurrentDifficultySuccess, struct TEnumAsByte<EEvaluateCurveTableResult>& CallFuncEvaluateCurveTableRowOutResult, float& CallFuncEvaluateCurveTableRowOutXY, int& CallFuncRoundReturnValue, bool& K2NodeSwitchEnumCmpSuccess, float& CallFuncEvaluateCurveTableRowInXYImplicitCast, double& CallFuncRoundAImplicitCast); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.Random_360_VectorInRange (Has no native function)
	static void Random360VectorInRange(double& MinDistance, double& MaxDistance, class UObject*& WorldContext, struct FVector& RandomVectorResult, double& CallFuncRandomFloatInRangeReturnValue, double& CallFuncRandomFloatInRangeReturnValue1, struct FVector& CallFuncMakeVectorReturnValue, struct FVector& CallFuncRotateAngleAxisReturnValue, float& CallFuncRotateAngleAxisAngleDegImplicitCast); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.AnyPawnNearActor (Has no native function)
	static void AnyPawnNearActor(double& DistanceToCheck, class AActor*& Actor, class UObject*& WorldContext, bool& IsPawnNearActor, struct TArray<class AFortPawn*>& PawnsNearActor, struct TArray<class AFortPawn*>& Pawns, int& TempintArrayIndexVariable, struct TArray<class AFortPawn*>& CallFuncGetAllActorsOfClassOutActors, class AFortPawn*& CallFuncArrayGetItem, int& CallFuncArrayLengthReturnValue, float& CallFuncGetDistanceToReturnValue, bool& CallFuncIsValidReturnValue, bool& CallFuncLessEqualDoubleDoubleReturnValue, int& TempintLoopCounterVariable, bool& CallFuncLessIntIntReturnValue, int& CallFuncAddIntIntReturnValue, int& CallFuncArrayLengthReturnValue1, int& CallFuncArrayAddUniqueReturnValue, bool& CallFuncGreaterEqualIntIntReturnValue, double& CallFuncLessEqualDoubleDoubleAImplicitCast); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.GiveQuestUpdateToPlayers (Has no native function)
	static void GiveQuestUpdateToPlayers(class UFortQuestItemDefinition*& QuestReference, struct FName& QuestObjectiveBackendName, struct FDataTableRowHandle& ObjectiveStatEvent, struct TArray<class AFortPlayerController*>& PlayerControllersForUpdate, class UObject*& WorldContext, int& TempintArrayIndexVariable, int& CallFuncArrayLengthReturnValue, class AFortPlayerController*& CallFuncArrayGetItem, bool& CallFuncIsValidReturnValue, class UFortQuestManager*& CallFuncGetQuestManagerReturnValue, class UFortQuestItem*& CallFuncGetQuestWithDefinitionReturnValue, bool& CallFuncIsValidReturnValue1, bool& CallFuncIsValidReturnValue2, bool& CallFuncHasCompletedObjectiveWithNameReturnValue, int& TempintLoopCounterVariable, bool& CallFuncLessIntIntReturnValue, int& CallFuncAddIntIntReturnValue); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.DropChance (Has no native function)
	static void DropChance(double& DropPercentChance, class UObject*& WorldContext, bool& DropResult, double& CallFuncFClampReturnValue, bool& CallFuncGreaterEqualDoubleDoubleReturnValue, double& CallFuncRandomFloatInRangeReturnValue, bool& CallFuncLessEqualDoubleDoubleReturnValue); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.AnyPlayerNearActor (Has no native function)
	static void AnyPlayerNearActor(double& DistanceToCheck, class AActor*& Actor, class UObject*& WorldContext, bool& IsPlayerNearActor, struct TArray<class AFortPlayerPawn*>& PlayersNearActor, struct TArray<class AFortPlayerPawn*>& PlayerPawns, struct TArray<class AFortPlayerPawn*>& CallFuncGetAllFortPlayerPawnsOutFortPlayerPawns, bool& CallFuncIsValidReturnValue, int& CallFuncArrayLengthReturnValue, int& TempintArrayIndexVariable, class AFortPlayerPawn*& CallFuncArrayGetItem, int& CallFuncArrayLengthReturnValue1, float& CallFuncGetDistanceToReturnValue, bool& CallFuncGreaterEqualIntIntReturnValue, bool& CallFuncLessEqualDoubleDoubleReturnValue, int& TempintLoopCounterVariable, int& CallFuncArrayAddUniqueReturnValue, bool& CallFuncLessIntIntReturnValue, int& CallFuncAddIntIntReturnValue, double& CallFuncLessEqualDoubleDoubleAImplicitCast); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.FlashObjectiveUI (Has no native function)
	static void FlashObjectiveUI(class AFortObjectiveBase*& ObjectiveReference, class UObject*& WorldContext, struct FGameplayTagContainer& CallFuncMakeLiteralGameplayTagContainerReturnValue); // (Static | Public | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.NPC_DroneStopRescue (Has no native function)
	static void NPCDroneStopRescue(class AActor*& Actor, class AActor*& Instigator, class UObject*& WorldContext, struct FStruct_SurvivorScriptedAbilities& SurvivorAbilityStruct, struct FGameplayEventData& K2NodeMakeStructGameplayEventData); // (Static | Public | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.NPC_DroneStartRescue (Has no native function)
	static void NPCDroneStartRescue(class AActor*& Actor, class AActor*& Instigator, class UObject*& WorldContext, struct FStruct_SurvivorScriptedAbilities& SurvivorAbilityStruct, struct FGameplayEventData& K2NodeMakeStructGameplayEventData); // (Static | Public | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.ListPlayersWhoNeedQuest (Has no native function)
	static void ListPlayersWhoNeedQuest(class UFortQuestItemDefinition*& QuestReference, struct FName& QuestBackendName, class UObject*& WorldContext, struct TArray<class AFortPlayerController*>& PlayerControllersWhoRequireTheQuest, bool& DoesAnyoneRequireTheQuest, bool& PlayerNeededTheQuest, struct TArray<class AFortPlayerController*>& PlayersWhoRequireQuest, struct TArray<class AFortPlayerController*>& CallFuncGetAllFortPlayerControllersReturnValue, int& TempintLoopCounterVariable, int& CallFuncArrayLengthReturnValue, int& CallFuncAddIntIntReturnValue, bool& CallFuncLessIntIntReturnValue, int& CallFuncArrayLengthReturnValue1, int& TempintArrayIndexVariable, bool& CallFuncGreaterEqualIntIntReturnValue, class AFortPlayerController*& CallFuncArrayGetItem, class UFortQuestManager*& CallFuncGetQuestManagerReturnValue, bool& CallFuncHasCompletedObjectiveWithNameReturnValue, int& CallFuncArrayAddUniqueReturnValue, int& CallFuncArrayLengthReturnValue2, bool& CallFuncGreaterEqualIntIntReturnValue1); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.DoesAnyoneRequireQuest (Has no native function)
	static void DoesAnyoneRequireQuest(class UFortQuestItemDefinition*& QuestReference, struct FName& QuestBackendName, class UObject*& WorldContext, bool& SomePlayerNeedsTheQuest, bool& PlayerNeedsQuest, int& TempintArrayIndexVariable, struct TArray<class AFortPlayerController*>& CallFuncGetAllFortPlayerControllersReturnValue, class AFortPlayerController*& CallFuncArrayGetItem, int& CallFuncArrayLengthReturnValue, class UFortQuestManager*& CallFuncGetQuestManagerReturnValue, int& CallFuncArrayLengthReturnValue1, class UFortQuestItem*& CallFuncGetQuestWithDefinitionReturnValue, bool& CallFuncGreaterEqualIntIntReturnValue, bool& CallFuncIsValidReturnValue, bool& CallFuncHasCompletedObjectiveWithNameReturnValue, int& TempintLoopCounterVariable, bool& CallFuncLessIntIntReturnValue, int& CallFuncAddIntIntReturnValue, bool& TempboolTrueifbreakwashitVariable, bool& CallFuncNotPreBoolReturnValue, bool& CallFuncBooleanANDReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.QuestObjectiveCountAchieved (Has no native function)
	static void QuestObjectiveCountAchieved(class AFortPlayerController*& PlayerControllerReference, class UFortQuestItemDefinition*& QuestItemReference, struct FDataTableRowHandle& ObjectiveStatHandle, class UObject*& WorldContext, int& QuestCountAchieved, int& QuestCountRequired, bool& SuccessfullyFoundCount, int& LocalRequiredCount, int& LocalAchievedCount, bool& bSuccessfullyFoundStage, bool& CallFuncIsValidReturnValue, class UFortQuestManager*& CallFuncGetQuestManagerReturnValue, class UFortQuestItem*& CallFuncGetQuestWithDefinitionReturnValue, class UFortQuestObjectiveInfo*& CallFuncGetObjectiveInfoReturnValue, bool& CallFuncIsValidReturnValue1); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.HighlightQuestActor (Has no native function)
	static void HighlightQuestActor(class AActor*& ActorToHighlight, bool& HighlightEnabled, class UObject*& WorldContext, class ABuildingActor*& K2NodeDynamicCastAsBuildingActor, bool& K2NodeDynamicCastbSuccess, float& CallFuncGetScalarParameterValueReturnValue, class ABuildingSMActor*& K2NodeDynamicCastAsBuildingStaticMesh, bool& K2NodeDynamicCastbSuccess1, int& CallFuncFTruncReturnValue, class UStaticMeshComponent*& CallFuncGetBuildingMeshComponentReturnValue, class UStaticMeshComponent*& CallFuncGetBuildingMeshComponentReturnValue1, float& CallFuncGetScalarParameterValueReturnValue1, int& CallFuncFTruncReturnValue1, double& CallFuncFTruncAImplicitCast, double& CallFuncFTruncAImplicitCast1); // (Static | Public | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.DoesPlayerHaveQuest (Has no native function)
	static void DoesPlayerHaveQuest(class AFortPlayerController*& PlayerController, class UFortQuestItemDefinition*& QuestItemReference, struct FName& QuestItemObjectiveBackendName, class UObject*& WorldContext, bool& QuestValid, class AFortPlayerController*& PlayerControllerRef, class UFortQuestManager*& CallFuncGetQuestManagerReturnValue, bool& CallFuncIsValidReturnValue, class UFortQuestItem*& CallFuncGetQuestWithDefinitionReturnValue, bool& CallFuncHasCompletedObjectiveWithNameReturnValue, bool& CallFuncIsValidReturnValue1, bool& CallFuncIsValidReturnValue2); // (Static | Public | HasOutParms | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.GetObjectiveBadgeIconBrush (Has no native function)
	static void GetObjectiveBadgeIconBrush(class AFortObjectiveBase*& Objective, struct FGameplayTag& RewardTag, class UObject*& WorldContext, struct FSlateBrush& IconBrush, class UFortBadgeItemDefinition*& BadgeItem, bool& TempboolTrueifbreakwashitVariable, struct TArray<class UFortWorldItemDefinition*>& CallFuncGetRewardItemsByTagOutRewardItems, int& CallFuncArrayLengthReturnValue, int& CallFuncArrayLengthReturnValue1, bool& CallFuncNotPreBoolReturnValue, bool& CallFuncGreaterIntIntReturnValue, bool& CallFuncLessIntIntReturnValue, int& TempintArrayIndexVariable, class UFortWorldItemDefinition*& CallFuncArrayGetItem, class UFortBadgeItemDefinition*& K2NodeDynamicCastAsFortBadgeItemDefinition, bool& K2NodeDynamicCastbSuccess, int& TempintLoopCounterVariable, bool& CallFuncLessIntIntReturnValue1, int& CallFuncAddIntIntReturnValue, bool& CallFuncBooleanANDReturnValue, struct FSlateBrush& CallFuncGetSmallPreviewImageBrushReturnValue, bool& CallFuncIsValidReturnValue); // (Static | Public | HasOutParms | HasDefaults | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.UnRegisterUI UpdatesWithDamageEvents (Has no native function)
	static void UnRegisterUIUpdatesWithDamageEvents(class AActor*& ActorToUnRegisterWith, class AFortMissionState*& MissionState, class UObject*& WorldContext, class ABuildingActor*& K2NodeDynamicCastAsBuildingActor, bool& K2NodeDynamicCastbSuccess, struct FDelegate& K2NodeCreateDelegateOutputDelegate, struct FDelegate& K2NodeCreateDelegateOutputDelegate1, class AFortPawn*& K2NodeDynamicCastAsFortPawn, bool& K2NodeDynamicCastbSuccess1); // (Static | Public | BlueprintCallable | BlueprintEvent)

	// Function /Game/Missions/FunctionLibrary/MissionBlueprintFunctionLibrary.MissionBlueprintFunctionLibrary_C.RegisterUI UpdatesWithDamageEvents (Has no native function)
	static void RegisterUIUpdatesWithDamageEvents(class AActor*& ActorToRegisterWith, class AFortMissionState*& MissionState, class UObject*& WorldContext, class ABuildingActor*& K2NodeDynamicCastAsBuildingActor, bool& K2NodeDynamicCastbSuccess, struct FDelegate& K2NodeCreateDelegateOutputDelegate, struct FDelegate& K2NodeCreateDelegateOutputDelegate1, class AFortPawn*& K2NodeDynamicCastAsFortPawn, bool& K2NodeDynamicCastbSuccess1); // (Static | Public | BlueprintCallable | BlueprintEvent)
};

